---
title: "Flavio Damasneco's cow study"
author: "Análise: [Henrique Laureano](https://henriquelaureano.github.io/)"
date: "*Last modification on* `r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float: true
---

```{r, echo=FALSE}

if (!requireNamespace('knitr', quietly=TRUE)) install.packages('knitr')
library(knitr)
options(width=100)
knitr::opts_chunk$set(fig.path='figuras/', fig.align='center',
                      ## dev=c('pdf', 'png'),
                      warning=FALSE, message=FALSE, prompt=FALSE,
                      echo=FALSE, comment=NA)

```

***

```{r pkgs}

if (!requireNamespace('pacman', quietly=TRUE)) install.packages('pacman')
pacman::p_load(
            ## data manipulation
            purrr, readxl, dplyr, tidyr, lubridate, stringr, haven,
            ## data analysis
            MASS, broom, 
            ## data visualization
            ggplot2, ggthemes, patchwork, psych, kableExtra
        )
source('../i4p-colors/i4p-palette.R')
```

```{r data}

sheet_names <- c('CCS', 'CBT', 'Gord', 'Proteína', 'Produção', 'Peso',
                 'Esc corporal', 'Esc higiene', 'Esc locom',
                 'Umid cama sup', 'Umid cama 20',
                 'Temp cama sup', 'Temp cama 20', 'C/N cama', 'pH cama')
dat <- 
    purrr::map(seq(length(sheet_names)),
               ~readxl::read_xlsx(path='novos_dados-sheet1.xlsx',
                                  sheet=.x))
names(dat) <- sheet_names

dat <- dplyr::bind_rows(dat, .id='variable')|>
    tidyr::pivot_longer(dplyr::starts_with('Semana'),
                        names_to='Semana', values_to='valor')|>
    dplyr::relocate(Semana, .after=Tempo)|>
    dplyr::relocate(valor, .after=Semana)|>
    dplyr::mutate(Tempo=rep(seq(as.Date('2019/3/8'),
                                as.Date('2020/2/28'), length.out=48), 
                            times=length(sheet_names)))

```

# Séries semanais

***

## CCS, CBT, Gord

```{r ccs_cbt_gord,fig.height=10,fig.width=10}

ccs <- dat|>
    dplyr::filter(variable=='CCS')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(180, 480, length.out=5))+
    labs(title='CCS')+
    theme_fivethirtyeight(base_size=16)

cbt <- dat|>
    dplyr::filter(variable=='CBT')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(2, 32, length.out=5))+
    labs(title='CBT')+
    theme_fivethirtyeight(base_size=16)

gord <- dat|>
    dplyr::filter(variable=='Gord')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(2.8, 4.5, length.out=5))+
    labs(title='Gordura')+
    theme_fivethirtyeight(base_size=16)

ccs / cbt / gord

```

## Proteína, Produção, Peso

```{r proteina_producao_peso,fig.height=10,fig.width=10}

proteína <- dat|>
    dplyr::filter(variable=='Proteína')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(3, 3.7, length.out=5))+
    labs(title='Proteína')+
    theme_fivethirtyeight(base_size=16)

produção <- dat|>
    dplyr::filter(variable=='Produção')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(800, 1500, length.out=5))+
    labs(title='Produção')+
    theme_fivethirtyeight(base_size=16)

peso <- dat|>
    dplyr::filter(variable=='Peso')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(615, 665, length.out=5))+
    labs(title='Peso')+
    theme_fivethirtyeight(base_size=16)

proteína / produção / peso

```

## Esc- corporal, higiene, locom

```{r esc_corporol_higiene_locom,fig.height=10,fig.width=10}

esc_corporol <- dat|>
    dplyr::filter(variable=='Esc corporal')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(2.9, 3.8, length.out=5))+
    labs(title='Esc corporal')+
    theme_fivethirtyeight(base_size=16)

esc_higiene <- dat|>
    dplyr::filter(variable=='Esc higiene')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(1, 1.6, length.out=5))+
    labs(title='Esc higiene')+
    theme_fivethirtyeight(base_size=16)

esc_locom <- dat|>
    dplyr::filter(variable=='Esc locom')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(1, 1.7, length.out=5))+
    labs(title='Esc locom')+
    theme_fivethirtyeight(base_size=16)

esc_corporol / esc_higiene / esc_locom

```

## Umid cama

```{r umid_cama,fig.height=2*10/3,fig.width=10}

umid_cama_sup <- dat|>
    dplyr::filter(variable=='Umid cama sup')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(30, 52, length.out=5))+
    labs(title='Umid cama sup')+
    theme_fivethirtyeight(base_size=16)

umid_cama_20 <- dat|>
    dplyr::filter(variable=='Umid cama 20')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(27, 47.5, length.out=5))+
    labs(title='Umid cama 20')+
    theme_fivethirtyeight(base_size=16)

umid_cama_sup / umid_cama_20

```

## Temp cama

```{r temp_cama,fig.height=2*10/3,fig.width=10}

temp_cama_sup <- dat|>
    dplyr::filter(variable=='Temp cama sup')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(20.5, 35, length.out=5))+
    labs(title='Temp cama sup')+
    theme_fivethirtyeight(base_size=16)

temp_cama_20 <- dat|>
    dplyr::filter(variable=='Temp cama 20')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(37.5, 56.5, length.out=5))+
    labs(title='Temp cama 20')+
    theme_fivethirtyeight(base_size=16)

temp_cama_sup / temp_cama_20

```

## C/N e pH cama

```{r cn_ph_cama,fig.height=2*10/3,fig.width=10}

cn_cama <- dat|>
    dplyr::filter(variable=='C/N cama')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(12, 26, length.out=5))+
    labs(title='C/N cama')+
    theme_fivethirtyeight(base_size=16)

ph_cama <- dat|>
    dplyr::filter(variable=='pH cama')|>
    ggplot(aes(x=Tempo, y=valor))+
    geom_line(size=1)+
    geom_smooth(method=lm, formula=y ~ poly(x, 3), se=TRUE)+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(7, 9.75, length.out=5))+
    labs(title='pH cama')+
    theme_fivethirtyeight(base_size=16)

cn_cama / ph_cama

```

# Modelos

***

## CCS

```{r ccs_dat}

dat_ccs <- dat|>
    dplyr::filter(variable%in%c('CCS',
                                'Umid cama sup', 'Umid cama 20',
                                'Temp cama sup', 'Temp cama 20',
                                'pH cama'))|>
    dplyr::select(variable, Tempo, valor)|>
    tidyr::pivot_wider(names_from=variable, values_from=valor)|>
    dplyr::mutate(Mês=lubridate::month(Tempo, label=TRUE), 
                  Mês=as.character(Mês), 
                  Mês=stringr::str_to_sentence(Mês),
                  Mês=haven::as_factor(Mês))|>
    dplyr::relocate(Mês, .after=Tempo)

```

```{r ccs_sub_20,fig.height=7}

dat_ccs|>
    dplyr::select(where(is.numeric) | where(is.factor))|>
    dplyr::select(!dplyr::ends_with('20'))|>
    pairs.panels(density=TRUE,
                 hist.col=7,
                 pch=21,
                 lm=TRUE, ## linear fit rather the LOESS (smoothed) fit
                 ci=TRUE,
                 cor=TRUE,
                 method='pearson', ## or 'spearman' or 'kendall'
                 stars=TRUE,
                 ellipses=TRUE, ## correlation ellipses
                 cex.axis=1.1)

dat_ccs|>
    dplyr::select(where(is.numeric) | where(is.factor))|>
    dplyr::select(!dplyr::ends_with('sup'))|>
    pairs.panels(density=TRUE,
                 hist.col=7,
                 pch=21,
                 lm=TRUE, ## linear fit rather the LOESS (smoothed) fit
                 ci=TRUE, 
                 cor=TRUE,
                 method='pearson', ## or 'spearman' or 'kendall'
                 stars=TRUE,
                 ellipses=TRUE, ## correlation ellipses
                 cex.axis=1.1)

```

```{r ccs_fit,fig.height=8,fig.width=10}

ccs_sup.fit <-
    MASS::stepAIC(
              lm(CCS ~ Mês+`Umid cama sup`*`Temp cama sup`*`pH cama`,
                 dat_ccs),
              direction='both', trace=FALSE)

ccs_sup.aug <- dplyr::bind_cols(Tempo=dat_ccs$Tempo,
                                broom::augment(ccs_sup.fit, se_fit=TRUE))

ccs_sup.plot <- ccs_sup.aug|>
    ggplot(aes(x=Tempo, y=CCS))+
    geom_line(size=1)+
    geom_line(aes(y=.fitted), size=1, col='#ff0000')+
    geom_ribbon(aes(ymin=(.fitted - 1.96 * .se.fit),
                    ymax=(.fitted + 1.96 * .se.fit)),
                alpha=0.25, fill='orange', col='#0080ff')+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(180, 480, length.out=5))+
    labs(title='CCS_sup')+
    theme_fivethirtyeight(base_size=16)

ccs_20.fit <-
    MASS::stepAIC(
              lm(CCS ~ Mês+`Umid cama 20`*`Temp cama 20`*`pH cama`,
                 dat_ccs),
              direction='both', trace=FALSE)

ccs_20.aug <- dplyr::bind_cols(Tempo=dat_ccs$Tempo,
                               broom::augment(ccs_20.fit, se_fit=TRUE))

ccs_20.plot <- ccs_20.aug|>
    ggplot(aes(x=Tempo, y=CCS))+
    geom_line(size=1)+
    geom_line(aes(y=.fitted), size=1, col='#ff0000')+
    geom_ribbon(aes(ymin=(.fitted - 1.96 * .se.fit),
                    ymax=(.fitted + 1.96 * .se.fit)),
                alpha=0.25, fill='orange', col='#0080ff')+
    scale_x_date(date_breaks='1 month', date_labels='%m/%y')+
    scale_y_continuous(breaks=seq(180, 480, length.out=5))+
    labs(title='CCS_20')+
    theme_fivethirtyeight(base_size=16)

ccs_sup.plot / ccs_20.plot

```

```{r ccs_fit-tables}

ccs_sup.ftable <- broom::tidy(ccs_sup.fit, conf.int=TRUE)

ccs_sup.colcol <- ccs_sup.ftable|>
    dplyr::summarize(
               red=ifelse(p.value > 0.05, 0, 1),
               yellow=ifelse(p.value > 0.05 & p.value < 0.10, 1, 0))

ccs_sup.ftable|>
    kableExtra::kbl(digits=3, booktabs=TRUE)|>
    kableExtra::kable_classic_2(fixed_thead=TRUE)|>
    kableExtra::column_spec(5, bold=TRUE)|>
    kableExtra::row_spec(which(ccs_sup.colcol$red == 1), bold=TRUE, 
                         color='white', background='#D7261E')|>
    kableExtra::row_spec(which(ccs_sup.colcol$yellow == 1), bold=TRUE, 
                         background=i4p_colors['yellow'])

ccs_20.ftable <- broom::tidy(ccs_20.fit, conf.int=TRUE)

ccs_20.colcol <- ccs_20.ftable|>
    dplyr::summarize(
               red=ifelse(p.value > 0.05, 0, 1),
               yellow=ifelse(p.value > 0.05 & p.value < 0.10, 1, 0))

ccs_20.ftable|>
    kableExtra::kbl(digits=3, booktabs=TRUE)|>
    kableExtra::kable_classic_2(fixed_thead=TRUE)|>
    kableExtra::column_spec(5, bold=TRUE)|>
    kableExtra::row_spec(which(ccs_20.colcol$red == 1), bold=TRUE, 
                         color='white', background='#D7261E')|>
    kableExtra::row_spec(which(ccs_20.colcol$yellow == 1), bold=TRUE, 
                         background=i4p_colors['yellow'])

```
