---
title: "Cleber Machado, genética-dosagem 250521"
author: "Análise: [Henrique Laureano](https://henriquelaureano.github.io/)"
date: "*Last modification on* `r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r, echo=FALSE}
library(knitr)
options(width=100)
knitr::opts_chunk$set(fig.path='figuras/',
                      fig.align='center',
                      ## dev=c('pdf', 'png'),
                      warning=FALSE,
                      message=FALSE, 
                      prompt=FALSE,
                      comment=NA)
```

***

```{r pkgs}
pacman::p_load(
            ## data manipulation
            readxl,
            dplyr,
            lubridate,
            tidyr,
            haven,
            stringr,
            ## data analysis
            ## data visualization
            ggplot2,
            ggthemes,
            patchwork
        )
```

```{r data}
dat <- readxl::read_xls("RESULTS_GENETICA-DOSAGEM_250521.xls",
                        sheet='Genetica e Dosagem',
                        col_types=c(rep('numeric', 6), 'skip',
                                    rep('numeric', 2), 'skip', 
                                    rep('numeric', 13), 'skip', 
                                    rep('numeric',  5)))
dat <- dat|>
    dplyr::rename(diasI='Dias de internamento',
                  diasI12='Id1_Dias internamento (<12=0)', 
                  diasI8='Id2_Dias de internamento (<8=0)',
                  obito='Id3_Óbito (0=não)',
                  diasS7='Id4_Dias_antes_sint (<7=0)',
                  il6='IL-6 (pg/mL)', 
                  infg='INF-g (pg/mL)')|>
    dplyr::mutate(dplyr::across(!dplyr::starts_with('i'), factor))
```

## Análise descritiva

***

### Aspectos clínicos

```{r dias_de_internamento,fig.height=7.5}
diasS7_0 <- paste(
    '7 ou menos dias de', 'sintomas antes do internamento', sep='\n'
)
diasS7_1 <- paste(
    'Mais de 7 dias de', 'sintomas antes do internamento', sep='\n'
)
dat1 <- dat|>
    dplyr::mutate(
               Óbito=dplyr::recode(obito, '0'='Não', '1'='Sim'),
               diasS7=dplyr::recode(diasS7, '0'=diasS7_0, '1'=diasS7_1)
           )
dat1|>
    ggplot(aes(y=diasI, fill=Óbito))+
    geom_bar(alpha=0.7)+
    facet_wrap(~diasS7)+
    geom_text(stat='count',
              aes(label=sprintf('%s (%.1f%%)',
                                after_stat(count),
                                after_stat(100*count/sum(count))
                                )),
              position=position_stack(0.5))+
    labs(x='Frequência', title='Dias de internamento')+
    theme_fivethirtyeight(base_size=14)+
    theme(axis.title.x=element_text(
              margin=unit(c(t=3, r=0, b=0, l=0), "mm")
          ))+
    scale_fill_fivethirtyeight()
```

```{r dias_de_internamento_dicotomico,fig.width=10,fig.height=6}
bar_dias8 <- dat1|>
    ggplot(aes(y=diasI8, fill=Óbito))+
    geom_bar(alpha=0.75)+
    facet_wrap(~diasS7)+
    geom_text(stat='count',
              aes(label=sprintf('%s (%.1f%%)',
                                after_stat(count), 
                                after_stat(100*count/sum(count))
                                )),
              position=position_stack(0.5))+
    labs(x='Frequência', title='8 ou menos dias de internamento')+
    theme_fivethirtyeight(base_size=14)+
    theme(legend.position='none',
          axis.title.x=element_text(
              margin=unit(c(t=3, r=0, b=0, l=0), "mm")
          ))+
    scale_fill_fivethirtyeight()
bar_dias12 <- dat1|>
    ggplot(aes(y=diasI12, fill=Óbito))+
    geom_bar(alpha=0.75)+
    facet_wrap(~diasS7)+
    geom_text(stat='count',
              aes(label=sprintf('%s (%.1f%%)',
                                after_stat(count), 
                                after_stat(100*count/sum(count))
                                )),
              position=position_stack(0.5))+
    labs(x='Frequência', title='12 ou menos dias de internamento')+
    theme_fivethirtyeight(base_size=14)+
    theme(axis.title.x=element_text(
              margin=unit(c(t=3, r=0, b=0, l=0), "mm")
          ))+
    scale_fill_fivethirtyeight()
bar_dias8/bar_dias12
```

### Dosagens

```{r dosagens,fig.height=7.5}
box_il6 <- dat1|>
    ggplot(aes(x=il6, y=Óbito))+
    geom_boxplot(outlier.shape=NA)+
    geom_jitter(alpha=0.5)+
    stat_summary(fun=mean, geom='point', size=3, color='red')+
    labs(title='IL-6 (pg/mL)')+
    theme_fivethirtyeight(base_size=13)+
    theme(axis.title.y=element_text(
              angle=0,
              vjust=0.5, 
              margin=unit(c(t=0, r=3, b=0, l=0), "mm")
          ))
box_infg <- dat1|>
    ggplot(aes(x=infg, y=Óbito))+
    geom_boxplot(outlier.shape=NA)+
    geom_jitter(alpha=0.5)+
    stat_summary(fun=mean, geom='point', size=3, color='red')+
    labs(title='INF-g (pg/mL)')+
    theme_fivethirtyeight(base_size=13)+
    theme(axis.title.y=element_text(
              angle=0,
              vjust=0.5, 
              margin=unit(c(t=0, r=3, b=0, l=0), "mm")
          ))
point_lm <- dat|>
    ggplot(aes(x=il6, y=infg))+
    geom_point(size=2)+
    geom_smooth(method='lm', size=1.5)+
    labs(title='Dosagens de IL-6 vs. INF-g')+
    theme_fivethirtyeight(base_size=13)
(box_il6/box_infg/point_lm)+patchwork::plot_layout(heights=c(1, 1, 3))
```

## Modelagem da genética
