## simulating data, my way

```{r echo=FALSE}
library(knitr)
opts_chunk$set(fig.path = "figures/")
```

```{r}
pacman::p_load(mvtnorm, ## rmvnorm()
               mc2d, ## rmultinomial()
               tidyverse,
               patchwork)
## why not library()?
## with p_load(), if the package isn't installed,
## install_packages() is automatically loaded
```

```{r datasimucif, fig.height=3.75}
cif <- function() {
    t <- seq(30, 79.5, by = 0.5)
    delta <- 80
    u <- c(0, 0)
    eta <- c(0, 0)
    beta <- c(-2, -1.5)
    gamma <- c(1.2, 1)
    w <- c(3, 5)
    risk1 <- exp(beta[1] + u[1])
    risk2 <- exp(beta[2] + u[2])
    level <- 1 +  risk1 + risk2
    risklevel1 <- risk1/level
    risklevel2 <- risk2/level
    traj1 <- pnorm(w[1] * atanh(2 * t/delta - 1) - gamma[1] - eta[1])
    traj2 <- pnorm(w[2] * atanh(2 * t/delta - 1) - gamma[2] - eta[2])
    cif1 <- risklevel1 * traj1
    cif2 <- risklevel2 * traj2
    out <- as.data.frame(cbind(t, cif1, cif2))
    out <- out %>% pivot_longer(cols = cif1:cif2,
                                names_to = "cif", values_to = "value")
    return(out)
}
dfcif <- cif()
dcif <- function() {
    t <- seq(30, 79.5, by = 0.5)
    delta <- 80
    u <- c(0, 0)
    eta <- c(0, 0)
    beta <- c(-2, -1.5)
    gamma <- c(1.2, 1)
    w <- c(3, 5)
    risk1 <- exp(beta[1] + u[1])
    risk2 <- exp(beta[2] + u[2])
    level <- 1 +  risk1 + risk2
    risklevel1 <- risk1/level
    risklevel2 <- risk2/level
    dtraj1 <- w[1] * delta/(2 * t * (delta - t)) *
        dnorm(w[1] * atanh(2 * t/delta - 1) - gamma[1] - eta[1])
    dtraj2 <- w[2] * delta/(2 * t * (delta - t)) *
        dnorm(w[2] * atanh(2 * t/delta - 1) - gamma[2] - eta[2])
    dcif1 <- risklevel1 * dtraj1
    dcif2 <- risklevel2 * dtraj2
    out <- as.data.frame(cbind(t, dcif1, dcif2))
    out <- out %>% pivot_longer(cols = dcif1:dcif2,
                                names_to = "dcif", values_to = "value")
    return(out)
}
dfdcif <- dcif()
p1 <- ggplot(dfcif, aes(t, value, group = cif)) +
    geom_line(aes(linetype = cif)) +
    labs(x = "Time", y = NULL) +
    scale_linetype_discrete(labels = c("CIF 1", "CIF 2")) +
    theme_minimal()+
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          legend.text = element_text(size = 14),
          axis.text.x = element_text(size = 13),
          axis.text.y = element_text(size = 13),
          axis.title.x = element_text(
              size = 14,
              margin = unit(c(t = 3, r = 0, b = 0, l = 0), "mm")))
p2 <- ggplot(dfdcif, aes(t, value, group = dcif)) +
    geom_line(aes(linetype = dcif)) +
    labs(x = "Time", y = NULL) +
    scale_linetype_discrete(labels = c("dCIF 1", "dCIF 2")) +
    theme_minimal()+
    theme(legend.position = "bottom",
          legend.title = element_blank(),
          legend.text = element_text(size = 14),
          axis.text.x = element_text(size = 13),
          axis.text.y = element_text(size = 13),
          axis.title.x = element_text(
              size = 14,
              margin = unit(c(t = 3, r = 0, b = 0, l = 0), "mm")))
p1+p2
```

```{r datasimu_cache,cache=TRUE}
library(mvtnorm)
library(tidyverse)
library(mc2d)

datasimu <- function(J,    ## number of clusters
                     cs,   ## clusters size (all the same size)  
                     time, ## failure, censorship times
                     Z,    ## latent effects design-matrix
                     S,    ## variance-covariance matrix
                     delta=80,
                     beta =c( beta1=-2.0,  beta2=-1.5),
                     gamma=c(gamma1= 1.2, gamma2= 1.0),
                     w    =c(    w1= 3.0,     w2= 5.0),
                     seed1,
                     seed2)
{
    out <- tibble::tibble(i=rep(seq(cs), times=J), ## cluster element
                          j=rep(seq(J),  each=cs), ## cluster
                          time=time,
                          p1=NA,
                          p2=NA,
                          p3=NA)

    K     <- dim(S)[1]/2 + 1
    ladim <- 2*(K-1) ## latent effects dimension
    set.seed(seed1)
    U     <- mvtnorm::rmvnorm(J, mean=rep(0, ladim), sigma=S)
    ZU    <- Z%*%U
    risk1 <- exp(beta['beta1'] + ZU[, 1])
    risk2 <- exp(beta['beta2'] + ZU[, 2])
    level <- 1 + risk1 + risk2
    gt    <- atanh(2*time/delta - 1)
    dgt   <- delta/(2*time*(delta - time))
    x1    <- w['w1']*gt - gamma['gamma1'] - ZU[, 3]
    x2    <- w['w2']*gt - gamma['gamma2'] - ZU[, 4]
    
    out$p1 <- risk1/level*w['w1']*dgt*dnorm(x1)
    out$p2 <- risk2/level*w['w2']*dgt*dnorm(x2)

    out    <- out %>% dplyr::mutate(p3=1-p1-p2)
    set.seed(seed2)
    y      <- mc2d::rmultinomial(cs*J, 1, prob=out%>%select(p1:p3))

    out    <- out %>%
        dplyr::bind_cols(tibble::as_tibble(y)) %>%
        dplyr::rename(y1=V1, y2=V2, y3=V3)
    return(out)
}
J    <- 50e3
cs   <- 2
time <- runif(n=cs*J, min=30, max=79.9)
Z    <- Matrix::bdiag(replicate(J, rep(1, cs), simplify=FALSE))
S    <- matrix(c( 1.0,  0.4, -0.1,  0.4,
                  0.4,  1.0,  0.4, -0.1,
                 -0.1,  0.4,  1.0,  0.4,
                  0.4, -0.1,  0.4,  1.0), 4)
dat  <- datasimu(J=J, cs=cs, time=time, Z=Z, S=S, seed1=1, seed2=2)
```

```{r datasimu,fig.width=7.5,fig.height=6}
dat_longp <- dat%>%
    pivot_longer(cols=p1:p3, names_to='p_label', values_to='p_value')%>%
    mutate(p_label=forcats::fct_recode(p_label,
                                       'Cause 1'='p1',
                                       'Cause 2'='p2',
                                       'Censorship'='p3'))
dat_longy <- dat%>%
    pivot_longer(cols=y1:y3, names_to='y_label', values_to='y_value')%>%
    filter(y_value==1)

p1 <- ggplot(dat_longp, aes(x=p_value))+
    geom_histogram(binwidth=0.0025, color='black', fill='white')+
    facet_wrap(~p_label, scales='free')+
    labs(x='Probability', caption='bindwidth=0.0025')+
    geom_label(data=data.frame(
                   label=paste0(
                       "Turns out in\n",
                       round(prop.table(table(dat_longy$y_label)), 3),
                       "%'s of data"),
                   p_label=levels(dat_longp$p_label)),
               mapping=aes(x=c(0.045, 0.0325, 0.955),
                           y=Inf, label=label),
               vjust=1.5)+
    theme_minimal()+
    theme(strip.background=element_rect(colour='black', fill='white'),
          strip.text.x=element_text(size=12), 
          axis.text.x=element_text(size=11),
          axis.text.y=element_blank(),
          axis.title.y=element_blank(),
          axis.title.x=element_text(
              size=12, 
              margin=unit(c(t=3, r=0, b=0, l=0), 'mm')),
          plot.caption=element_text(size=11))

dat_nocens <- dat_longy %>% filter(y_label != 'y3') %>%
    mutate(y_label=forcats::fct_recode(y_label,
                                       '210 failures by cause 1'='y1',
                                       '355 failures by cause 2'='y2'))
## table(dat_nocens$y_label)

p2 <- ggplot(dat_nocens, aes(x=time))+
    geom_histogram(binwidth=2.5, color='black', fill='white')+
    facet_wrap(~y_label, scales='free')+
    labs(x='Time', caption='bindwidth=2.5')+
    theme_minimal()+
    theme(strip.background=element_rect(colour='black', fill='white'),
          strip.text.x=element_text(size=12), 
          axis.text.x=element_text(size=11),
          axis.text.y=element_text(size=11),
          axis.title.y=element_blank(),
          axis.title.x=element_text(
              size=12, 
              margin=unit(c(t=3, r=0, b=0, l=0), 'mm')),
          plot.caption=element_text(size=11))

layout <- '
AAAAAA
#BBBB#
'
p1+p2+plot_layout(design=layout)
```

```{r twodiffcifs, fig.height=3.75}
cif <- function(time, delta=80, beta, gama, w)
{
    risk1 <- exp(beta[1])
    risk2 <- exp(beta[2])

    level <- 1 + risk1 + risk2

    gt <- 0.5*log(time/(delta-time))

    x1 <- w[1]*gt - gama[1]
    x2 <- w[2]*gt - gama[2]
    
    cif1 <- risk1/level * pnorm(x1)
    cif2 <- risk2/level * pnorm(x2)

    label.cif1 <- paste0(
        'CIF1: beta1=', beta[1], ', gama1=', gama[1], ', w1=', w[1]
    )
    label.cif2 <- paste0(
        'CIF2: beta2=', beta[2], ', gama2=', gama[2], ', w2=', w[2]
    )
    n <- length(time)

    dat <- tibble::tibble(time =rep(time, 2),
                          cif  =c(cif1, cif2),
                          label=c(rep(label.cif1, n),
                                  rep(label.cif2, n)))

    dgt <- delta/(2*time*(delta-time))
    
    p1 <- risk1/level * w[1]*dgt * dnorm(x1)
    p2 <- risk2/level * w[2]*dgt * dnorm(x2)

    p3 <- 1 - p1 - p2

    y <- mc2d::rmultinomial(n, 1, prob=cbind(p1, p2, p3))

    censorship <- prop.table(colSums(y))[3]

    return(list(dat=dat, censorship=censorship))
}

plotcif <- function(cif.obj)
{
    ggplot(data=cif.obj$dat, aes(x=time, y=cif, linetype=label))+
        geom_line()+
        labs(x=NULL, y=NULL, color=NULL,
             title=paste('Censorship %:', cif.obj$censorship))+
        theme_minimal()+
        theme(legend.position='bottom',
              legend.box.background=element_rect(color='black'), 
              legend.title=element_blank(),
              legend.text=element_text(size=12),
              axis.text.x=element_text(size=12),
              axis.text.y=element_text(size=12),
              plot.title=element_text(size=13, face='bold'))+
        guides(linetype=guide_legend(nrow=2))
}
time <- seq(from=30, to=79.9, length.out=100)

beta <- c(-2.0, -1.5)
gama <- c( 1.0,  1.5)
w    <- c( 3.0,  4.0)
set.seed(1442)
dat1 <- cif(time=time, beta=beta, gama=gama, w=w)

beta <- c(3.0,  2.6)
gama <- c(2.5,  4.0)
w    <- c(5.0, 10.0)
set.seed(1487)
dat2 <- cif(time=time, beta=beta, gama=gama, w=w)

pc1 <- plotcif(dat1)
pc2 <- plotcif(dat2)
pc1|pc2
```
