---
title: "Multinomial model: average income plot"
bibliography: /home/laureano/Git/consu/references.bib
format:
  html:
    toc: true
    toc-fold: true
    echo: false
    code-line-numbers: true
---

> Leidimari Neves do Prado and
> [Henrique Laureano](https://henriquelaureano.github.io/)

*Last modification on* `r Sys.time()`

***

```{r}
#| label: pkgs

## setwd('leidiprado/')

if(!requireNamespace('pacman', quietly=TRUE)) install.packages('pacman')

pacman::p_load(quarto, tidyr, dplyr, ggplot2, patchwork)

```

```{r}
#| label: average-income
#| fig-width: 10
#| fig-height: 9

res    <- read.csv('res_summary_model.csv', header=TRUE, sep=' ')
final1 <- read.csv('final1.csv',            header=TRUE, sep=' ')

plotObj <- function(i1, i2, i3, start, end)
{
    mgrid  <- seq(start, end, length.out=40)
    n1.est <- exp(res[ 1, 2]              + mgrid *  res[i1, 2]              )
    n1.low <- exp(res[ 1, 2] - res[ 1, 3] + mgrid * (res[i1, 2] - res[i1, 3]))
    n1.upp <- exp(res[ 1, 2] + res[ 1, 3] + mgrid * (res[i1, 2] + res[i1, 3]))
    n2.est <- exp(res[21, 2]              + mgrid *  res[i2, 2]              )
    n2.low <- exp(res[21, 2] - res[21, 3] + mgrid * (res[i2, 2] - res[i2, 3]))
    n2.upp <- exp(res[21, 2] + res[21, 3] + mgrid * (res[i2, 2] + res[i2, 3]))
    n3.est <- exp(res[41, 2]              + mgrid *  res[i3, 2]              )
    n3.low <- exp(res[41, 2] - res[41, 3] + mgrid * (res[i3, 2] - res[i3, 3]))
    n3.upp <- exp(res[41, 2] + res[41, 3] + mgrid * (res[i3, 2] + res[i3, 3]))
    denom.est <- 1 + rowSums(cbind(n1.est, n2.est, n3.est))
    denom.low <- 1 + rowSums(cbind(n1.low, n2.low, n3.low))
    denom.upp <- 1 + rowSums(cbind(n1.upp, n2.upp, n3.upp))
    dat.est   <-
        tibble::tibble(x   =mgrid,
                       L0S0=n1.est/denom.est,
                       L1S0=n2.est/denom.est,
                       L0S1=n3.est/denom.est,
                       L1S1=     1/denom.est)|>
        tidyr::pivot_longer(L0S0:L1S1,
                            names_to='p', values_to='value.est')
    dat.low   <-
        tibble::tibble(L0S0=n1.low/denom.low,
                       L1S0=n2.low/denom.low,
                       L0S1=n3.low/denom.low,
                       L1S1=     1/denom.low)|>
        tidyr::pivot_longer(L0S0:L1S1,
                            names_to='p', values_to='value.low')|>
        dplyr::select(value.low)
    dat.upp   <-
        tibble::tibble(L0S0=n1.upp/denom.upp,
                       L1S0=n2.upp/denom.upp,
                       L0S1=n3.upp/denom.upp,
                       L1S1=     1/denom.upp)|>
        tidyr::pivot_longer(L0S0:L1S1,
                            names_to='p', values_to='value.upp')|>
        dplyr::select(value.upp)
    out <- dplyr::bind_cols(dat.est, dat.low, dat.upp)
    return(out)
}
dat <- plotObj(i1=2, i2=22, i3=42,
               start=min(final1$average.income_),
               end  =max(final1$average.income_))

p1 <- dat|>
    ggplot(aes(x, value.est, color=p))+
    geom_line(size=1.25)+
    geom_ribbon(aes(ymin=value.low, ymax=value.upp),
                alpha=0.2, linetype='dashed')+
    scale_x_continuous(breaks=seq(2500, 25e3, by=5e3))+
    scale_y_continuous(breaks=seq(0, 1, by=0.1))+
    scale_color_brewer(palette='Spectral')+
    labs(x='Average income', y='Probability',
         title='Probabilities vs.\nAverage income')+
    theme_minimal(base_size=15)+
    theme(axis.title.x=element_text(
              face='bold',
              margin=ggplot2::unit(c(t=3, l=0, b=0, r=0), 'mm')),
          axis.title.y=element_text(
              face='bold',
              margin=ggplot2::unit(c(t=0, l=3, b=0, r=0), 'mm')),
          legend.position='none',
          plot.title     =element_text(face='bold'))

p2 <- dat|>
    ggplot(aes(x, value.est, color=p))+
    geom_line(size=1.25)+
    scale_x_continuous(breaks=seq(2500, 25e3, by=5e3))+
    scale_y_continuous(breaks=seq(0, 1, by=0.1))+
    scale_color_brewer(palette='Spectral')+
    labs(x='Average income', y='Probability')+
    theme_minimal(base_size=15)+
    theme(axis.title.x=element_text(
              face='bold',
              margin=ggplot2::unit(c(t=3, l=0, b=0, r=0), 'mm')),
          axis.title.y=element_text(
              face='bold',
              margin=ggplot2::unit(c(t=0, l=3, b=0, r=0), 'mm')),
          legend.position='none',
          plot.title     =element_text(face='bold'))

p3 <- dat|>
    ggplot(aes(x, value.est, color=p))+
    geom_line(size=1.25)+
    geom_ribbon(aes(ymin=value.low, ymax=value.upp),
                alpha=0.2, linetype='dashed')+
    facet_grid(~ p)+
    scale_x_continuous(breaks=c(2500, 7500, 12500, 2e4))+
    scale_y_continuous(breaks=seq(0, 1, by=0.1))+
    scale_color_brewer(palette='Spectral')+
    labs(x='Average income', y='Probability')+
    theme_minimal(base_size=15)+
    theme(axis.title.x=element_text(
              face='bold',
              margin=ggplot2::unit(c(t=3, l=0, b=-3, r=0), 'mm')),
          axis.title.y=element_text(
              face='bold',
              margin=ggplot2::unit(c(t=0, l=3, b=0, r=0), 'mm')),
          legend.position ='bottom',
          plot.title      =element_text(face='bold'),
          strip.text.x    =element_text(face='bold', size=15),
          strip.background=element_rect(color='black'))+
    guides(color=guide_legend(title='Class:', keywidth=2))

layout <- '
AB
CC
'
p1 + p2 + p3 +
    patchwork::plot_layout(design=layout)

```

***

> R [@R22].

::: {#refs}
:::
