<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.25">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Henrique Laureano">

<title>ELPT</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="respostas_elpt_files/libs/clipboard/clipboard.min.js"></script>
<script src="respostas_elpt_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="respostas_elpt_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="respostas_elpt_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="respostas_elpt_files/libs/quarto-html/popper.min.js"></script>
<script src="respostas_elpt_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="respostas_elpt_files/libs/quarto-html/anchor.min.js"></script>
<link href="respostas_elpt_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="respostas_elpt_files/libs/quarto-html/quarto-syntax-highlighting-7b89279ff1a6dce999919e0e67d4d9ec.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="respostas_elpt_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="respostas_elpt_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="respostas_elpt_files/libs/bootstrap/bootstrap-ec567951c972cfd6b8f0c9672dede165.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body class="quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#análise-epidemiológica" id="toc-análise-epidemiológica" class="nav-link active" data-scroll-target="#análise-epidemiológica">1. Análise epidemiológica</a>
  <ul class="collapse">
  <li><a href="#a-porcentagem-de-cada-faixa-etária-na-amostra" id="toc-a-porcentagem-de-cada-faixa-etária-na-amostra" class="nav-link" data-scroll-target="#a-porcentagem-de-cada-faixa-etária-na-amostra">a) Porcentagem de cada faixa etária na amostra</a></li>
  <li><a href="#b-setores-mais-representativos-na-amostra" id="toc-b-setores-mais-representativos-na-amostra" class="nav-link" data-scroll-target="#b-setores-mais-representativos-na-amostra">b) Setores mais representativos na amostra</a></li>
  <li><a href="#c-sexo" id="toc-c-sexo" class="nav-link" data-scroll-target="#c-sexo">c) Sexo</a></li>
  <li><a href="#d-presençaausência-de-quadros-infecciosos-e-sistema-mais-afetado-em-casos-positivos-para-quadros-infecciosos" id="toc-d-presençaausência-de-quadros-infecciosos-e-sistema-mais-afetado-em-casos-positivos-para-quadros-infecciosos" class="nav-link" data-scroll-target="#d-presençaausência-de-quadros-infecciosos-e-sistema-mais-afetado-em-casos-positivos-para-quadros-infecciosos">d) Presença/ausência de quadros infecciosos e sistema mais afetado em casos positivos para quadros infecciosos</a></li>
  <li><a href="#e-porcentagem-de-indivíduos-com-comorbidade-e-comorbidades-mais-frequentes" id="toc-e-porcentagem-de-indivíduos-com-comorbidade-e-comorbidades-mais-frequentes" class="nav-link" data-scroll-target="#e-porcentagem-de-indivíduos-com-comorbidade-e-comorbidades-mais-frequentes">e) Porcentagem de indivíduos com comorbidade e comorbidades mais frequentes</a></li>
  <li><a href="#f-porcentagem-de-pacientes-que-realizam-hemodiálise" id="toc-f-porcentagem-de-pacientes-que-realizam-hemodiálise" class="nav-link" data-scroll-target="#f-porcentagem-de-pacientes-que-realizam-hemodiálise">f) Porcentagem de pacientes que realizam hemodiálise</a></li>
  <li><a href="#g-porcentagem-de-pacientes-que-passaram-por-cirurgia-nos-30-dias-antes-do-exame" id="toc-g-porcentagem-de-pacientes-que-passaram-por-cirurgia-nos-30-dias-antes-do-exame" class="nav-link" data-scroll-target="#g-porcentagem-de-pacientes-que-passaram-por-cirurgia-nos-30-dias-antes-do-exame">g) Porcentagem de pacientes que passaram por cirurgia nos 30 dias antes do exame</a></li>
  <li><a href="#h-porcentagem-de-pacientes-que-passaram-por-tratamento-oncológico-nos-30-antes-do-exame" id="toc-h-porcentagem-de-pacientes-que-passaram-por-tratamento-oncológico-nos-30-antes-do-exame" class="nav-link" data-scroll-target="#h-porcentagem-de-pacientes-que-passaram-por-tratamento-oncológico-nos-30-antes-do-exame">h) Porcentagem de pacientes que passaram por tratamento oncológico nos 30 antes do exame</a></li>
  <li><a href="#i-porcentagem-de-pacientes-que-fizeram-uso-de-medicação" id="toc-i-porcentagem-de-pacientes-que-fizeram-uso-de-medicação" class="nav-link" data-scroll-target="#i-porcentagem-de-pacientes-que-fizeram-uso-de-medicação">i) Porcentagem de pacientes que fizeram uso de medicação</a></li>
  <li><a href="#j-porcentagem-de-pacientes-com-registro-de-óbito.-definir-intervalo-de-tempo-entre-a-data-do-exame-e-a-data-do-óbito." id="toc-j-porcentagem-de-pacientes-com-registro-de-óbito.-definir-intervalo-de-tempo-entre-a-data-do-exame-e-a-data-do-óbito." class="nav-link" data-scroll-target="#j-porcentagem-de-pacientes-com-registro-de-óbito.-definir-intervalo-de-tempo-entre-a-data-do-exame-e-a-data-do-óbito.">j) Porcentagem de pacientes com registro de óbito. Definir intervalo de tempo entre a data do exame e a data do óbito.</a></li>
  </ul></li>
  <li><a href="#análise-de-indivíduos-com-dosagem-de-igg" id="toc-análise-de-indivíduos-com-dosagem-de-igg" class="nav-link" data-scroll-target="#análise-de-indivíduos-com-dosagem-de-igg">2. Análise de indivíduos com dosagem de IgG</a>
  <ul class="collapse">
  <li><a href="#a-a-partir-dos-valores-de-dosagem-de-igg-verificar-se-existe-correlação-com-os-valores-de-elpt-não-considerar-na-estatistica-os-pacientes-que-fazem-reposição-de-igg---pois-é-um-tratamento-logo-não-é-um-dado-basal" id="toc-a-a-partir-dos-valores-de-dosagem-de-igg-verificar-se-existe-correlação-com-os-valores-de-elpt-não-considerar-na-estatistica-os-pacientes-que-fazem-reposição-de-igg---pois-é-um-tratamento-logo-não-é-um-dado-basal" class="nav-link" data-scroll-target="#a-a-partir-dos-valores-de-dosagem-de-igg-verificar-se-existe-correlação-com-os-valores-de-elpt-não-considerar-na-estatistica-os-pacientes-que-fazem-reposição-de-igg---pois-é-um-tratamento-logo-não-é-um-dado-basal">a) A partir dos valores de dosagem de IgG, verificar se existe correlação com os valores de ELPT; Não considerar na estatistica os pacientes que fazem reposição de IgG - pois é um tratamento, logo não é um dado basal</a></li>
  <li><a href="#b-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt" id="toc-b-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt" class="nav-link" data-scroll-target="#b-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt">b) Entre os indivíduos com dosagem de IgG abaixo do valor de referência, qual foi o valor médio, mínimo e máximo do valor de ELPT?</a></li>
  <li><a href="#c-entre-os-indivíduos-com-dosagem-de-igg-acima-do-valor-de-referência-e-que-não-fazem-reposição-de-igg-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt" id="toc-c-entre-os-indivíduos-com-dosagem-de-igg-acima-do-valor-de-referência-e-que-não-fazem-reposição-de-igg-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt" class="nav-link" data-scroll-target="#c-entre-os-indivíduos-com-dosagem-de-igg-acima-do-valor-de-referência-e-que-não-fazem-reposição-de-igg-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt">c) Entre os indivíduos com dosagem de IgG acima do valor de referência e que NÃO fazem reposição de IgG, qual foi o valor médio, mínimo e máximo do valor de ELPT?</a></li>
  <li><a href="#d-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-quantos-possuíam-comorbidade-quais-eram-mais-frequentes" id="toc-d-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-quantos-possuíam-comorbidade-quais-eram-mais-frequentes" class="nav-link" data-scroll-target="#d-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-quantos-possuíam-comorbidade-quais-eram-mais-frequentes">d) Entre os indivíduos com dosagem de IgG abaixo do valor de referência, quantos possuíam comorbidade? Quais eram mais frequentes?</a></li>
  </ul></li>
  <li><a href="#análise-dos-menores-de-1-ano" id="toc-análise-dos-menores-de-1-ano" class="nav-link" data-scroll-target="#análise-dos-menores-de-1-ano">3. Análise dos menores de 1 ano</a>
  <ul class="collapse">
  <li><a href="#a-entre-os-menores-de-1-ano-quantos-apresentavam-a-comorbidade-prematuridade" id="toc-a-entre-os-menores-de-1-ano-quantos-apresentavam-a-comorbidade-prematuridade" class="nav-link" data-scroll-target="#a-entre-os-menores-de-1-ano-quantos-apresentavam-a-comorbidade-prematuridade">a) Entre os menores de 1 ano, quantos apresentavam a comorbidade “Prematuridade”?</a></li>
  <li><a href="#b-levando-em-consideração-pacientes-que-fizeram-os-exames-elpt-igg-definir-um-valor-de-referência-para-elpt-levando-como-referência-a-dosagem-de-igg" id="toc-b-levando-em-consideração-pacientes-que-fizeram-os-exames-elpt-igg-definir-um-valor-de-referência-para-elpt-levando-como-referência-a-dosagem-de-igg" class="nav-link" data-scroll-target="#b-levando-em-consideração-pacientes-que-fizeram-os-exames-elpt-igg-definir-um-valor-de-referência-para-elpt-levando-como-referência-a-dosagem-de-igg">b) Levando em consideração pacientes que fizeram os exames ELPT + IgG, definir um valor de referência para ELPT levando como referência a dosagem de IgG</a></li>
  <li><a href="#explicação-mais-detalhada" id="toc-explicação-mais-detalhada" class="nav-link" data-scroll-target="#explicação-mais-detalhada">Explicação mais detalhada</a>
  <ul class="collapse">
  <li><a href="#establishment-of-the-baseline-reference" id="toc-establishment-of-the-baseline-reference" class="nav-link" data-scroll-target="#establishment-of-the-baseline-reference">1. Establishment of the Baseline Reference</a></li>
  <li><a href="#group-dynamics-the-rise-vs.-attenuation-effect" id="toc-group-dynamics-the-rise-vs.-attenuation-effect" class="nav-link" data-scroll-target="#group-dynamics-the-rise-vs.-attenuation-effect">2. Group Dynamics: The “Rise vs.&nbsp;Attenuation” Effect</a></li>
  <li><a href="#segmented-regression-inflection-point" id="toc-segmented-regression-inflection-point" class="nav-link" data-scroll-target="#segmented-regression-inflection-point">3. Segmented Regression (Inflection Point)</a></li>
  <li><a href="#summary-of-statistical-findings" id="toc-summary-of-statistical-findings" class="nav-link" data-scroll-target="#summary-of-statistical-findings">Summary of Statistical Findings</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#how-to-use-elpt-to-predict-igg-deficiency" id="toc-how-to-use-elpt-to-predict-igg-deficiency" class="nav-link" data-scroll-target="#how-to-use-elpt-to-predict-igg-deficiency">How to use ELPT to predict IgG deficiency</a>
  <ul class="collapse">
  <li><a href="#diagnostic-screening-elpt-as-a-predictor-for-igg-testing" id="toc-diagnostic-screening-elpt-as-a-predictor-for-igg-testing" class="nav-link" data-scroll-target="#diagnostic-screening-elpt-as-a-predictor-for-igg-testing">Diagnostic Screening: ELPT as a Predictor for IgG Testing</a>
  <ul class="collapse">
  <li><a href="#analysis-of-cutoff-strategies" id="toc-analysis-of-cutoff-strategies" class="nav-link" data-scroll-target="#analysis-of-cutoff-strategies">Analysis of Cutoff Strategies</a></li>
  <li><a href="#conclusion-and-recommendation" id="toc-conclusion-and-recommendation" class="nav-link" data-scroll-target="#conclusion-and-recommendation">Conclusion and Recommendation</a></li>
  </ul></li>
  <li><a href="#advanced-strategy-the-indeterminate-zone-approach" id="toc-advanced-strategy-the-indeterminate-zone-approach" class="nav-link" data-scroll-target="#advanced-strategy-the-indeterminate-zone-approach">Advanced Strategy: The “Indeterminate Zone” Approach</a></li>
  <li><a href="#infections" id="toc-infections" class="nav-link" data-scroll-target="#infections">Infections</a>
  <ul class="collapse">
  <li><a href="#clinical-validation-association-with-infection-history-elpt" id="toc-clinical-validation-association-with-infection-history-elpt" class="nav-link" data-scroll-target="#clinical-validation-association-with-infection-history-elpt">Clinical Validation: Association with Infection History (ELPT)</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#methodology-references" id="toc-methodology-references" class="nav-link" data-scroll-target="#methodology-references">Methodology &amp; References</a>
  <ul class="collapse">
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references">References</a></li>
  </ul></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">ELPT</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Henrique Laureano </p>
          </div>
  </div>
    
  
    <div>
    <div class="quarto-title-meta-heading">Modified</div>
    <div class="quarto-title-meta-contents">
      <p class="date-modified">January 13, 2026</p>
    </div>
  </div>
    
  </div>
  


</header>


<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a><span class="cf">if</span> (<span class="sc">!</span><span class="fu">requireNamespace</span>(<span class="st">"pacman"</span>, <span class="at">quietly =</span> <span class="cn">TRUE</span>)) </span>
<span id="cb1-2"><a href="#cb1-2"></a>  <span class="fu">install.packages</span>(<span class="st">"pacman"</span>) </span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a>pacman<span class="sc">::</span><span class="fu">p_load</span>(</span>
<span id="cb1-5"><a href="#cb1-5"></a>  ggplot2, googlesheets4, </span>
<span id="cb1-6"><a href="#cb1-6"></a>  dplyr, lubridate, tidyr, stringr, ggpubr, segmented, broom, pROC, knitr, purrr</span>
<span id="cb1-7"><a href="#cb1-7"></a>)</span>
<span id="cb1-8"><a href="#cb1-8"></a>ggplot2<span class="sc">::</span><span class="fu">theme_set</span>(</span>
<span id="cb1-9"><a href="#cb1-9"></a>  <span class="fu">theme_classic</span>(<span class="at">base_size =</span> <span class="dv">14</span>) <span class="sc">+</span></span>
<span id="cb1-10"><a href="#cb1-10"></a>    <span class="fu">theme</span>(<span class="at">plot.title           =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">14</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb1-11"><a href="#cb1-11"></a>          <span class="at">plot.subtitle        =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb1-12"><a href="#cb1-12"></a>          <span class="at">axis.text.x          =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb1-13"><a href="#cb1-13"></a>          <span class="at">axis.text.y          =</span> <span class="fu">element_text</span>(<span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb1-14"><a href="#cb1-14"></a>          <span class="at">axis.title.x         =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>),</span>
<span id="cb1-15"><a href="#cb1-15"></a>          <span class="at">axis.title.y         =</span> <span class="fu">element_text</span>(<span class="at">hjust =</span> <span class="dv">0</span>, <span class="at">angle =</span> <span class="dv">360</span>),</span>
<span id="cb1-16"><a href="#cb1-16"></a>          <span class="at">strip.text           =</span> <span class="fu">element_text</span>(<span class="at">size =</span> <span class="dv">13</span>, <span class="at">face =</span> <span class="st">"bold"</span>),</span>
<span id="cb1-17"><a href="#cb1-17"></a>          <span class="at">legend.position      =</span> <span class="st">"bottom"</span>, </span>
<span id="cb1-18"><a href="#cb1-18"></a>          <span class="at">legend.justification =</span> <span class="st">"right"</span>,</span>
<span id="cb1-19"><a href="#cb1-19"></a>          <span class="at">panel.grid.major     =</span> <span class="fu">element_line</span>(<span class="at">color =</span> <span class="st">"gray90"</span>, <span class="at">linewidth =</span> <span class="fl">0.7</span>))</span>
<span id="cb1-20"><a href="#cb1-20"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1"></a>elpt_url <span class="ot">&lt;-</span> </span>
<span id="cb2-2"><a href="#cb2-2"></a>  <span class="fu">paste0</span>(</span>
<span id="cb2-3"><a href="#cb2-3"></a>    <span class="st">"https://docs.google.com/spreadsheets/d/"</span>,</span>
<span id="cb2-4"><a href="#cb2-4"></a>    <span class="st">"1FHy8nsW_WfEiWfWXdk7atQlaChNAkJIrAkuNxfOuECg/"</span>,</span>
<span id="cb2-5"><a href="#cb2-5"></a>    <span class="st">"edit?gid=1057715313#gid=1057715313"</span></span>
<span id="cb2-6"><a href="#cb2-6"></a>)</span>
<span id="cb2-7"><a href="#cb2-7"></a>elpt <span class="ot">&lt;-</span> googlesheets4<span class="sc">::</span><span class="fu">read_sheet</span>(elpt_url) <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">distinct</span>()</span>
<span id="cb2-8"><a href="#cb2-8"></a></span>
<span id="cb2-9"><a href="#cb2-9"></a>elpt <span class="ot">&lt;-</span> elpt <span class="sc">|&gt;</span> </span>
<span id="cb2-10"><a href="#cb2-10"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb2-11"><a href="#cb2-11"></a>    <span class="at">IDADE =</span> lubridate<span class="sc">::</span><span class="fu">time_length</span>(</span>
<span id="cb2-12"><a href="#cb2-12"></a>      lubridate<span class="sc">::</span><span class="fu">interval</span>(<span class="st">`</span><span class="at">6 - Data de Nascimento</span><span class="st">`</span>, </span>
<span id="cb2-13"><a href="#cb2-13"></a>                          <span class="st">`</span><span class="at">5 - Data de Cadastro do Exame</span><span class="st">`</span>), <span class="st">"years"</span></span>
<span id="cb2-14"><a href="#cb2-14"></a>    )</span>
<span id="cb2-15"><a href="#cb2-15"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
</div>
<section id="análise-epidemiológica" class="level1">
<h1>1. Análise epidemiológica</h1>
<section id="a-porcentagem-de-cada-faixa-etária-na-amostra" class="level2">
<h2 class="anchored" data-anchor-id="a-porcentagem-de-cada-faixa-etária-na-amostra">a) Porcentagem de cada faixa etária na amostra</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a>elpt <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">3 - Insira Faixa etária do paciente</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb3-2"><a href="#cb3-2"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 3
  `3 - Insira Faixa etária do paciente`     n Percentual
  &lt;chr&gt;                                 &lt;int&gt;      &lt;dbl&gt;
1 1 ano a 3 anos                           85    0.525  
2 10 anos a 17 anos                        43    0.265  
3 4 anos a 9 anos                          33    0.204  
4 &lt; 1 ano                                   1    0.00617</code></pre>
</div>
</div>
</section>
<section id="b-setores-mais-representativos-na-amostra" class="level2">
<h2 class="anchored" data-anchor-id="b-setores-mais-representativos-na-amostra">b) Setores mais representativos na amostra</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a>elpt <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">2 - Insira o Setor de Solicitação do exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt)) <span class="sc">|&gt;</span></span>
<span id="cb5-3"><a href="#cb5-3"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(dplyr<span class="sc">::</span><span class="fu">desc</span>(n)) <span class="sc">|&gt;</span> <span class="fu">print</span>(<span class="at">n =</span> <span class="dv">22</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 22 × 3
   `2 - Insira o Setor de Solicitação do exame`     n Percentual
   &lt;chr&gt;                                        &lt;int&gt;      &lt;dbl&gt;
 1 Laboratório de Analises Clinicas                80    0.494  
 2 Posto 52                                         9    0.0556 
 3 UTI Geral                                        8    0.0494 
 4 UTI Cirúrgica                                    7    0.0432 
 5 Emergência Convenio                              6    0.0370 
 6 Emergência SUS Interno                           6    0.0370 
 7 Posto 51                                         6    0.0370 
 8 Ambulatório Hemato-Oncologia                     4    0.0247 
 9 Infectologia                                     4    0.0247 
10 Posto 11 Nefrologia                              4    0.0247 
11 Posto 21                                         4    0.0247 
12 Posto 23                                         4    0.0247 
13 Emergência SUS                                   3    0.0185 
14 Posto 41                                         3    0.0185 
15 UTI Cardiologia                                  3    0.0185 
16 HD Posto 12                                      2    0.0123 
17 Posto 31                                         2    0.0123 
18 Posto 33                                         2    0.0123 
19 Posto 42                                         2    0.0123 
20 Posto 34                                         1    0.00617
21 Posto 43                                         1    0.00617
22 U.I 4º Andar - Posto 40                          1    0.00617</code></pre>
</div>
</div>
</section>
<section id="c-sexo" class="level2">
<h2 class="anchored" data-anchor-id="c-sexo">c) Sexo</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a>elpt <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">4 - Sexo</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb7-2"><a href="#cb7-2"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 3
  `4 - Sexo`     n Percentual
  &lt;chr&gt;      &lt;int&gt;      &lt;dbl&gt;
1 Feminino      63      0.389
2 Masculino     99      0.611</code></pre>
</div>
</div>
</section>
<section id="d-presençaausência-de-quadros-infecciosos-e-sistema-mais-afetado-em-casos-positivos-para-quadros-infecciosos" class="level2">
<h2 class="anchored" data-anchor-id="d-presençaausência-de-quadros-infecciosos-e-sistema-mais-afetado-em-casos-positivos-para-quadros-infecciosos">d) Presença/ausência de quadros infecciosos e sistema mais afetado em casos positivos para quadros infecciosos</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a>elpt <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">7 - Quadros infecciosos até o momento da coleta?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb9-2"><a href="#cb9-2"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  `7 - Quadros infecciosos até o momento da coleta?`     n Percentual
  &lt;chr&gt;                                              &lt;int&gt;      &lt;dbl&gt;
1 Não                                                   45      0.278
2 Sem informação                                        44      0.272
3 Sim                                                   73      0.451</code></pre>
</div>
</div>
<p>Em quem tem caso positivo para quadro infeccioso</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1"></a>elpt <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb11-2"><a href="#cb11-2"></a>  <span class="st">`</span><span class="at">7 - Quadros infecciosos até o momento da coleta?</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sim"</span></span>
<span id="cb11-3"><a href="#cb11-3"></a>) <span class="sc">|&gt;</span></span>
<span id="cb11-4"><a href="#cb11-4"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">`</span><span class="at">8 - Infecção em sistema nervoso central?</span><span class="st">`</span>,</span>
<span id="cb11-5"><a href="#cb11-5"></a>                <span class="st">`</span><span class="at">9 - Infecção de vias áreas superioras?</span><span class="st">`</span>,</span>
<span id="cb11-6"><a href="#cb11-6"></a>                <span class="st">`</span><span class="at">10 - Infecção de vias áreas inferiores?</span><span class="st">`</span>,</span>
<span id="cb11-7"><a href="#cb11-7"></a>                <span class="st">`</span><span class="at">11 - Infecção de sistema urinário?</span><span class="st">`</span>,</span>
<span id="cb11-8"><a href="#cb11-8"></a>                <span class="st">`</span><span class="at">12 - Infecção de sistema gastrointestinal?</span><span class="st">`</span>,</span>
<span id="cb11-9"><a href="#cb11-9"></a>                <span class="st">`</span><span class="at">13 - Infecção de pele?</span><span class="st">`</span>,</span>
<span id="cb11-10"><a href="#cb11-10"></a>                <span class="st">`</span><span class="at">14 - Sepse?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-11"><a href="#cb11-11"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="st">`</span><span class="at">8 - Infecção em sistema nervoso central?</span><span class="st">`</span><span class="sc">:</span><span class="st">`</span><span class="at">14 - Sepse?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-12"><a href="#cb11-12"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(value <span class="sc">==</span> <span class="st">"Sim"</span>) <span class="sc">|&gt;</span></span>
<span id="cb11-13"><a href="#cb11-13"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(name) <span class="sc">|&gt;</span></span>
<span id="cb11-14"><a href="#cb11-14"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">sum</span>(n)) <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">arrange</span>(dplyr<span class="sc">::</span><span class="fu">desc</span>(n))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  name                                           n Percentual
  &lt;chr&gt;                                      &lt;int&gt;      &lt;dbl&gt;
1 10 - Infecção de vias áreas inferiores?       24     0.255 
2 9 - Infecção de vias áreas superioras?        18     0.191 
3 14 - Sepse?                                   14     0.149 
4 11 - Infecção de sistema urinário?            13     0.138 
5 13 - Infecção de pele?                        10     0.106 
6 12 - Infecção de sistema gastrointestinal?     9     0.0957
7 8 - Infecção em sistema nervoso central?       6     0.0638</code></pre>
</div>
</div>
<p>Dos 73 pacientes com quadro infeccioso, 22 apresentaram em mais de um sistema (ao menos em dois). 30.14%.</p>
<p>Nestes 22, estes são os sintomas que aparecem e em quantos dos 22 pacientes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb13"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1"></a>proxy <span class="ot">&lt;-</span> </span>
<span id="cb13-2"><a href="#cb13-2"></a>  elpt <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb13-3"><a href="#cb13-3"></a>    <span class="st">`</span><span class="at">7 - Quadros infecciosos até o momento da coleta?</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sim"</span></span>
<span id="cb13-4"><a href="#cb13-4"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb13-5"><a href="#cb13-5"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>,</span>
<span id="cb13-6"><a href="#cb13-6"></a>                <span class="st">`</span><span class="at">8 - Infecção em sistema nervoso central?</span><span class="st">`</span>,</span>
<span id="cb13-7"><a href="#cb13-7"></a>                <span class="st">`</span><span class="at">9 - Infecção de vias áreas superioras?</span><span class="st">`</span>,</span>
<span id="cb13-8"><a href="#cb13-8"></a>                <span class="st">`</span><span class="at">10 - Infecção de vias áreas inferiores?</span><span class="st">`</span>,</span>
<span id="cb13-9"><a href="#cb13-9"></a>                <span class="st">`</span><span class="at">11 - Infecção de sistema urinário?</span><span class="st">`</span>,</span>
<span id="cb13-10"><a href="#cb13-10"></a>                <span class="st">`</span><span class="at">12 - Infecção de sistema gastrointestinal?</span><span class="st">`</span>,</span>
<span id="cb13-11"><a href="#cb13-11"></a>                <span class="st">`</span><span class="at">13 - Infecção de pele?</span><span class="st">`</span>,</span>
<span id="cb13-12"><a href="#cb13-12"></a>                <span class="st">`</span><span class="at">14 - Sepse?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-13"><a href="#cb13-13"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="sc">!</span><span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-14"><a href="#cb13-14"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(value <span class="sc">==</span> <span class="st">"Sim"</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-15"><a href="#cb13-15"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(<span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-16"><a href="#cb13-16"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">n =</span> dplyr<span class="sc">::</span><span class="fu">n</span>()) <span class="sc">|&gt;</span></span>
<span id="cb13-17"><a href="#cb13-17"></a>  dplyr<span class="sc">::</span><span class="fu">ungroup</span>() <span class="sc">|&gt;</span></span>
<span id="cb13-18"><a href="#cb13-18"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb13-19"><a href="#cb13-19"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(dplyr<span class="sc">::</span><span class="fu">desc</span>(n), <span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>) </span>
<span id="cb13-20"><a href="#cb13-20"></a></span>
<span id="cb13-21"><a href="#cb13-21"></a>(</span>
<span id="cb13-22"><a href="#cb13-22"></a>  proxy2 <span class="ot">&lt;-</span> </span>
<span id="cb13-23"><a href="#cb13-23"></a>    proxy <span class="sc">|&gt;</span></span>
<span id="cb13-24"><a href="#cb13-24"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">!</span><span class="fu">c</span>(value, n)) <span class="sc">|&gt;</span> </span>
<span id="cb13-25"><a href="#cb13-25"></a>    <span class="fu">mutate</span>(<span class="at">name =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(name, <span class="st">"^[0-9]+ - "</span>),</span>
<span id="cb13-26"><a href="#cb13-26"></a>           <span class="at">name =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(name, <span class="st">"</span><span class="sc">\\</span><span class="st">?"</span>),</span>
<span id="cb13-27"><a href="#cb13-27"></a>           <span class="at">name =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(name, <span class="st">"Infecção (de|em) "</span>),</span>
<span id="cb13-28"><a href="#cb13-28"></a>           <span class="at">name =</span> stringr<span class="sc">::</span><span class="fu">str_to_sentence</span>(name)) <span class="sc">|&gt;</span></span>
<span id="cb13-29"><a href="#cb13-29"></a>    dplyr<span class="sc">::</span><span class="fu">count</span>(name) <span class="sc">|&gt;</span> </span>
<span id="cb13-30"><a href="#cb13-30"></a>    dplyr<span class="sc">::</span><span class="fu">arrange</span>(dplyr<span class="sc">::</span><span class="fu">desc</span>(n)) <span class="sc">|&gt;</span></span>
<span id="cb13-31"><a href="#cb13-31"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="dv">22</span>) </span>
<span id="cb13-32"><a href="#cb13-32"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 7 × 3
  name                         n Percentual
  &lt;chr&gt;                    &lt;int&gt;      &lt;dbl&gt;
1 Vias áreas inferiores       15      0.682
2 Vias áreas superioras       13      0.591
3 Sepse                        8      0.364
4 Pele                         7      0.318
5 Sistema urinário             6      0.273
6 Sistema gastrointestinal     5      0.227
7 Sistema nervoso central      4      0.182</code></pre>
</div>
</div>
<p>O máximo de infecções que um paciente apresenta são 4, e 5 pacientes ficaram em tal situação.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">value =</span> <span class="fu">ifelse</span>(value <span class="sc">==</span> <span class="st">"Sim"</span>, <span class="dv">1</span>, <span class="dv">0</span>)) <span class="sc">|&gt;</span></span>
<span id="cb15-3"><a href="#cb15-3"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_wider</span>(<span class="at">names_from =</span> name, <span class="at">values_from =</span> value, <span class="at">values_fill =</span> <span class="dv">0</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-4"><a href="#cb15-4"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="sc">-</span>n) <span class="sc">|&gt;</span> </span>
<span id="cb15-5"><a href="#cb15-5"></a>  tidyr<span class="sc">::</span><span class="fu">pivot_longer</span>(<span class="sc">-</span><span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>, </span>
<span id="cb15-6"><a href="#cb15-6"></a>                      <span class="at">names_to =</span> <span class="st">"Infection_Type"</span>, </span>
<span id="cb15-7"><a href="#cb15-7"></a>                      <span class="at">values_to =</span> <span class="st">"Present"</span>) <span class="sc">|&gt;</span></span>
<span id="cb15-8"><a href="#cb15-8"></a>  <span class="fu">mutate</span>(<span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(Infection_Type, <span class="st">"^[0-9]+ - "</span>),</span>
<span id="cb15-9"><a href="#cb15-9"></a>         <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(Infection_Type, <span class="st">"</span><span class="sc">\\</span><span class="st">?"</span>),</span>
<span id="cb15-10"><a href="#cb15-10"></a>         <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(Infection_Type, <span class="st">"Infecção (de|em) "</span>),</span>
<span id="cb15-11"><a href="#cb15-11"></a>         <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_to_sentence</span>(Infection_Type)) <span class="sc">|&gt;</span></span>
<span id="cb15-12"><a href="#cb15-12"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb15-13"><a href="#cb15-13"></a>  <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">factor</span>(Infection_Type, <span class="at">levels =</span> <span class="fu">unique</span>(proxy2<span class="sc">$</span>name)), </span>
<span id="cb15-14"><a href="#cb15-14"></a>      <span class="at">y =</span> <span class="fu">factor</span>(<span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>, </span>
<span id="cb15-15"><a href="#cb15-15"></a>                 <span class="at">levels =</span> <span class="fu">unique</span>(proxy<span class="sc">$</span><span class="st">`</span><span class="at">1 - Insira o Prontuário do Paciente</span><span class="st">`</span>) <span class="sc">|&gt;</span> <span class="fu">rev</span>()), </span>
<span id="cb15-16"><a href="#cb15-16"></a>      <span class="at">fill =</span> <span class="fu">as.factor</span>(Present)) <span class="sc">+</span></span>
<span id="cb15-17"><a href="#cb15-17"></a>  <span class="fu">geom_tile</span>(<span class="at">color =</span> <span class="st">"white"</span>) <span class="sc">+</span> <span class="co"># Adds a grid line effect</span></span>
<span id="cb15-18"><a href="#cb15-18"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"0"</span> <span class="ot">=</span> <span class="st">"grey95"</span>, <span class="st">"1"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>),</span>
<span id="cb15-19"><a href="#cb15-19"></a>                    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Não"</span>, <span class="st">"Sim"</span>),</span>
<span id="cb15-20"><a href="#cb15-20"></a>                    <span class="at">name =</span> <span class="st">"Presença: "</span>) <span class="sc">+</span></span>
<span id="cb15-21"><a href="#cb15-21"></a>  <span class="fu">labs</span>(<span class="at">x =</span> <span class="st">"Tipo de Infecção"</span>, <span class="at">y =</span> <span class="st">"Paciente"</span>,</span>
<span id="cb15-22"><a href="#cb15-22"></a>       <span class="at">title =</span> <span class="st">"Mapa de Calor de Infecções por Paciente"</span>,</span>
<span id="cb15-23"><a href="#cb15-23"></a>       <span class="at">subtitle =</span> <span class="st">"Apenas pacientes com ao menos dois tipos de infecção"</span>) <span class="sc">+</span></span>
<span id="cb15-24"><a href="#cb15-24"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">30</span> , <span class="at">hjust =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-7-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="e-porcentagem-de-indivíduos-com-comorbidade-e-comorbidades-mais-frequentes" class="level2">
<h2 class="anchored" data-anchor-id="e-porcentagem-de-indivíduos-com-comorbidade-e-comorbidades-mais-frequentes">e) Porcentagem de indivíduos com comorbidade e comorbidades mais frequentes</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb16-2"><a href="#cb16-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">21 - Paciente possui alguma comorbidade/diagnostico de base?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb16-3"><a href="#cb16-3"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  21 - Paciente possui alguma comorbidade/diagnostico de base…¹     n Percentual
  &lt;chr&gt;                                                         &lt;int&gt;      &lt;dbl&gt;
1 Não                                                              19      0.117
2 Sem informação                                                   29      0.179
3 Sim                                                             114      0.704
# ℹ abbreviated name:
#   ¹​`21 - Paciente possui alguma comorbidade/diagnostico de base?`</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb18-2"><a href="#cb18-2"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb18-3"><a href="#cb18-3"></a>    <span class="st">`</span><span class="at">21 - Paciente possui alguma comorbidade/diagnostico de base?</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sim"</span></span>
<span id="cb18-4"><a href="#cb18-4"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb18-5"><a href="#cb18-5"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">21.1 -  Qual comorbidade o paciente possui?</span></span>
<span id="cb18-6"><a href="#cb18-6"></a></span>
<span id="cb18-7"><a href="#cb18-7"></a><span class="at">-Em caso negativo responder com NA</span><span class="st">`</span>) <span class="sc">|&gt;</span> </span>
<span id="cb18-8"><a href="#cb18-8"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(dplyr<span class="sc">::</span><span class="fu">desc</span>(n)) <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(n <span class="sc">&gt;</span> <span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 12 × 2
   21.1 -  Qual comorbidade o paciente possui?\n\n-Em caso negativo resp…¹     n
   &lt;chr&gt;                                                                   &lt;int&gt;
 1 Síndrome genética                                                           6
 2 Alergia                                                                     5
 3 Diabetes tipo I ou II                                                       4
 4 Hepatopatia                                                                 4
 5 Síndrome nefrótica                                                          4
 6 Deformidade óssea congênita                                                 3
 7 Neurologica                                                                 3
 8 Alergia; Lúpus Eritematoso Sistêmico                                        2
 9 Anemia; TMO                                                                 2
10 Artrite Idiopática Juvenil                                                  2
11 Cardiopatia                                                                 2
12 Neurologica; Prematuridade                                                  2
# ℹ abbreviated name:
#   ¹​`21.1 -  Qual comorbidade o paciente possui?\n\n-Em caso negativo responder com NA`</code></pre>
</div>
</div>
<p>Entre os 114 pacientes com comorbidade, 87 diferentes combinações de comorbidade são observadas - mas apenas 12 aparecem em ao menos dois pacientes.</p>
</section>
<section id="f-porcentagem-de-pacientes-que-realizam-hemodiálise" class="level2">
<h2 class="anchored" data-anchor-id="f-porcentagem-de-pacientes-que-realizam-hemodiálise">f) Porcentagem de pacientes que realizam hemodiálise</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb20-2"><a href="#cb20-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">22 - Paciente realiza hemodiálise?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb20-3"><a href="#cb20-3"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  `22 - Paciente realiza hemodiálise?`     n Percentual
  &lt;chr&gt;                                &lt;int&gt;      &lt;dbl&gt;
1 Não                                     94     0.580 
2 Sem informação                          60     0.370 
3 Sim                                      8     0.0494</code></pre>
</div>
</div>
</section>
<section id="g-porcentagem-de-pacientes-que-passaram-por-cirurgia-nos-30-dias-antes-do-exame" class="level2">
<h2 class="anchored" data-anchor-id="g-porcentagem-de-pacientes-que-passaram-por-cirurgia-nos-30-dias-antes-do-exame">g) Porcentagem de pacientes que passaram por cirurgia nos 30 dias antes do exame</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb22"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb22-2"><a href="#cb22-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(</span>
<span id="cb22-3"><a href="#cb22-3"></a>    <span class="st">`</span><span class="at">23 - Paciente passou por cirurgia nos 30 dias que antecederam a realização do exame ELPT?</span><span class="st">`</span></span>
<span id="cb22-4"><a href="#cb22-4"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb22-5"><a href="#cb22-5"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  23 - Paciente passou por cirurgia nos 30 dias que anteceder…¹     n Percentual
  &lt;chr&gt;                                                         &lt;int&gt;      &lt;dbl&gt;
1 Não                                                              88     0.543 
2 Sem informação                                                   68     0.420 
3 Sim                                                               6     0.0370
# ℹ abbreviated name:
#   ¹​`23 - Paciente passou por cirurgia nos 30 dias que antecederam a realização do exame ELPT?`</code></pre>
</div>
</div>
</section>
<section id="h-porcentagem-de-pacientes-que-passaram-por-tratamento-oncológico-nos-30-antes-do-exame" class="level2">
<h2 class="anchored" data-anchor-id="h-porcentagem-de-pacientes-que-passaram-por-tratamento-oncológico-nos-30-antes-do-exame">h) Porcentagem de pacientes que passaram por tratamento oncológico nos 30 antes do exame</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb24-2"><a href="#cb24-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(</span>
<span id="cb24-3"><a href="#cb24-3"></a>    <span class="st">`</span><span class="at">24 - Paciente passou por tratamento oncológico nos 30 dias que antecederam a realização do exame ELPT?</span><span class="st">`</span></span>
<span id="cb24-4"><a href="#cb24-4"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb24-5"><a href="#cb24-5"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  24 - Paciente passou por tratamento oncológico nos 30 dias …¹     n Percentual
  &lt;chr&gt;                                                         &lt;int&gt;      &lt;dbl&gt;
1 Não                                                              93     0.574 
2 Sem informação                                                   63     0.389 
3 Sim                                                               6     0.0370
# ℹ abbreviated name:
#   ¹​`24 - Paciente passou por tratamento oncológico nos 30 dias que antecederam a realização do exame ELPT?`</code></pre>
</div>
</div>
</section>
<section id="i-porcentagem-de-pacientes-que-fizeram-uso-de-medicação" class="level2">
<h2 class="anchored" data-anchor-id="i-porcentagem-de-pacientes-que-fizeram-uso-de-medicação">i) Porcentagem de pacientes que fizeram uso de medicação</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb26-2"><a href="#cb26-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(</span>
<span id="cb26-3"><a href="#cb26-3"></a>    <span class="st">`</span><span class="at">27 - Paciente faz uso de medicação que pode causar imunodeficiência nos 30 dias que antecederam a realização do exame ELPT?</span><span class="st">`</span></span>
<span id="cb26-4"><a href="#cb26-4"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb26-5"><a href="#cb26-5"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  27 - Paciente faz uso de medicação que pode causar imunodef…¹     n Percentual
  &lt;chr&gt;                                                         &lt;int&gt;      &lt;dbl&gt;
1 Não                                                              53      0.327
2 Sem informação                                                   68      0.420
3 Sim                                                              41      0.253
# ℹ abbreviated name:
#   ¹​`27 - Paciente faz uso de medicação que pode causar imunodeficiência nos 30 dias que antecederam a realização do exame ELPT?`</code></pre>
</div>
</div>
</section>
<section id="j-porcentagem-de-pacientes-com-registro-de-óbito.-definir-intervalo-de-tempo-entre-a-data-do-exame-e-a-data-do-óbito." class="level2">
<h2 class="anchored" data-anchor-id="j-porcentagem-de-pacientes-com-registro-de-óbito.-definir-intervalo-de-tempo-entre-a-data-do-exame-e-a-data-do-óbito.">j) Porcentagem de pacientes com registro de óbito. Definir intervalo de tempo entre a data do exame e a data do óbito.</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a>elpt <span class="sc">|&gt;</span> </span>
<span id="cb28-2"><a href="#cb28-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">33 - Paciente possui registro de óbito?</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>  dplyr<span class="sc">::</span><span class="fu">mutate</span>(<span class="at">Percentual =</span> n <span class="sc">/</span> <span class="fu">nrow</span>(elpt))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 3
  `33 - Paciente possui registro de óbito?`     n Percentual
  &lt;chr&gt;                                     &lt;int&gt;      &lt;dbl&gt;
1 Não                                         152     0.938 
2 Sem informação                                2     0.0123
3 Sim                                           8     0.0494</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a>(</span>
<span id="cb30-2"><a href="#cb30-2"></a>  proxy <span class="ot">&lt;-</span> </span>
<span id="cb30-3"><a href="#cb30-3"></a>    elpt <span class="sc">|&gt;</span> </span>
<span id="cb30-4"><a href="#cb30-4"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="st">`</span><span class="at">33 - Paciente possui registro de óbito?</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sim"</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-5"><a href="#cb30-5"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(<span class="st">`</span><span class="at">5 - Data de Cadastro do Exame</span><span class="st">`</span>, </span>
<span id="cb30-6"><a href="#cb30-6"></a>                  <span class="st">`</span><span class="at">33.2 - Data de óbito</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb30-7"><a href="#cb30-7"></a>    dplyr<span class="sc">::</span><span class="fu">mutate</span>(</span>
<span id="cb30-8"><a href="#cb30-8"></a>      <span class="at">Intervalo_dias =</span> lubridate<span class="sc">::</span><span class="fu">time_length</span>(</span>
<span id="cb30-9"><a href="#cb30-9"></a>        lubridate<span class="sc">::</span><span class="fu">interval</span>(<span class="st">`</span><span class="at">5 - Data de Cadastro do Exame</span><span class="st">`</span>, <span class="st">`</span><span class="at">33.2 - Data de óbito</span><span class="st">`</span>), </span>
<span id="cb30-10"><a href="#cb30-10"></a>        <span class="st">"days"</span></span>
<span id="cb30-11"><a href="#cb30-11"></a>      ),</span>
<span id="cb30-12"><a href="#cb30-12"></a>      <span class="at">Intervalo_meses =</span> lubridate<span class="sc">::</span><span class="fu">time_length</span>(</span>
<span id="cb30-13"><a href="#cb30-13"></a>        lubridate<span class="sc">::</span><span class="fu">interval</span>(<span class="st">`</span><span class="at">5 - Data de Cadastro do Exame</span><span class="st">`</span>, <span class="st">`</span><span class="at">33.2 - Data de óbito</span><span class="st">`</span>), </span>
<span id="cb30-14"><a href="#cb30-14"></a>        <span class="st">"months"</span></span>
<span id="cb30-15"><a href="#cb30-15"></a>      )</span>
<span id="cb30-16"><a href="#cb30-16"></a>    )</span>
<span id="cb30-17"><a href="#cb30-17"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 8 × 4
  5 - Data de Cadastro d…¹ `33.2 - Data de óbito` Intervalo_dias Intervalo_meses
  &lt;dttm&gt;                   &lt;dttm&gt;                          &lt;dbl&gt;           &lt;dbl&gt;
1 2021-10-19 00:00:00      2022-01-26 00:00:00                99           3.23 
2 2019-04-29 00:00:00      2019-08-16 00:00:00               109           3.58 
3 2019-05-06 00:00:00      2020-05-12 00:00:00               372          12.2  
4 2020-10-19 00:00:00      2023-04-05 00:00:00               898          29.5  
5 2021-08-01 00:00:00      2022-04-24 00:00:00               266           8.77 
6 2024-04-21 00:00:00      2024-05-07 00:00:00                16           0.533
7 2019-06-07 00:00:00      2019-07-15 00:00:00                38           1.26 
8 2023-01-18 00:00:00      2023-07-06 00:00:00               169           5.6  
# ℹ abbreviated name: ¹​`5 - Data de Cadastro do Exame`</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb32"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1"></a><span class="fu">summary</span>(proxy<span class="sc">$</span>Intervalo_dias)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
  16.00   83.75  139.00  245.88  292.50  898.00 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1"></a><span class="fu">summary</span>(proxy<span class="sc">$</span>Intervalo_meses)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.5333  2.7339  4.5903  8.0883  9.6234 29.5484 </code></pre>
</div>
</div>
<p>Oito pacientes vieram a óbito (5%), com um tempo médio de sobrevida de 246 dias (8.1 meses) - mediana de 139 dias (4.6 meses).</p>
</section>
</section>
<section id="análise-de-indivíduos-com-dosagem-de-igg" class="level1">
<h1>2. Análise de indivíduos com dosagem de IgG</h1>
<section id="a-a-partir-dos-valores-de-dosagem-de-igg-verificar-se-existe-correlação-com-os-valores-de-elpt-não-considerar-na-estatistica-os-pacientes-que-fazem-reposição-de-igg---pois-é-um-tratamento-logo-não-é-um-dado-basal" class="level2">
<h2 class="anchored" data-anchor-id="a-a-partir-dos-valores-de-dosagem-de-igg-verificar-se-existe-correlação-com-os-valores-de-elpt-não-considerar-na-estatistica-os-pacientes-que-fazem-reposição-de-igg---pois-é-um-tratamento-logo-não-é-um-dado-basal">a) A partir dos valores de dosagem de IgG, verificar se existe correlação com os valores de ELPT; Não considerar na estatistica os pacientes que fazem reposição de IgG - pois é um tratamento, logo não é um dado basal</h2>
<p>68 pacientes (41.2%) tem registro do valor de IgG e não fizeram reposição.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1"></a>(</span>
<span id="cb36-2"><a href="#cb36-2"></a>  proxy <span class="ot">&lt;-</span> </span>
<span id="cb36-3"><a href="#cb36-3"></a>    elpt <span class="sc">|&gt;</span></span>
<span id="cb36-4"><a href="#cb36-4"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb36-5"><a href="#cb36-5"></a>      <span class="st">`</span><span class="at">19 - Fez reposições de Imunoglobulinas durante os 30 dias que antecederam a realização do exame ELPT?</span><span class="st">`</span></span>
<span id="cb36-6"><a href="#cb36-6"></a>    <span class="sc">!=</span> <span class="st">"Sim"</span> <span class="sc">&amp;</span></span>
<span id="cb36-7"><a href="#cb36-7"></a>    <span class="st">`</span><span class="at">18.1 - Como se encontra o resultado de IgG?</span></span>
<span id="cb36-8"><a href="#cb36-8"></a></span>
<span id="cb36-9"><a href="#cb36-9"></a><span class="at">NA = não se aplica</span><span class="st">`</span> <span class="sc">!=</span> <span class="st">"NA"</span></span>
<span id="cb36-10"><a href="#cb36-10"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb36-11"><a href="#cb36-11"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">IgG =</span> <span class="st">`</span><span class="at">18.2 - Qual resultado da dosagem? Colocar apenas número</span></span>
<span id="cb36-12"><a href="#cb36-12"></a></span>
<span id="cb36-13"><a href="#cb36-13"></a><span class="at">-Responder com NA em caso de não realização do exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-14"><a href="#cb36-14"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">ELPT =</span> <span class="st">`</span><span class="at">16 - Resultado do Primeiro exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb36-15"><a href="#cb36-15"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(IgG, ELPT) <span class="sc">|&gt;</span></span>
<span id="cb36-16"><a href="#cb36-16"></a>    tidyr<span class="sc">::</span><span class="fu">unnest</span>(IgG)  </span>
<span id="cb36-17"><a href="#cb36-17"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 68 × 2
     IgG  ELPT
   &lt;dbl&gt; &lt;dbl&gt;
 1   412  0.39
 2   600  0.56
 3   406  0.44
 4   424  0.45
 5   701  0.43
 6   893  0.54
 7  1376  0.26
 8   507  0.48
 9   552  0.54
10   415  0.47
# ℹ 58 more rows</code></pre>
</div>
</div>
<p>Correlação linear de Pearson de 0.55 (forte e estatísticamente significativa, 1.1e-06 = 0.0000011).</p>
<p>Contudo, vemos que o que melhor se adequa aos dados é um comportamento quadrático - subida linear até um igG ao redor de 600 e a partir dali uma queda, mas temos pouquíssimos pacientes passando desse valor.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb38"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb38-2"><a href="#cb38-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3"></a>  <span class="fu">aes</span>(<span class="at">x =</span> IgG, <span class="at">y =</span> ELPT) <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb38-6"><a href="#cb38-6"></a>              <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">2</span>), </span>
<span id="cb38-7"><a href="#cb38-7"></a>              <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb38-8"><a href="#cb38-8"></a>              <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb38-9"><a href="#cb38-9"></a>  ggpubr<span class="sc">::</span><span class="fu">stat_cor</span>(<span class="at">method =</span> <span class="st">"pearson"</span>, <span class="at">label.x =</span> <span class="dv">1000</span>, <span class="at">label.y =</span> <span class="fl">0.575</span>) <span class="sc">+</span> </span>
<span id="cb38-10"><a href="#cb38-10"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlação entre IgG e ELPT"</span>,</span>
<span id="cb38-11"><a href="#cb38-11"></a>       <span class="at">subtitle =</span> <span class="st">"Modelo Linear Quadrático (y ~ x²) com banda de confiança de 95%"</span>,</span>
<span id="cb38-12"><a href="#cb38-12"></a>       <span class="at">x =</span> <span class="st">"IgG (mg/dL)"</span>, <span class="at">y =</span> <span class="st">"ELPT (g/dL)"</span>) <span class="sc">+</span></span>
<span id="cb38-13"><a href="#cb38-13"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1400</span>, <span class="at">by =</span> <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb38-14"><a href="#cb38-14"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.05</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-15-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="b-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt" class="level2">
<h2 class="anchored" data-anchor-id="b-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt">b) Entre os indivíduos com dosagem de IgG abaixo do valor de referência, qual foi o valor médio, mínimo e máximo do valor de ELPT?</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1"></a>elpt <span class="sc">|&gt;</span></span>
<span id="cb39-2"><a href="#cb39-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(</span>
<span id="cb39-3"><a href="#cb39-3"></a>    <span class="st">`</span><span class="at">18.1 - Como se encontra o resultado de IgG?</span></span>
<span id="cb39-4"><a href="#cb39-4"></a></span>
<span id="cb39-5"><a href="#cb39-5"></a><span class="at">NA = não se aplica</span><span class="st">`</span></span>
<span id="cb39-6"><a href="#cb39-6"></a>    ) </span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  `18.1 - Como se encontra o resultado de IgG?\n\nNA = não se aplica`     n
  &lt;chr&gt;                                                               &lt;int&gt;
1 Abaixo do valor de referência                                          28
2 NA                                                                     90
3 Normal                                                                 44</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1"></a>proxy <span class="ot">&lt;-</span> </span>
<span id="cb41-2"><a href="#cb41-2"></a>  elpt <span class="sc">|&gt;</span></span>
<span id="cb41-3"><a href="#cb41-3"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb41-4"><a href="#cb41-4"></a>    <span class="st">`</span><span class="at">18.1 - Como se encontra o resultado de IgG?</span></span>
<span id="cb41-5"><a href="#cb41-5"></a></span>
<span id="cb41-6"><a href="#cb41-6"></a><span class="at">NA = não se aplica</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Abaixo do valor de referência"</span></span>
<span id="cb41-7"><a href="#cb41-7"></a>    ) <span class="sc">|&gt;</span> </span>
<span id="cb41-8"><a href="#cb41-8"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">IgG =</span> <span class="st">`</span><span class="at">18.2 - Qual resultado da dosagem? Colocar apenas número</span></span>
<span id="cb41-9"><a href="#cb41-9"></a></span>
<span id="cb41-10"><a href="#cb41-10"></a><span class="at">-Responder com NA em caso de não realização do exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-11"><a href="#cb41-11"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">ELPT =</span> <span class="st">`</span><span class="at">16 - Resultado do Primeiro exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb41-12"><a href="#cb41-12"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(IgG, ELPT) <span class="sc">|&gt;</span></span>
<span id="cb41-13"><a href="#cb41-13"></a>    tidyr<span class="sc">::</span><span class="fu">unnest</span>(IgG) </span>
<span id="cb41-14"><a href="#cb41-14"></a></span>
<span id="cb41-15"><a href="#cb41-15"></a><span class="fu">summary</span>(proxy<span class="sc">$</span>ELPT)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
 0.0600  0.2550  0.3450  0.3657  0.4900  0.6000 </code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb43-2"><a href="#cb43-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb43-3"><a href="#cb43-3"></a>  <span class="fu">aes</span>(<span class="at">x =</span> IgG, <span class="at">y =</span> ELPT) <span class="sc">+</span></span>
<span id="cb43-4"><a href="#cb43-4"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb43-5"><a href="#cb43-5"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb43-6"><a href="#cb43-6"></a>              <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">1</span>), </span>
<span id="cb43-7"><a href="#cb43-7"></a>              <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb43-8"><a href="#cb43-8"></a>              <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb43-9"><a href="#cb43-9"></a>  ggpubr<span class="sc">::</span><span class="fu">stat_cor</span>(<span class="at">method =</span> <span class="st">"pearson"</span>) <span class="sc">+</span> </span>
<span id="cb43-10"><a href="#cb43-10"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlação entre IgG e ELPT"</span>,</span>
<span id="cb43-11"><a href="#cb43-11"></a>       <span class="at">subtitle =</span> <span class="st">"Modelo Linear (y ~ x) com banda de confiança de 95%"</span>,</span>
<span id="cb43-12"><a href="#cb43-12"></a>       <span class="at">x =</span> <span class="st">"IgG (mg/dL)"</span>, <span class="at">y =</span> <span class="st">"ELPT (g/dL)"</span>) <span class="sc">+</span></span>
<span id="cb43-13"><a href="#cb43-13"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">700</span>, <span class="at">by =</span> <span class="dv">50</span>)) <span class="sc">+</span></span>
<span id="cb43-14"><a href="#cb43-14"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.05</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-16-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>ELPT médio de 0.366, min 0.06 e máx 0.6.</p>
</section>
<section id="c-entre-os-indivíduos-com-dosagem-de-igg-acima-do-valor-de-referência-e-que-não-fazem-reposição-de-igg-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt" class="level2">
<h2 class="anchored" data-anchor-id="c-entre-os-indivíduos-com-dosagem-de-igg-acima-do-valor-de-referência-e-que-não-fazem-reposição-de-igg-qual-foi-o-valor-médio-mínimo-e-máximo-do-valor-de-elpt">c) Entre os indivíduos com dosagem de IgG acima do valor de referência e que NÃO fazem reposição de IgG, qual foi o valor médio, mínimo e máximo do valor de ELPT?</h2>
<p>Nenhum paciente com IgG acima do valor de referência.</p>
</section>
<section id="d-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-quantos-possuíam-comorbidade-quais-eram-mais-frequentes" class="level2">
<h2 class="anchored" data-anchor-id="d-entre-os-indivíduos-com-dosagem-de-igg-abaixo-do-valor-de-referência-quantos-possuíam-comorbidade-quais-eram-mais-frequentes">d) Entre os indivíduos com dosagem de IgG abaixo do valor de referência, quantos possuíam comorbidade? Quais eram mais frequentes?</h2>
<p>22 pacientes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1"></a>elpt <span class="sc">|&gt;</span></span>
<span id="cb44-2"><a href="#cb44-2"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb44-3"><a href="#cb44-3"></a>    <span class="st">`</span><span class="at">18.1 - Como se encontra o resultado de IgG?</span></span>
<span id="cb44-4"><a href="#cb44-4"></a></span>
<span id="cb44-5"><a href="#cb44-5"></a><span class="at">NA = não se aplica</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Abaixo do valor de referência"</span></span>
<span id="cb44-6"><a href="#cb44-6"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb44-7"><a href="#cb44-7"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">21 - Paciente possui alguma comorbidade/diagnostico de base?</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3 × 2
  `21 - Paciente possui alguma comorbidade/diagnostico de base?`     n
  &lt;chr&gt;                                                          &lt;int&gt;
1 Não                                                                4
2 Sem informação                                                     2
3 Sim                                                               22</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1"></a>elpt <span class="sc">|&gt;</span></span>
<span id="cb46-2"><a href="#cb46-2"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(</span>
<span id="cb46-3"><a href="#cb46-3"></a>    <span class="st">`</span><span class="at">18.1 - Como se encontra o resultado de IgG?</span></span>
<span id="cb46-4"><a href="#cb46-4"></a></span>
<span id="cb46-5"><a href="#cb46-5"></a><span class="at">NA = não se aplica</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Abaixo do valor de referência"</span> <span class="sc">&amp;</span></span>
<span id="cb46-6"><a href="#cb46-6"></a>  <span class="st">`</span><span class="at">21 - Paciente possui alguma comorbidade/diagnostico de base?</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"Sim"</span></span>
<span id="cb46-7"><a href="#cb46-7"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb46-8"><a href="#cb46-8"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">21.1 -  Qual comorbidade o paciente possui?</span></span>
<span id="cb46-9"><a href="#cb46-9"></a></span>
<span id="cb46-10"><a href="#cb46-10"></a><span class="at">-Em caso negativo responder com NA</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb46-11"><a href="#cb46-11"></a>  dplyr<span class="sc">::</span><span class="fu">arrange</span>(dplyr<span class="sc">::</span><span class="fu">desc</span>(n))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 21 × 2
   21.1 -  Qual comorbidade o paciente possui?\n\n-Em caso negativo resp…¹     n
   &lt;chr&gt;                                                                   &lt;int&gt;
 1 Anemia; TMO                                                                 2
 2 Acidemia propiônica                                                         1
 3 Alergia; Cardiopatia; Hepatopatia; Hipotireoidismo; Deficiência de GH       1
 4 Alergia; Insuficiência renal; Síndrome genética; Lúpus Eritematoso Sis…     1
 5 Anemia; Síndrome de Evans                                                   1
 6 Cardiopatia; Doença renal                                                   1
 7 Cardiopatia; Hepatopatia; Pneumopatia; Síndrome genética; Hipogamaglob…     1
 8 Cardiopatia; Pneumopatia; Transplante cardíaco                              1
 9 Deformidade óssea congênita; Insuficiência renal                            1
10 Diabetes tipo I ou II                                                       1
# ℹ 11 more rows
# ℹ abbreviated name:
#   ¹​`21.1 -  Qual comorbidade o paciente possui?\n\n-Em caso negativo responder com NA`</code></pre>
</div>
</div>
</section>
</section>
<section id="análise-dos-menores-de-1-ano" class="level1">
<h1>3. Análise dos menores de 1 ano</h1>
<section id="a-entre-os-menores-de-1-ano-quantos-apresentavam-a-comorbidade-prematuridade" class="level2">
<h2 class="anchored" data-anchor-id="a-entre-os-menores-de-1-ano-quantos-apresentavam-a-comorbidade-prematuridade">a) Entre os menores de 1 ano, quantos apresentavam a comorbidade “Prematuridade”?</h2>
<p>Apenas um paciente menor de 1 ano. Paciente sem informação de comorbidades.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1"></a>elpt <span class="sc">|&gt;</span></span>
<span id="cb48-2"><a href="#cb48-2"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">3 - Insira Faixa etária do paciente</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 4 × 2
  `3 - Insira Faixa etária do paciente`     n
  &lt;chr&gt;                                 &lt;int&gt;
1 1 ano a 3 anos                           85
2 10 anos a 17 anos                        43
3 4 anos a 9 anos                          33
4 &lt; 1 ano                                   1</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1"></a>elpt <span class="sc">|&gt;</span></span>
<span id="cb50-2"><a href="#cb50-2"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(<span class="st">`</span><span class="at">3 - Insira Faixa etária do paciente</span><span class="st">`</span> <span class="sc">==</span> <span class="st">"&lt; 1 ano"</span>) <span class="sc">|&gt;</span></span>
<span id="cb50-3"><a href="#cb50-3"></a>  dplyr<span class="sc">::</span><span class="fu">count</span>(<span class="st">`</span><span class="at">21 - Paciente possui alguma comorbidade/diagnostico de base?</span><span class="st">`</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
  `21 - Paciente possui alguma comorbidade/diagnostico de base?`     n
  &lt;chr&gt;                                                          &lt;int&gt;
1 Sem informação                                                     1</code></pre>
</div>
</div>
</section>
<section id="b-levando-em-consideração-pacientes-que-fizeram-os-exames-elpt-igg-definir-um-valor-de-referência-para-elpt-levando-como-referência-a-dosagem-de-igg" class="level2">
<h2 class="anchored" data-anchor-id="b-levando-em-consideração-pacientes-que-fizeram-os-exames-elpt-igg-definir-um-valor-de-referência-para-elpt-levando-como-referência-a-dosagem-de-igg">b) Levando em consideração pacientes que fizeram os exames ELPT + IgG, definir um valor de referência para ELPT levando como referência a dosagem de IgG</h2>
<p>72 pacientes.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb52"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb52-1"><a href="#cb52-1"></a>(</span>
<span id="cb52-2"><a href="#cb52-2"></a>  proxy <span class="ot">&lt;-</span> </span>
<span id="cb52-3"><a href="#cb52-3"></a>    elpt <span class="sc">|&gt;</span></span>
<span id="cb52-4"><a href="#cb52-4"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(IgG_Referência <span class="ot">=</span> <span class="st">`</span><span class="at">18.1 - Como se encontra o resultado de IgG?</span></span>
<span id="cb52-5"><a href="#cb52-5"></a></span>
<span id="cb52-6"><a href="#cb52-6"></a><span class="at">NA = não se aplica</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-7"><a href="#cb52-7"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">IgG =</span> <span class="st">`</span><span class="at">18.2 - Qual resultado da dosagem? Colocar apenas número</span></span>
<span id="cb52-8"><a href="#cb52-8"></a></span>
<span id="cb52-9"><a href="#cb52-9"></a><span class="at">-Responder com NA em caso de não realização do exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-10"><a href="#cb52-10"></a>    dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">ELPT =</span> <span class="st">`</span><span class="at">16 - Resultado do Primeiro exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb52-11"><a href="#cb52-11"></a>    dplyr<span class="sc">::</span><span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"NA"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb52-12"><a href="#cb52-12"></a>    dplyr<span class="sc">::</span><span class="fu">select</span>(IgG, ELPT, IgG_Referência) <span class="sc">|&gt;</span></span>
<span id="cb52-13"><a href="#cb52-13"></a>    tidyr<span class="sc">::</span><span class="fu">unnest</span>(IgG)  </span>
<span id="cb52-14"><a href="#cb52-14"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 72 × 3
     IgG  ELPT IgG_Referência               
   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;                        
 1   412  0.39 Normal                       
 2   600  0.56 Abaixo do valor de referência
 3   406  0.44 Normal                       
 4   424  0.45 Abaixo do valor de referência
 5   701  0.43 Normal                       
 6   893  0.54 Normal                       
 7  1376  0.26 Normal                       
 8   507  0.48 Normal                       
 9   552  0.54 Normal                       
10   415  0.47 Normal                       
# ℹ 62 more rows</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb54"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb54-1"><a href="#cb54-1"></a>proxy <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">count</span>(IgG_Referência)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 2
  IgG_Referência                    n
  &lt;chr&gt;                         &lt;int&gt;
1 Abaixo do valor de referência    28
2 Normal                           44</code></pre>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb56"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb56-1"><a href="#cb56-1"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb56-2"><a href="#cb56-2"></a>  <span class="fu">ggplot</span>() <span class="sc">+</span></span>
<span id="cb56-3"><a href="#cb56-3"></a>  <span class="fu">aes</span>(<span class="at">x =</span> IgG, <span class="at">y =</span> ELPT, <span class="at">fill =</span>IgG_Referência, <span class="at">color =</span> IgG_Referência) <span class="sc">+</span></span>
<span id="cb56-4"><a href="#cb56-4"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="dv">3</span>, <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">alpha =</span> <span class="fl">0.6</span>) <span class="sc">+</span></span>
<span id="cb56-5"><a href="#cb56-5"></a>  <span class="fu">geom_smooth</span>(<span class="at">method =</span> <span class="st">"lm"</span>, </span>
<span id="cb56-6"><a href="#cb56-6"></a>              <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">1</span>), </span>
<span id="cb56-7"><a href="#cb56-7"></a>              <span class="at">color =</span> <span class="st">"red"</span>, </span>
<span id="cb56-8"><a href="#cb56-8"></a>              <span class="at">se =</span> <span class="cn">TRUE</span>) <span class="sc">+</span> </span>
<span id="cb56-9"><a href="#cb56-9"></a>  ggpubr<span class="sc">::</span><span class="fu">stat_cor</span>(<span class="at">method =</span> <span class="st">"pearson"</span>, </span>
<span id="cb56-10"><a href="#cb56-10"></a>                   <span class="at">label.x.npc =</span> <span class="fl">0.6</span>,   <span class="co"># 60% across the x-axis</span></span>
<span id="cb56-11"><a href="#cb56-11"></a>                   <span class="at">label.y.npc =</span> <span class="st">"bottom"</span>) <span class="sc">+</span> </span>
<span id="cb56-12"><a href="#cb56-12"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Correlação entre IgG e ELPT"</span>,</span>
<span id="cb56-13"><a href="#cb56-13"></a>       <span class="at">subtitle =</span> <span class="st">"Modelo Linear (y ~ x) com banda de confiança de 95%"</span>,</span>
<span id="cb56-14"><a href="#cb56-14"></a>       <span class="at">fill =</span> <span class="st">"Referência: "</span>, <span class="at">color =</span> <span class="st">"Referência: "</span>,</span>
<span id="cb56-15"><a href="#cb56-15"></a>       <span class="at">x =</span> <span class="st">"IgG (mg/dL)"</span>, <span class="at">y =</span> <span class="st">"ELPT (g/dL)"</span>) <span class="sc">+</span></span>
<span id="cb56-16"><a href="#cb56-16"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1400</span>, <span class="at">by =</span> <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb56-17"><a href="#cb56-17"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.6</span>, <span class="at">by =</span> <span class="fl">0.05</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-19-1.png" class="img-fluid figure-img" width="816"></p>
</figure>
</div>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb57"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1"></a>(</span>
<span id="cb57-2"><a href="#cb57-2"></a>  ref_stats <span class="ot">&lt;-</span> proxy <span class="sc">|&gt;</span></span>
<span id="cb57-3"><a href="#cb57-3"></a>    <span class="fu">filter</span>(IgG_Referência <span class="sc">==</span> <span class="st">"Normal"</span>) <span class="sc">|&gt;</span></span>
<span id="cb57-4"><a href="#cb57-4"></a>    <span class="fu">summarise</span>(</span>
<span id="cb57-5"><a href="#cb57-5"></a>      <span class="at">mean_elpt =</span> <span class="fu">mean</span>(ELPT),</span>
<span id="cb57-6"><a href="#cb57-6"></a>      <span class="at">sd_elpt =</span> <span class="fu">sd</span>(ELPT),</span>
<span id="cb57-7"><a href="#cb57-7"></a>      <span class="at">upper_ref =</span> mean_elpt <span class="sc">+</span> (<span class="dv">2</span> <span class="sc">*</span> sd_elpt),</span>
<span id="cb57-8"><a href="#cb57-8"></a>      <span class="at">lower_ref =</span> mean_elpt <span class="sc">-</span> (<span class="dv">2</span> <span class="sc">*</span> sd_elpt)</span>
<span id="cb57-9"><a href="#cb57-9"></a>    )</span>
<span id="cb57-10"><a href="#cb57-10"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 4
  mean_elpt sd_elpt upper_ref lower_ref
      &lt;dbl&gt;   &lt;dbl&gt;     &lt;dbl&gt;     &lt;dbl&gt;
1     0.467  0.0581     0.583     0.351</code></pre>
</div>
</div>
<p>Valor de referência: 0.47 (95% CI 0.35, 0.58).</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb59"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1"></a>lin_mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(</span>
<span id="cb59-2"><a href="#cb59-2"></a>  ELPT <span class="sc">~</span> IgG, </span>
<span id="cb59-3"><a href="#cb59-3"></a>  <span class="at">data =</span> proxy <span class="sc">|&gt;</span> dplyr<span class="sc">::</span><span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>)</span>
<span id="cb59-4"><a href="#cb59-4"></a>)</span>
<span id="cb59-5"><a href="#cb59-5"></a></span>
<span id="cb59-6"><a href="#cb59-6"></a><span class="co"># Fit a segmented model (it estimates where the 'plateau' starts)</span></span>
<span id="cb59-7"><a href="#cb59-7"></a><span class="co"># You provide an initial guess for the breakpoint (e.g., IgG = 600)</span></span>
<span id="cb59-8"><a href="#cb59-8"></a>seg_mod <span class="ot">&lt;-</span> <span class="fu">segmented</span>(lin_mod, <span class="at">seg.Z =</span> <span class="sc">~</span>IgG, <span class="at">psi =</span> <span class="dv">600</span>)</span>
<span id="cb59-9"><a href="#cb59-9"></a></span>
<span id="cb59-10"><a href="#cb59-10"></a><span class="co"># seg_mod$psi[, "Est."] + c(-1.95, 1.96) * seg_mod$psi[, "St.Err"]</span></span>
<span id="cb59-11"><a href="#cb59-11"></a></span>
<span id="cb59-12"><a href="#cb59-12"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb59-13"><a href="#cb59-13"></a>  <span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>) <span class="sc">|&gt;</span></span>
<span id="cb59-14"><a href="#cb59-14"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> IgG, <span class="at">y =</span> ELPT)) <span class="sc">+</span></span>
<span id="cb59-15"><a href="#cb59-15"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">xmax =</span> <span class="cn">Inf</span>, </span>
<span id="cb59-16"><a href="#cb59-16"></a>           <span class="at">ymin =</span> ref_stats<span class="sc">$</span>lower_ref, <span class="at">ymax =</span> ref_stats<span class="sc">$</span>upper_ref, </span>
<span id="cb59-17"><a href="#cb59-17"></a>           <span class="at">fill =</span> <span class="st">"steelblue"</span>, <span class="at">alpha =</span> <span class="fl">0.3</span>) <span class="sc">+</span></span>
<span id="cb59-18"><a href="#cb59-18"></a>  <span class="fu">annotate</span>(<span class="st">"segment"</span>, <span class="at">x =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">xend =</span> <span class="cn">Inf</span>, </span>
<span id="cb59-19"><a href="#cb59-19"></a>           <span class="at">y =</span> ref_stats<span class="sc">$</span>mean_elpt, <span class="at">yend =</span> ref_stats<span class="sc">$</span>mean_elpt, </span>
<span id="cb59-20"><a href="#cb59-20"></a>           <span class="at">color =</span> <span class="st">"steelblue"</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb59-21"><a href="#cb59-21"></a>  <span class="fu">geom_point</span>(<span class="fu">aes</span>(<span class="at">fill =</span> IgG_Referência), <span class="at">shape =</span> <span class="dv">21</span>, <span class="at">size =</span> <span class="dv">3</span>, <span class="at">alpha =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb59-22"><a href="#cb59-22"></a>  <span class="fu">geom_smooth</span>(</span>
<span id="cb59-23"><a href="#cb59-23"></a>    <span class="fu">aes</span>(<span class="at">color =</span> IgG_Referência), </span>
<span id="cb59-24"><a href="#cb59-24"></a>    <span class="at">method =</span> <span class="st">"lm"</span>, <span class="at">formula =</span> y <span class="sc">~</span> <span class="fu">poly</span>(x, <span class="dv">1</span>), <span class="at">se =</span> <span class="cn">TRUE</span>, <span class="at">linewidth =</span> <span class="dv">1</span></span>
<span id="cb59-25"><a href="#cb59-25"></a>  ) <span class="sc">+</span></span>
<span id="cb59-26"><a href="#cb59-26"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> seg_mod<span class="sc">$</span>psi[, <span class="st">"Est."</span>], <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">alpha =</span> <span class="fl">0.7</span>) <span class="sc">+</span></span>
<span id="cb59-27"><a href="#cb59-27"></a>  <span class="fu">scale_fill_manual</span>(</span>
<span id="cb59-28"><a href="#cb59-28"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Normal"</span> <span class="ot">=</span> <span class="st">"white"</span>, <span class="st">"Abaixo do valor de referência"</span> <span class="ot">=</span> <span class="st">"orange"</span>),</span>
<span id="cb59-29"><a href="#cb59-29"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Abaixo da Referência"</span>, <span class="st">"Normal"</span>)</span>
<span id="cb59-30"><a href="#cb59-30"></a>  ) <span class="sc">+</span></span>
<span id="cb59-31"><a href="#cb59-31"></a>  <span class="fu">scale_color_manual</span>(</span>
<span id="cb59-32"><a href="#cb59-32"></a>    <span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Normal"</span> <span class="ot">=</span> <span class="st">"darkblue"</span>, <span class="st">"Abaixo do valor de referência"</span> <span class="ot">=</span> <span class="st">"darkorange"</span>),</span>
<span id="cb59-33"><a href="#cb59-33"></a>    <span class="at">labels =</span> <span class="fu">c</span>(<span class="st">"Abaixo da Referência"</span>, <span class="st">"Normal"</span>)</span>
<span id="cb59-34"><a href="#cb59-34"></a>  ) <span class="sc">+</span></span>
<span id="cb59-35"><a href="#cb59-35"></a>  <span class="fu">labs</span>(</span>
<span id="cb59-36"><a href="#cb59-36"></a>    <span class="at">title =</span> <span class="st">"Baseline de ELPT Baseado no Platô de IgG (Grupo Normal)"</span>,</span>
<span id="cb59-37"><a href="#cb59-37"></a>    <span class="at">subtitle =</span> <span class="st">"Linhas de tendência com Intervalo de Confiança de 95% (sombreado)"</span>,</span>
<span id="cb59-38"><a href="#cb59-38"></a>    <span class="at">x =</span> <span class="st">"IgG (mg/dL)"</span>, </span>
<span id="cb59-39"><a href="#cb59-39"></a>    <span class="at">y =</span> <span class="st">"ELPT (g/dL)"</span>,</span>
<span id="cb59-40"><a href="#cb59-40"></a>    <span class="at">fill =</span> <span class="st">"Classificação IgG: "</span>, <span class="at">color =</span> <span class="st">"Classificação IgG: "</span></span>
<span id="cb59-41"><a href="#cb59-41"></a>  ) <span class="sc">+</span></span>
<span id="cb59-42"><a href="#cb59-42"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1500</span>, <span class="at">by =</span> <span class="dv">100</span>)) <span class="sc">+</span></span>
<span id="cb59-43"><a href="#cb59-43"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="fl">0.6</span>, <span class="at">by =</span> <span class="fl">0.05</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-20-1.png" class="img-fluid figure-img" width="864"></p>
</figure>
</div>
</div>
</div>
<p>Além disso, estimamos um ponto de corte para ver onde se inicia o platô - onde termina o padrão de crescimento e se inicia a estagnação de ELPT médio em relação ao IgG, é em 588.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb60"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1"></a><span class="fu">summary</span>(seg_mod)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    ***Regression Model with Segmented Relationship(s)***

Call: 
segmented.lm(obj = lin_mod, seg.Z = ~IgG, psi = 600)

Estimated Break-Point(s):
             Est. St.Err
psi1.IgG 588.442 17.276

Coefficients of the linear terms:
              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  9.757e-02  1.766e-02   5.524 5.65e-07 ***
IgG          7.855e-04  4.118e-05  19.076  &lt; 2e-16 ***
U1.IgG      -1.165e-03  7.392e-05 -15.759       NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.04372 on 68 degrees of freedom
Multiple R-Squared: 0.8623,  Adjusted R-squared: 0.8562 

Boot restarting based on 6 samples. Last fit:
Convergence attained in 2 iterations (rel. change 6.5927e-13)</code></pre>
</div>
</div>
<p>Aqui é apenas para “comprovar” que o grupo “Normal” não tem inclinação estatísticamente significativa. Neste grupo, independente do valor de IgG se espera o mesmo valor de ELPT.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb62"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb62-1"><a href="#cb62-1"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb62-2"><a href="#cb62-2"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>) <span class="sc">|&gt;</span></span>
<span id="cb62-3"><a href="#cb62-3"></a>  dplyr<span class="sc">::</span><span class="fu">group_by</span>(IgG_Referência) <span class="sc">|&gt;</span></span>
<span id="cb62-4"><a href="#cb62-4"></a>  dplyr<span class="sc">::</span><span class="fu">group_modify</span>(<span class="sc">~</span> broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">lm</span>(ELPT <span class="sc">~</span> IgG, <span class="at">data =</span> .x), <span class="at">conf.int =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span></span>
<span id="cb62-5"><a href="#cb62-5"></a>  dplyr<span class="sc">::</span><span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"IgG"</span>) <span class="sc">|&gt;</span></span>
<span id="cb62-6"><a href="#cb62-6"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(IgG_Referência, estimate, std.error, p.value, conf.low, conf.high)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2 × 6
# Groups:   IgG_Referência [2]
  IgG_Referência                  estimate std.error  p.value conf.low conf.high
  &lt;chr&gt;                              &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;    &lt;dbl&gt;     &lt;dbl&gt;
1 Abaixo do valor de referência  0.000882  0.0000553 6.16e-15  7.68e-4 0.000996 
2 Normal                        -0.0000677 0.0000508 1.90e- 1 -1.70e-4 0.0000348</code></pre>
</div>
</div>
</section>
<section id="explicação-mais-detalhada" class="level2">
<h2 class="anchored" data-anchor-id="explicação-mais-detalhada">Explicação mais detalhada</h2>
<section id="establishment-of-the-baseline-reference" class="level3">
<h3 class="anchored" data-anchor-id="establishment-of-the-baseline-reference">1. Establishment of the Baseline Reference</h3>
<p>To define a physiological ELPT baseline, the Normal Group (patients with IgG within the reference range) was used as the normative standard.</p>
<ul>
<li><p><strong>Process:</strong> We calculated the mean and standard deviation (SD) for the Normal group. The shaded area in the visualization represents the Mean ± 2 SD, covering approximately 95% of the expected physiological variation.</p></li>
<li><p><strong>Interpretation:</strong> ELPT values falling below this band indicate a pathological deficit relative to the established biological baseline.</p></li>
</ul>
</section>
<section id="group-dynamics-the-rise-vs.-attenuation-effect" class="level3">
<h3 class="anchored" data-anchor-id="group-dynamics-the-rise-vs.-attenuation-effect">2. Group Dynamics: The “Rise vs.&nbsp;Attenuation” Effect</h3>
<p>The relationship was modeled separately for each group to identify how IgG deficiency impacts ELPT measurements.</p>
<ul>
<li><p><strong>Below Reference Group:</strong> This group exhibits a significant positive slope (<span class="math inline">\(p &lt; 0.05\)</span>). This demonstrates that in patients with low IgG, ELPT is “coupled” to IgG levels—as IgG increases, ELPT rises proportionally toward the baseline.</p></li>
<li><p><strong>Normal Group:</strong> This group shows a significant change in trajectory. While the steep recovery phase ends, the group exhibits an attenuation of the slope (<span class="math inline">\(p &gt; 0.05\)</span> for a flat plateau or a very weak negative trend), representing the transition to a physiological steady state.</p></li>
</ul>
</section>
<section id="segmented-regression-inflection-point" class="level3">
<h3 class="anchored" data-anchor-id="segmented-regression-inflection-point">3. Segmented Regression (Inflection Point)</h3>
<p>A Segmented (Broken-stick) Regression was applied to mathematically determine the threshold of stabilization.</p>
<ul>
<li><p><strong>The Breakpoint:</strong> The model identifies the specific IgG coordinate where the linear recovery phase ends and the stabilization phase begins.</p></li>
<li><p><strong>Clinical Utility:</strong> This point defines the “Critical IgG Threshold” required for an ELPT measurement to be considered stable and diagnostically reliable, independent of hypogammaglobulinemia interference.</p></li>
</ul>
<hr>
</section>
<section id="summary-of-statistical-findings" class="level3">
<h3 class="anchored" data-anchor-id="summary-of-statistical-findings">Summary of Statistical Findings</h3>
<p>A positive linear dependency was observed between ELPT and IgG strictly within the deficient group (<span class="math inline">\(p &lt; 0.05\)</span>). Conversely, the normal group exhibited a stabilization phase, establishing a stable reference baseline for clinical interpretation¹.</p>
<p>¹ <em>Note: While the second segment in the ELPT model shows a statistically significant negative trend (p &lt; 0.05), the effect size is minimal compared to the recovery phase, indicating a gradual attenuation rather than a flat plateau.</em></p>
</section>
</section>
</section>
<section id="how-to-use-elpt-to-predict-igg-deficiency" class="level1">
<h1>How to use ELPT to predict IgG deficiency</h1>
<blockquote class="blockquote">
<p>Minimizing false positives, prioritizing Specificity and Positive Predictive Value (PPV).</p>
<ul>
<li>Catch fewer sick people (lower sensitivity), but almost everyone catched will actually be sick.</li>
</ul>
</blockquote>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb64"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb64-1"><a href="#cb64-1"></a><span class="co"># 1. Prepare Data</span></span>
<span id="cb64-2"><a href="#cb64-2"></a>proxy_roc <span class="ot">&lt;-</span> proxy <span class="sc">|&gt;</span></span>
<span id="cb64-3"><a href="#cb64-3"></a>  <span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-4"><a href="#cb64-4"></a>  <span class="fu">mutate</span>(<span class="at">low_igg_flag =</span> <span class="fu">ifelse</span>(IgG_Referência <span class="sc">==</span> <span class="st">"Abaixo do valor de referência"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb64-5"><a href="#cb64-5"></a></span>
<span id="cb64-6"><a href="#cb64-6"></a><span class="co"># 2. Generate ROC Object</span></span>
<span id="cb64-7"><a href="#cb64-7"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(proxy_roc<span class="sc">$</span>low_igg_flag, proxy_roc<span class="sc">$</span>ELPT, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb64-8"><a href="#cb64-8"></a></span>
<span id="cb64-9"><a href="#cb64-9"></a><span class="co"># 3. Extract Scenarios</span></span>
<span id="cb64-10"><a href="#cb64-10"></a></span>
<span id="cb64-11"><a href="#cb64-11"></a><span class="co"># A. Max Specificity (The "Perfect" but useless one)</span></span>
<span id="cb64-12"><a href="#cb64-12"></a>scen_max_spec <span class="ot">&lt;-</span> <span class="fu">coords</span>(roc_obj, <span class="st">"all"</span>, <span class="at">ret =</span> <span class="fu">c</span>(<span class="st">"threshold"</span>, <span class="st">"specificity"</span>, <span class="st">"sensitivity"</span>, <span class="st">"ppv"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb64-13"><a href="#cb64-13"></a>  <span class="fu">filter</span>(specificity <span class="sc">==</span> <span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-14"><a href="#cb64-14"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-15"><a href="#cb64-15"></a>  <span class="fu">mutate</span>(<span class="at">Strategy =</span> <span class="st">"Max Specificity (100%)"</span>)</span>
<span id="cb64-16"><a href="#cb64-16"></a></span>
<span id="cb64-17"><a href="#cb64-17"></a><span class="co"># B. High Specificity (The &gt;90% attempt)</span></span>
<span id="cb64-18"><a href="#cb64-18"></a>scen_high_spec <span class="ot">&lt;-</span> <span class="fu">coords</span>(roc_obj, <span class="st">"all"</span>, <span class="at">ret =</span> <span class="fu">c</span>(<span class="st">"threshold"</span>, <span class="st">"specificity"</span>, <span class="st">"sensitivity"</span>, <span class="st">"ppv"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb64-19"><a href="#cb64-19"></a>  <span class="fu">filter</span>(specificity <span class="sc">&gt;=</span> <span class="fl">0.90</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-20"><a href="#cb64-20"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(sensitivity)) <span class="sc">|&gt;</span> <span class="co"># Get best sensitivity in this range</span></span>
<span id="cb64-21"><a href="#cb64-21"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb64-22"><a href="#cb64-22"></a>  <span class="fu">mutate</span>(<span class="at">Strategy =</span> <span class="st">"High Specificity (&gt;90%)"</span>)</span>
<span id="cb64-23"><a href="#cb64-23"></a></span>
<span id="cb64-24"><a href="#cb64-24"></a><span class="co"># C. Balanced (Youden's Index - The Winner)</span></span>
<span id="cb64-25"><a href="#cb64-25"></a>scen_balanced <span class="ot">&lt;-</span> <span class="fu">coords</span>(roc_obj, <span class="st">"best"</span>, <span class="at">best.method =</span> <span class="st">"youden"</span>, </span>
<span id="cb64-26"><a href="#cb64-26"></a>                        <span class="at">ret =</span> <span class="fu">c</span>(<span class="st">"threshold"</span>, <span class="st">"specificity"</span>, <span class="st">"sensitivity"</span>, <span class="st">"ppv"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb64-27"><a href="#cb64-27"></a>  <span class="fu">mutate</span>(<span class="at">Strategy =</span> <span class="st">"Balanced (Youden's Index)"</span>)</span>
<span id="cb64-28"><a href="#cb64-28"></a></span>
<span id="cb64-29"><a href="#cb64-29"></a><span class="co"># 4. Combine into a Summary Table</span></span>
<span id="cb64-30"><a href="#cb64-30"></a>roc_summary <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(scen_max_spec, scen_high_spec, scen_balanced) <span class="sc">|&gt;</span></span>
<span id="cb64-31"><a href="#cb64-31"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb64-32"><a href="#cb64-32"></a>    Strategy, </span>
<span id="cb64-33"><a href="#cb64-33"></a>    <span class="at">Threshold =</span> threshold, </span>
<span id="cb64-34"><a href="#cb64-34"></a>    <span class="at">Sensitivity =</span> sensitivity, <span class="at">Specificity =</span> specificity, <span class="at">PPV =</span> ppv</span>
<span id="cb64-35"><a href="#cb64-35"></a>  )</span>
<span id="cb64-36"><a href="#cb64-36"></a></span>
<span id="cb64-37"><a href="#cb64-37"></a><span class="co"># Display Table</span></span>
<span id="cb64-38"><a href="#cb64-38"></a><span class="fu">kable</span>(roc_summary, <span class="at">digits =</span> <span class="dv">3</span>, <span class="at">caption =</span> <span class="st">"Comparison of Cutoff Strategies"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Comparison of Cutoff Strategies</caption>
<colgroup>
<col style="width: 13%">
<col style="width: 34%">
<col style="width: 13%">
<col style="width: 15%">
<col style="width: 15%">
<col style="width: 7%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: left;">Strategy</th>
<th style="text-align: right;">Threshold</th>
<th style="text-align: right;">Sensitivity</th>
<th style="text-align: right;">Specificity</th>
<th style="text-align: right;">PPV</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">…1</td>
<td style="text-align: left;">Max Specificity (100%)</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">0.250</td>
<td style="text-align: right;">1.000</td>
<td style="text-align: right;">1.000</td>
</tr>
<tr class="even">
<td style="text-align: left;">…2</td>
<td style="text-align: left;">High Specificity (&gt;90%)</td>
<td style="text-align: right;">0.395</td>
<td style="text-align: right;">0.607</td>
<td style="text-align: right;">0.909</td>
<td style="text-align: right;">0.810</td>
</tr>
<tr class="odd">
<td style="text-align: left;">threshold</td>
<td style="text-align: left;">Balanced (Youden’s Index)</td>
<td style="text-align: right;">0.410</td>
<td style="text-align: right;">0.643</td>
<td style="text-align: right;">0.886</td>
<td style="text-align: right;">0.783</td>
</tr>
</tbody>
</table>
</div>
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb65"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb65-1"><a href="#cb65-1"></a><span class="co"># 5. Visualization: Density Plot with the Winner Cutoff</span></span>
<span id="cb65-2"><a href="#cb65-2"></a>optimal_cutoff <span class="ot">&lt;-</span> scen_balanced<span class="sc">$</span>threshold</span>
<span id="cb65-3"><a href="#cb65-3"></a></span>
<span id="cb65-4"><a href="#cb65-4"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb65-5"><a href="#cb65-5"></a>  <span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>) <span class="sc">|&gt;</span></span>
<span id="cb65-6"><a href="#cb65-6"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ELPT, <span class="at">fill =</span> IgG_Referência)) <span class="sc">+</span></span>
<span id="cb65-7"><a href="#cb65-7"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb65-8"><a href="#cb65-8"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> optimal_cutoff, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"black"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb65-9"><a href="#cb65-9"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> optimal_cutoff, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">" Optimal Cutoff:"</span>, <span class="fu">round</span>(optimal_cutoff, <span class="dv">2</span>)), </span>
<span id="cb65-10"><a href="#cb65-10"></a>           <span class="at">hjust =</span> <span class="fl">1.05</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">2</span>, <span class="at">angle =</span> <span class="dv">0</span>, <span class="at">fontface =</span> <span class="st">"bold"</span>) <span class="sc">+</span></span>
<span id="cb65-11"><a href="#cb65-11"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Normal"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>, <span class="st">"Abaixo do valor de referência"</span> <span class="ot">=</span> <span class="st">"orange"</span>)) <span class="sc">+</span></span>
<span id="cb65-12"><a href="#cb65-12"></a>  <span class="fu">labs</span>(</span>
<span id="cb65-13"><a href="#cb65-13"></a>    <span class="at">title =</span> <span class="st">"Clinical Decision Threshold"</span>,</span>
<span id="cb65-14"><a href="#cb65-14"></a>    <span class="at">subtitle =</span> <span class="st">"Overlap of ELPT distributions with optimal screening cutoff"</span>,</span>
<span id="cb65-15"><a href="#cb65-15"></a>    <span class="at">x =</span> <span class="st">"ELPT (g/dL)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">fill =</span> <span class="st">"IgG Status"</span></span>
<span id="cb65-16"><a href="#cb65-16"></a>  ) <span class="sc">+</span></span>
<span id="cb65-17"><a href="#cb65-17"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-23-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="diagnostic-screening-elpt-as-a-predictor-for-igg-testing" class="level2">
<h2 class="anchored" data-anchor-id="diagnostic-screening-elpt-as-a-predictor-for-igg-testing">Diagnostic Screening: ELPT as a Predictor for IgG Testing</h2>
<p>We evaluated the diagnostic performance of <strong>ELPT</strong> to identify a threshold that signals IgG deficiency.</p>
<p>We compared three cutoff strategies to determine the optimal balance between minimizing false positives (Specificity) and maximizing disease detection (Sensitivity).</p>
<section id="analysis-of-cutoff-strategies" class="level3">
<h3 class="anchored" data-anchor-id="analysis-of-cutoff-strategies">Analysis of Cutoff Strategies</h3>
<p>The table above summarizes the performance of the potential thresholds:</p>
<ol type="1">
<li><strong>Max Specificity Strategy (Cutoff 0.250):</strong>
<ul>
<li><strong>Pros:</strong> Perfect Specificity (100%) and PPV (100%). If a patient falls below this level, they are certainly deficient.</li>
<li><strong>Cons:</strong> Sensitivity is critically low (25%). This threshold is too conservative for screening, as it misses nearly three-quarters of the target population.</li>
</ul></li>
<li><strong>High Specificity Strategy (Cutoff 0.395):</strong>
<ul>
<li><strong>Performance:</strong> This threshold provides strong specificity (91%) with a Positive Predictive Value of 81%.</li>
<li><strong>Trade-off:</strong> Sensitivity increases to 60.7%, capturing a majority of cases while maintaining a low false-positive rate.</li>
</ul></li>
<li><strong>Balanced “Youden” Strategy (Cutoff 0.410):</strong>
<ul>
<li><strong>Pros:</strong> Optimizes the overall accuracy. It offers the highest <strong>Sensitivity (64.3%)</strong> among the viable options while maintaining a robust <strong>Specificity (88.6%)</strong>.</li>
<li><strong>Clinical Context:</strong> Unlike PROTF, which prioritized sensitivity at the cost of specificity, ELPT demonstrates naturally higher specificity. The values for the “High Specificity” and “Balanced” strategies are numerically very close (0.395 vs.&nbsp;0.410), indicating a stable diagnostic zone.</li>
</ul></li>
</ol>
</section>
<section id="conclusion-and-recommendation" class="level3">
<h3 class="anchored" data-anchor-id="conclusion-and-recommendation">Conclusion and Recommendation</h3>
<p>We recommend the <strong>Balanced Strategy</strong> as the clinical standard for ELPT.</p>
<p><strong>Recommendation:</strong> An ELPT value below <strong>0.410</strong> should trigger a follow-up IgG test.</p>
<ul>
<li><strong>Performance:</strong> At this threshold, the test detects approximately <strong>65%</strong> of IgG-deficient patients (Sensitivity).</li>
<li><strong>Precision:</strong> Crucially, it generates very few false alarms (Specificity <strong>88.6%</strong>), meaning that patients flagged by ELPT have a high probability (PPV <strong>78.3%</strong>) of actually requiring intervention.</li>
</ul>
</section>
</section>
<section id="advanced-strategy-the-indeterminate-zone-approach" class="level2">
<h2 class="anchored" data-anchor-id="advanced-strategy-the-indeterminate-zone-approach">Advanced Strategy: The “Indeterminate Zone” Approach</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb66"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb66-1"><a href="#cb66-1"></a><span class="co"># 1. Prepare Data &amp; ROC</span></span>
<span id="cb66-2"><a href="#cb66-2"></a>proxy_roc <span class="ot">&lt;-</span> proxy <span class="sc">|&gt;</span></span>
<span id="cb66-3"><a href="#cb66-3"></a>  <span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-4"><a href="#cb66-4"></a>  <span class="fu">mutate</span>(<span class="at">low_igg_flag =</span> <span class="fu">ifelse</span>(IgG_Referência <span class="sc">==</span> <span class="st">"Abaixo do valor de referência"</span>, <span class="dv">1</span>, <span class="dv">0</span>))</span>
<span id="cb66-5"><a href="#cb66-5"></a></span>
<span id="cb66-6"><a href="#cb66-6"></a>roc_obj <span class="ot">&lt;-</span> <span class="fu">roc</span>(proxy_roc<span class="sc">$</span>low_igg_flag, proxy_roc<span class="sc">$</span>ELPT, <span class="at">quiet =</span> <span class="cn">TRUE</span>)</span>
<span id="cb66-7"><a href="#cb66-7"></a></span>
<span id="cb66-8"><a href="#cb66-8"></a><span class="co"># 2. Extract All Coordinates</span></span>
<span id="cb66-9"><a href="#cb66-9"></a>all_coords <span class="ot">&lt;-</span> <span class="fu">coords</span>(roc_obj, <span class="st">"all"</span>, <span class="at">ret =</span> <span class="fu">c</span>(<span class="st">"threshold"</span>, <span class="st">"specificity"</span>, <span class="st">"sensitivity"</span>))</span>
<span id="cb66-10"><a href="#cb66-10"></a></span>
<span id="cb66-11"><a href="#cb66-11"></a><span class="co"># 3. Find the Boundaries (Using &gt;= Logic to avoid NA)</span></span>
<span id="cb66-12"><a href="#cb66-12"></a></span>
<span id="cb66-13"><a href="#cb66-13"></a><span class="co"># A. LOWER CUTOFF (Red Zone Boundary)</span></span>
<span id="cb66-14"><a href="#cb66-14"></a><span class="co"># Logic: We want High Specificity (&gt;= 95%) to be sure they are sick.</span></span>
<span id="cb66-15"><a href="#cb66-15"></a><span class="co"># We pick the threshold with the highest sensitivity possible within that constraint.</span></span>
<span id="cb66-16"><a href="#cb66-16"></a>cutoff_red <span class="ot">&lt;-</span> all_coords <span class="sc">|&gt;</span></span>
<span id="cb66-17"><a href="#cb66-17"></a>  <span class="fu">filter</span>(specificity <span class="sc">&gt;=</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-18"><a href="#cb66-18"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(sensitivity)) <span class="sc">|&gt;</span> </span>
<span id="cb66-19"><a href="#cb66-19"></a>  <span class="fu">slice</span>(<span class="dv">1</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-20"><a href="#cb66-20"></a>  <span class="fu">pull</span>(threshold)</span>
<span id="cb66-21"><a href="#cb66-21"></a></span>
<span id="cb66-22"><a href="#cb66-22"></a><span class="co"># B. UPPER CUTOFF (Green Zone Boundary)</span></span>
<span id="cb66-23"><a href="#cb66-23"></a><span class="co"># Logic: We want High Sensitivity (&gt;= 95%) to be sure we don't miss anyone.</span></span>
<span id="cb66-24"><a href="#cb66-24"></a><span class="co"># We pick the threshold with the highest specificity possible within that constraint.</span></span>
<span id="cb66-25"><a href="#cb66-25"></a>cutoff_green <span class="ot">&lt;-</span> all_coords <span class="sc">|&gt;</span></span>
<span id="cb66-26"><a href="#cb66-26"></a>  <span class="fu">filter</span>(sensitivity <span class="sc">&gt;=</span> <span class="fl">0.95</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-27"><a href="#cb66-27"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(specificity)) <span class="sc">|&gt;</span> </span>
<span id="cb66-28"><a href="#cb66-28"></a>  <span class="fu">slice</span>(<span class="dv">2</span>) <span class="sc">|&gt;</span></span>
<span id="cb66-29"><a href="#cb66-29"></a>  <span class="fu">pull</span>(threshold)</span>
<span id="cb66-30"><a href="#cb66-30"></a></span>
<span id="cb66-31"><a href="#cb66-31"></a><span class="co"># 4. Print Values for verification</span></span>
<span id="cb66-32"><a href="#cb66-32"></a><span class="fu">rbind</span>(</span>
<span id="cb66-33"><a href="#cb66-33"></a>  <span class="fu">paste</span>(<span class="st">"Red Zone (Deficient) &lt;"</span>, <span class="fu">round</span>(cutoff_red, <span class="dv">2</span>)),</span>
<span id="cb66-34"><a href="#cb66-34"></a>  <span class="fu">paste</span>(<span class="st">"Grey Zone (Indeterminate):"</span>, <span class="fu">round</span>(cutoff_red, <span class="dv">2</span>), <span class="st">"-"</span>, <span class="fu">round</span>(cutoff_green, <span class="dv">2</span>)),</span>
<span id="cb66-35"><a href="#cb66-35"></a>  <span class="fu">paste</span>(<span class="st">"Green Zone (Safe) &gt;"</span>, <span class="fu">round</span>(cutoff_green, <span class="dv">2</span>))</span>
<span id="cb66-36"><a href="#cb66-36"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>     [,1]                                   
[1,] "Red Zone (Deficient) &lt; 0.38"          
[2,] "Grey Zone (Indeterminate): 0.38 - 0.6"
[3,] "Green Zone (Safe) &gt; 0.6"              </code></pre>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb68"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb68-1"><a href="#cb68-1"></a><span class="co"># 2. Visualize the Zones</span></span>
<span id="cb68-2"><a href="#cb68-2"></a>proxy <span class="sc">|&gt;</span></span>
<span id="cb68-3"><a href="#cb68-3"></a>  <span class="fu">filter</span>(IgG_Referência <span class="sc">!=</span> <span class="st">"Acima do valor de referência"</span>) <span class="sc">|&gt;</span></span>
<span id="cb68-4"><a href="#cb68-4"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> ELPT, <span class="at">fill =</span> IgG_Referência)) <span class="sc">+</span></span>
<span id="cb68-5"><a href="#cb68-5"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.4</span>) <span class="sc">+</span></span>
<span id="cb68-6"><a href="#cb68-6"></a>  <span class="co"># Red Zone</span></span>
<span id="cb68-7"><a href="#cb68-7"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> <span class="sc">-</span><span class="cn">Inf</span>, <span class="at">xmax =</span> cutoff_red, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="cn">Inf</span>, </span>
<span id="cb68-8"><a href="#cb68-8"></a>           <span class="at">fill =</span> <span class="st">"firebrick"</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb68-9"><a href="#cb68-9"></a>  <span class="co"># Grey Zone</span></span>
<span id="cb68-10"><a href="#cb68-10"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> cutoff_red, <span class="at">xmax =</span> cutoff_green, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="cn">Inf</span>, </span>
<span id="cb68-11"><a href="#cb68-11"></a>           <span class="at">fill =</span> <span class="st">"gold"</span>, <span class="at">alpha =</span> <span class="fl">0.15</span>) <span class="sc">+</span></span>
<span id="cb68-12"><a href="#cb68-12"></a>  <span class="co"># Green Zone</span></span>
<span id="cb68-13"><a href="#cb68-13"></a>  <span class="fu">annotate</span>(<span class="st">"rect"</span>, <span class="at">xmin =</span> cutoff_green, <span class="at">xmax =</span> <span class="cn">Inf</span>, <span class="at">ymin =</span> <span class="dv">0</span>, <span class="at">ymax =</span> <span class="cn">Inf</span>, </span>
<span id="cb68-14"><a href="#cb68-14"></a>           <span class="at">fill =</span> <span class="st">"forestgreen"</span>, <span class="at">alpha =</span> <span class="fl">0.1</span>) <span class="sc">+</span></span>
<span id="cb68-15"><a href="#cb68-15"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="fu">c</span>(cutoff_red, cutoff_green), <span class="at">linetype =</span> <span class="st">"dashed"</span>) <span class="sc">+</span></span>
<span id="cb68-16"><a href="#cb68-16"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> cutoff_red, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Red &lt;"</span>, <span class="fu">round</span>(cutoff_red, <span class="dv">2</span>)), </span>
<span id="cb68-17"><a href="#cb68-17"></a>           <span class="at">hjust =</span> <span class="fl">1.1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">10</span>, <span class="at">angle =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"firebrick"</span>) <span class="sc">+</span></span>
<span id="cb68-18"><a href="#cb68-18"></a>  <span class="fu">annotate</span>(<span class="st">"text"</span>, <span class="at">x =</span> cutoff_green, <span class="at">y =</span> <span class="dv">0</span>, <span class="at">label =</span> <span class="fu">paste</span>(<span class="st">"Green &gt;"</span>, <span class="fu">round</span>(cutoff_green, <span class="dv">2</span>)), </span>
<span id="cb68-19"><a href="#cb68-19"></a>           <span class="at">hjust =</span> <span class="fl">1.1</span>, <span class="at">vjust =</span> <span class="sc">-</span><span class="dv">10</span>, <span class="at">angle =</span> <span class="dv">0</span>, <span class="at">color =</span> <span class="st">"forestgreen"</span>) <span class="sc">+</span></span>
<span id="cb68-20"><a href="#cb68-20"></a>  <span class="fu">scale_fill_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Normal"</span> <span class="ot">=</span> <span class="st">"steelblue"</span>, <span class="st">"Abaixo do valor de referência"</span> <span class="ot">=</span> <span class="st">"orange"</span>)) <span class="sc">+</span></span>
<span id="cb68-21"><a href="#cb68-21"></a>  <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">"Traffic Light System: Managing Clinical Overlap"</span>,</span>
<span id="cb68-22"><a href="#cb68-22"></a>       <span class="at">subtitle =</span> <span class="st">"Red: High Probability of Deficiency | Grey: Indeterminate | Green: High Probability of Normal"</span>,</span>
<span id="cb68-23"><a href="#cb68-23"></a>       <span class="at">x =</span> <span class="st">"ELPT (g/dL)"</span>, <span class="at">y =</span> <span class="st">"Density"</span>, <span class="at">fill =</span> <span class="st">"IgG Status"</span>) <span class="sc">+</span></span>
<span id="cb68-24"><a href="#cb68-24"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">1</span>, <span class="at">by =</span> <span class="fl">0.1</span>)) <span class="sc">+</span></span>
<span id="cb68-25"><a href="#cb68-25"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">0</span>, <span class="dv">10</span>, <span class="at">by =</span> <span class="dv">1</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-25-1.png" class="img-fluid figure-img" width="912"></p>
</figure>
</div>
</div>
</div>
<p>Given the distributional overlap observed in the ELPT data, a single binary cutoff may not sufficiently capture the clinical complexity. To address this, we applied a <strong>Two-Cutoff Strategy</strong> (Traffic Light System) to isolate the zone of diagnostic uncertainty.</p>
<p>We defined three clinical zones based on strict statistical safety margins:</p>
<ol type="1">
<li><strong>Deficiency Zone (&lt; 0.38):</strong>
<ul>
<li><strong>Definition:</strong> Threshold established at <strong>≥95% Specificity</strong>.</li>
<li><strong>Implication:</strong> ELPT values below <strong>0.38</strong> are highly indicative of IgG deficiency. The probability of a false positive in this range is minimal, warranting immediate clinical action or substitution therapy consideration.</li>
</ul></li>
<li><strong>Safety Zone (&gt; 0.60):</strong>
<ul>
<li><strong>Definition:</strong> Threshold established at <strong>≥95% Sensitivity</strong>.</li>
<li><strong>Implication:</strong> ELPT values above <strong>0.60</strong> effectively rule out deficiency with high confidence. The risk of missing a true deficient case in this range is negligible.</li>
</ul></li>
<li><strong>Indeterminate “Grey” Zone (0.38 – 0.60):</strong>
<ul>
<li><strong>Definition:</strong> The interval between the high-specificity and high-sensitivity thresholds.</li>
<li><strong>Implication:</strong> Patients falling within this range (0.38 to 0.60) represent a diagnostic challenge where ELPT alone is inconclusive due to biological overlap. For these individuals, <strong>mandatory IgG quantification</strong> is recommended to resolve the diagnosis.</li>
</ul></li>
</ol>
<p><strong>Conclusion:</strong> By defining 0.38 and 0.60 as the critical boundaries, we enhance diagnostic precision for patients at the extremes while clearly identifying the subset of patients requiring confirmatory testing.</p>
</section>
<section id="infections" class="level2">
<h2 class="anchored" data-anchor-id="infections">Infections</h2>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb69"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb69-1"><a href="#cb69-1"></a><span class="co"># Define your Cutoff (Use the Balanced one found earlier)</span></span>
<span id="cb69-2"><a href="#cb69-2"></a>elpt_cutoff <span class="ot">&lt;-</span> <span class="fl">0.41</span></span>
<span id="cb69-3"><a href="#cb69-3"></a></span>
<span id="cb69-4"><a href="#cb69-4"></a>infection_analysis <span class="ot">&lt;-</span> elpt <span class="sc">|&gt;</span></span>
<span id="cb69-5"><a href="#cb69-5"></a>  dplyr<span class="sc">::</span><span class="fu">rename</span>(<span class="at">ELPT =</span> <span class="st">`</span><span class="at">16 - Resultado do Primeiro exame</span><span class="st">`</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-6"><a href="#cb69-6"></a>  <span class="co"># Create Binary Groups based on Cutoff</span></span>
<span id="cb69-7"><a href="#cb69-7"></a>  <span class="fu">mutate</span>(<span class="at">Risk_Group =</span> <span class="fu">ifelse</span>(ELPT <span class="sc">&lt;</span> elpt_cutoff, <span class="st">"High_Risk"</span>, <span class="st">"Low_Risk"</span>)) <span class="sc">|&gt;</span></span>
<span id="cb69-8"><a href="#cb69-8"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb69-9"><a href="#cb69-9"></a>    Risk_Group,</span>
<span id="cb69-10"><a href="#cb69-10"></a>    <span class="st">`</span><span class="at">8 - Infecção em sistema nervoso central?</span><span class="st">`</span>,</span>
<span id="cb69-11"><a href="#cb69-11"></a>    <span class="st">`</span><span class="at">9 - Infecção de vias áreas superioras?</span><span class="st">`</span>,</span>
<span id="cb69-12"><a href="#cb69-12"></a>    <span class="st">`</span><span class="at">10 - Infecção de vias áreas inferiores?</span><span class="st">`</span>,</span>
<span id="cb69-13"><a href="#cb69-13"></a>    <span class="st">`</span><span class="at">11 - Infecção de sistema urinário?</span><span class="st">`</span>,</span>
<span id="cb69-14"><a href="#cb69-14"></a>    <span class="st">`</span><span class="at">12 - Infecção de sistema gastrointestinal?</span><span class="st">`</span>,</span>
<span id="cb69-15"><a href="#cb69-15"></a>    <span class="st">`</span><span class="at">13 - Infecção de pele?</span><span class="st">`</span>,</span>
<span id="cb69-16"><a href="#cb69-16"></a>    <span class="st">`</span><span class="at">14 - Sepse?</span><span class="st">`</span></span>
<span id="cb69-17"><a href="#cb69-17"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-18"><a href="#cb69-18"></a>  <span class="fu">pivot_longer</span>(</span>
<span id="cb69-19"><a href="#cb69-19"></a>    <span class="at">cols =</span> <span class="sc">!</span>Risk_Group,</span>
<span id="cb69-20"><a href="#cb69-20"></a>    <span class="at">names_to =</span> <span class="st">"Infection_Type"</span>,</span>
<span id="cb69-21"><a href="#cb69-21"></a>    <span class="at">values_to =</span> <span class="st">"Status"</span></span>
<span id="cb69-22"><a href="#cb69-22"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-23"><a href="#cb69-23"></a>  <span class="fu">mutate</span>(</span>
<span id="cb69-24"><a href="#cb69-24"></a>    <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(Infection_Type, <span class="st">"^</span><span class="sc">\\</span><span class="st">d+ - "</span>),</span>
<span id="cb69-25"><a href="#cb69-25"></a>    <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(Infection_Type, <span class="st">"</span><span class="sc">\\</span><span class="st">?"</span>),</span>
<span id="cb69-26"><a href="#cb69-26"></a>    <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_remove</span>(Infection_Type, <span class="st">"^Infecção (de|em) "</span>),</span>
<span id="cb69-27"><a href="#cb69-27"></a>    <span class="at">Infection_Type =</span> stringr<span class="sc">::</span><span class="fu">str_to_sentence</span>(Infection_Type),</span>
<span id="cb69-28"><a href="#cb69-28"></a>    <span class="at">Is_Infected =</span> <span class="fu">ifelse</span>(Status <span class="sc">==</span> <span class="st">"Sim"</span>, <span class="dv">1</span>, <span class="dv">0</span>)</span>
<span id="cb69-29"><a href="#cb69-29"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-30"><a href="#cb69-30"></a>  <span class="co"># Remove NAs if any exist in Status/Risk_Group</span></span>
<span id="cb69-31"><a href="#cb69-31"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Is_Infected))</span>
<span id="cb69-32"><a href="#cb69-32"></a></span>
<span id="cb69-33"><a href="#cb69-33"></a>rates_table <span class="ot">&lt;-</span> infection_analysis <span class="sc">|&gt;</span></span>
<span id="cb69-34"><a href="#cb69-34"></a>  <span class="fu">group_by</span>(Infection_Type, Risk_Group) <span class="sc">|&gt;</span></span>
<span id="cb69-35"><a href="#cb69-35"></a>  <span class="fu">summarise</span>(</span>
<span id="cb69-36"><a href="#cb69-36"></a>    <span class="at">Total_Patients =</span> <span class="fu">n</span>(),</span>
<span id="cb69-37"><a href="#cb69-37"></a>    <span class="at">Infected_Count =</span> <span class="fu">sum</span>(Is_Infected),</span>
<span id="cb69-38"><a href="#cb69-38"></a>    <span class="at">Rate_Pct =</span> (Infected_Count <span class="sc">/</span> Total_Patients) <span class="sc">*</span> <span class="dv">100</span>, <span class="co"># Em porcentagem</span></span>
<span id="cb69-39"><a href="#cb69-39"></a>    <span class="at">.groups =</span> <span class="st">"drop"</span></span>
<span id="cb69-40"><a href="#cb69-40"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-41"><a href="#cb69-41"></a>  <span class="co"># Coloca High_Risk e Low_Risk lado a lado</span></span>
<span id="cb69-42"><a href="#cb69-42"></a>  <span class="fu">pivot_wider</span>(</span>
<span id="cb69-43"><a href="#cb69-43"></a>    <span class="at">names_from =</span> Risk_Group,</span>
<span id="cb69-44"><a href="#cb69-44"></a>    <span class="at">values_from =</span> <span class="fu">c</span>(Total_Patients, Infected_Count, Rate_Pct)</span>
<span id="cb69-45"><a href="#cb69-45"></a>  )</span>
<span id="cb69-46"><a href="#cb69-46"></a></span>
<span id="cb69-47"><a href="#cb69-47"></a>stats_table <span class="ot">&lt;-</span> infection_analysis <span class="sc">|&gt;</span></span>
<span id="cb69-48"><a href="#cb69-48"></a>  <span class="fu">group_by</span>(Infection_Type) <span class="sc">|&gt;</span></span>
<span id="cb69-49"><a href="#cb69-49"></a>  <span class="fu">nest</span>() <span class="sc">|&gt;</span></span>
<span id="cb69-50"><a href="#cb69-50"></a>  <span class="fu">mutate</span>(</span>
<span id="cb69-51"><a href="#cb69-51"></a>    <span class="at">model =</span> <span class="fu">map</span>(data, <span class="cf">function</span>(df) {</span>
<span id="cb69-52"><a href="#cb69-52"></a>      <span class="co"># Tabela cruzada 2x2</span></span>
<span id="cb69-53"><a href="#cb69-53"></a>      tbl <span class="ot">&lt;-</span> <span class="fu">table</span>(df<span class="sc">$</span>Risk_Group, df<span class="sc">$</span>Is_Infected)</span>
<span id="cb69-54"><a href="#cb69-54"></a>      </span>
<span id="cb69-55"><a href="#cb69-55"></a>      <span class="co"># Verifica se a tabela é válida (tem 2 grupos de risco e pelo menos infectados e não infectados no geral)</span></span>
<span id="cb69-56"><a href="#cb69-56"></a>      <span class="co"># Se for muito esparsa, fisher.test pode falhar ou retornar NULL</span></span>
<span id="cb69-57"><a href="#cb69-57"></a>      <span class="fu">tryCatch</span>({</span>
<span id="cb69-58"><a href="#cb69-58"></a>        broom<span class="sc">::</span><span class="fu">tidy</span>(<span class="fu">fisher.test</span>(tbl))</span>
<span id="cb69-59"><a href="#cb69-59"></a>      }, <span class="at">error =</span> <span class="cf">function</span>(e) <span class="cn">NULL</span>)</span>
<span id="cb69-60"><a href="#cb69-60"></a>    })</span>
<span id="cb69-61"><a href="#cb69-61"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-62"><a href="#cb69-62"></a>  <span class="fu">unnest</span>(model) <span class="sc">|&gt;</span></span>
<span id="cb69-63"><a href="#cb69-63"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(Infection_Type, estimate, p.value, conf.low, conf.high)</span>
<span id="cb69-64"><a href="#cb69-64"></a></span>
<span id="cb69-65"><a href="#cb69-65"></a>final_results <span class="ot">&lt;-</span> rates_table <span class="sc">|&gt;</span></span>
<span id="cb69-66"><a href="#cb69-66"></a>  <span class="fu">left_join</span>(stats_table, <span class="at">by =</span> <span class="st">"Infection_Type"</span>) <span class="sc">|&gt;</span></span>
<span id="cb69-67"><a href="#cb69-67"></a>  <span class="fu">mutate</span>(</span>
<span id="cb69-68"><a href="#cb69-68"></a>    <span class="at">Odds_Ratio =</span> estimate,</span>
<span id="cb69-69"><a href="#cb69-69"></a>    <span class="at">Significant =</span> <span class="fu">ifelse</span>(p.value <span class="sc">&lt;</span> <span class="fl">0.05</span>, <span class="st">"Yes"</span>, <span class="st">"No"</span>)</span>
<span id="cb69-70"><a href="#cb69-70"></a>  ) <span class="sc">|&gt;</span></span>
<span id="cb69-71"><a href="#cb69-71"></a>  dplyr<span class="sc">::</span><span class="fu">select</span>(</span>
<span id="cb69-72"><a href="#cb69-72"></a>    Infection_Type, </span>
<span id="cb69-73"><a href="#cb69-73"></a>    <span class="at">Rate_High =</span> Rate_Pct_High_Risk, </span>
<span id="cb69-74"><a href="#cb69-74"></a>    <span class="at">Rate_Low =</span> Rate_Pct_Low_Risk,</span>
<span id="cb69-75"><a href="#cb69-75"></a>    Odds_Ratio, </span>
<span id="cb69-76"><a href="#cb69-76"></a>    conf.low, </span>
<span id="cb69-77"><a href="#cb69-77"></a>    conf.high,</span>
<span id="cb69-78"><a href="#cb69-78"></a>    p.value, </span>
<span id="cb69-79"><a href="#cb69-79"></a>    Significant</span>
<span id="cb69-80"><a href="#cb69-80"></a>  )</span>
<span id="cb69-81"><a href="#cb69-81"></a></span>
<span id="cb69-82"><a href="#cb69-82"></a>knitr<span class="sc">::</span><span class="fu">kable</span>(</span>
<span id="cb69-83"><a href="#cb69-83"></a>  final_results, <span class="at">digits =</span> <span class="dv">2</span>, </span>
<span id="cb69-84"><a href="#cb69-84"></a>  <span class="at">caption =</span> <span class="st">"Prevalência de Infecções por Grupo de Risco (ELPT &lt; 0.41)"</span></span>
<span id="cb69-85"><a href="#cb69-85"></a>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Prevalência de Infecções por Grupo de Risco (ELPT &lt; 0.41)</caption>
<colgroup>
<col style="width: 26%">
<col style="width: 10%">
<col style="width: 9%">
<col style="width: 11%">
<col style="width: 9%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 12%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Infection_Type</th>
<th style="text-align: right;">Rate_High</th>
<th style="text-align: right;">Rate_Low</th>
<th style="text-align: right;">Odds_Ratio</th>
<th style="text-align: right;">conf.low</th>
<th style="text-align: right;">conf.high</th>
<th style="text-align: right;">p.value</th>
<th style="text-align: left;">Significant</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pele</td>
<td style="text-align: right;">13.64</td>
<td style="text-align: right;">13.73</td>
<td style="text-align: right;">1.01</td>
<td style="text-align: right;">0.20</td>
<td style="text-align: right;">6.68</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sepse</td>
<td style="text-align: right;">18.18</td>
<td style="text-align: right;">19.61</td>
<td style="text-align: right;">1.10</td>
<td style="text-align: right;">0.27</td>
<td style="text-align: right;">5.43</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sistema gastrointestinal</td>
<td style="text-align: right;">13.64</td>
<td style="text-align: right;">11.76</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.16</td>
<td style="text-align: right;">5.77</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Sistema nervoso central</td>
<td style="text-align: right;">9.09</td>
<td style="text-align: right;">7.84</td>
<td style="text-align: right;">0.85</td>
<td style="text-align: right;">0.11</td>
<td style="text-align: right;">10.14</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Sistema urinário</td>
<td style="text-align: right;">27.27</td>
<td style="text-align: right;">13.73</td>
<td style="text-align: right;">0.43</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">1.80</td>
<td style="text-align: right;">0.19</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="even">
<td style="text-align: left;">Vias áreas inferiores</td>
<td style="text-align: right;">31.82</td>
<td style="text-align: right;">33.33</td>
<td style="text-align: right;">1.07</td>
<td style="text-align: right;">0.33</td>
<td style="text-align: right;">3.72</td>
<td style="text-align: right;">1.00</td>
<td style="text-align: left;">No</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Vias áreas superioras</td>
<td style="text-align: right;">27.27</td>
<td style="text-align: right;">23.53</td>
<td style="text-align: right;">0.82</td>
<td style="text-align: right;">0.23</td>
<td style="text-align: right;">3.15</td>
<td style="text-align: right;">0.77</td>
<td style="text-align: left;">No</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>Odds Ratio: Normal (&gt;= 0.41) vs.&nbsp;Low (&lt; 0.41). 0.43 means que o grupo normal tem menos chances.</p>
<div class="cell">
<details class="code-fold">
<summary>Code</summary>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb70"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb70-1"><a href="#cb70-1"></a>final_results <span class="sc">|&gt;</span></span>
<span id="cb70-2"><a href="#cb70-2"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(Odds_Ratio)) <span class="sc">|&gt;</span> </span>
<span id="cb70-3"><a href="#cb70-3"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> Odds_Ratio, <span class="at">y =</span> <span class="fu">reorder</span>(Infection_Type, Odds_Ratio), <span class="at">color =</span> Significant)) <span class="sc">+</span></span>
<span id="cb70-4"><a href="#cb70-4"></a>  <span class="fu">geom_point</span>(<span class="at">size =</span> <span class="fl">3.5</span>) <span class="sc">+</span></span>
<span id="cb70-5"><a href="#cb70-5"></a>  <span class="fu">geom_errorbar</span>(<span class="fu">aes</span>(<span class="at">xmin =</span> conf.low, <span class="at">xmax =</span> conf.high), <span class="at">width =</span> <span class="fl">0.3</span>, <span class="at">linewidth =</span> <span class="fl">0.8</span>) <span class="sc">+</span></span>
<span id="cb70-6"><a href="#cb70-6"></a>  <span class="fu">geom_vline</span>(<span class="at">xintercept =</span> <span class="dv">1</span>, <span class="at">linetype =</span> <span class="st">"dashed"</span>, <span class="at">color =</span> <span class="st">"gray40"</span>, <span class="at">linewidth =</span> <span class="dv">1</span>) <span class="sc">+</span></span>
<span id="cb70-7"><a href="#cb70-7"></a>  <span class="fu">scale_x_log10</span>() <span class="sc">+</span> </span>
<span id="cb70-8"><a href="#cb70-8"></a>  <span class="fu">scale_color_manual</span>(<span class="at">values =</span> <span class="fu">c</span>(<span class="st">"Yes"</span> <span class="ot">=</span> <span class="st">"#D55E00"</span>, <span class="st">"No"</span> <span class="ot">=</span> <span class="st">"gray60"</span>)) <span class="sc">+</span></span>
<span id="cb70-9"><a href="#cb70-9"></a>  <span class="fu">labs</span>(</span>
<span id="cb70-10"><a href="#cb70-10"></a>    <span class="at">title =</span> <span class="st">"Clinical Impact of Low ELPT (&lt; 0.41 g/dL)"</span>,</span>
<span id="cb70-11"><a href="#cb70-11"></a>    <span class="at">subtitle =</span> <span class="st">"Odds Ratio of Infection Risk (High Risk vs. Low Risk Group)"</span>,</span>
<span id="cb70-12"><a href="#cb70-12"></a>    <span class="at">x =</span> <span class="st">"Odds Ratio (Log Scale) </span><span class="sc">\n</span><span class="st"> &gt;1 indicates higher risk in Low ELPT group"</span>,</span>
<span id="cb70-13"><a href="#cb70-13"></a>    <span class="at">y =</span> <span class="cn">NULL</span>,</span>
<span id="cb70-14"><a href="#cb70-14"></a>    <span class="at">color =</span> <span class="st">"Significant (p &lt; 0.05)?"</span></span>
<span id="cb70-15"><a href="#cb70-15"></a>  )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</details>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="respostas_elpt_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="768"></p>
</figure>
</div>
</div>
</div>
<section id="clinical-validation-association-with-infection-history-elpt" class="level3">
<h3 class="anchored" data-anchor-id="clinical-validation-association-with-infection-history-elpt">Clinical Validation: Association with Infection History (ELPT)</h3>
<p>To determine if the ELPT cutoff (<strong>0.410</strong>) translates into a functional clinical marker, we assessed whether patients falling below this threshold exhibited a higher prevalence of infections compared to those above it.</p>
<ul>
<li><p><strong>Methodology:</strong> Patients were stratified into “High Risk” (ELPT &lt; 0.410) and “Low Risk” (ELPT ≥ 0.410) cohorts. We calculated the Prevalence Rate (%) and Odds Ratio (OR) for seven specific infection types using Fisher’s Exact Test.</p></li>
<li><p><strong>Results:</strong></p>
<ul>
<li><strong>Absence of Phenotypic Correlation:</strong> Unlike the PROTF marker, the ELPT cutoff did not demonstrate a statistically significant association with any specific infection type. P-values for all categories exceeded the significance threshold (<span class="math inline">\(p &gt; 0.05\)</span>).</li>
<li><strong>Uniform Infection Rates:</strong> Infection rates were remarkably similar between the high-risk and low-risk groups across most categories. For example, <strong>Sepsis</strong> prevalence was nearly identical (18.18% in the Low ELPT group vs.&nbsp;19.61% in the Normal ELPT group, <span class="math inline">\(p = 1.00\)</span>).</li>
<li><strong>Urinary Tract Trend:</strong> A non-significant trend was observed for <strong>Urinary System Infections</strong>, which were more frequent in the “High Risk” group (27.27%) compared to the “Low Risk” group (13.73%). However, this difference did not reach statistical significance (<span class="math inline">\(p = 0.19\)</span>).</li>
</ul></li>
</ul>
<p><strong>Conclusion:</strong> While the ELPT cutoff of 0.410 is statistically valid for screening IgG deficiency (as shown in the ROC analysis), it does not appear to independently stratify patients by specific infectious history in this dataset. This suggests that ELPT should be utilized primarily as a biochemical screening tool for IgG levels rather than a direct predictor of clinical infection phenotypes.</p>
</section>
</section>
</section>
<section id="methodology-references" class="level1">
<h1>Methodology &amp; References</h1>
<p>All analyses were conducted using the <code>R</code> language and environment for statistical computing (R Core Team, 2025). Data manipulation and string processing were performed using <code>dplyr</code> (Wickham et al., 2023), <code>tidyr</code> (Wickham et al., 2024), and <code>stringr</code> (Wickham, 2023). Temporal data were handled with <code>lubridate</code> (Grolemund &amp; Wickham, 2011).</p>
<p>To date, the study has focused on data cleaning, feature engineering, and advanced visualization using <code>ggplot2</code> (Wickham, 2016). A key objective was the identification of biological cutoff points for ELPT where existing references were unknown or required validation. To achieve this, we utilized a two-step modeling approach:</p>
<ol type="1">
<li><strong>Reference Interval Modeling:</strong> We established biological baselines by calculating the mean and standard deviation (± 2 SD) of the “Normal” IgG cohort, treating this group as a stable physiological standard.</li>
<li><strong>Threshold Discovery via Segmented Regression:</strong> To identify the specific IgG level at which ELPT stabilizes, we implemented segmented (broken-stick) regression (Muggeo, 2008). This allowed us to mathematically determine the “inflection point” between the rising deficient phase and the steady-state phase.</li>
</ol>
<p>Statistical significance of the observed slopes and the fit of the resulting models were verified using tidied coefficients extracted via <code>broom</code> (Robinson et al., 2024).</p>
<!-- In the next steps, we plan to expand these associations using generalized linear models (GLMs - McCullagh & Nelder, 1989) and generalized additive models (GAMs - Hastie & Tibshirani, 1990; Wood, 2017) to account for potential non-linear effects across the broader dataset. -->
<section id="references" class="level2">
<h2 class="anchored" data-anchor-id="references">References</h2>
<blockquote class="blockquote">
<p>R Core Team (2025). <em>R: A Language and Environment for Statistical Computing</em>. R Foundation for Statistical Computing, Vienna, Austria. <a href="https://www.R-project.org/" class="uri">https://www.R-project.org/</a>.</p>
<p>Wickham, H. (2016). <em>ggplot2: Elegant Graphics for Data Analysis</em>. Springer-Verlag New York.</p>
<p>Wickham, H., François, R., Henry, L., Müller, K., &amp; Vaughan, D. (2023). <em>dplyr: A Grammar of Data Manipulation</em>. R package version 1.1.4.</p>
<p>Wickham, H., Vaughan, D., &amp; Girlich, M. (2024). <em>tidyr: Tidy Messy Data</em>. R package version 1.3.1.</p>
<p>Wickham, H. (2023). <em>stringr: Simple, Consistent Wrappers for Common String Operations</em>. R package version 1.5.1.</p>
<p>Robinson, D., Hayes, A., &amp; Couch, S. (2024). <em>broom: Glance, Tidy, and Augment Regression Models</em>. R package version 1.0.6.</p>
<p>Muggeo, V. M. R. (2008). <em>segmented: an R Package to Fit Regression Models with Broken-Line Relationships</em>. R News, 8/1, 20-25.</p>
<p>Garrett Grolemund, Hadley Wickham (2011). <em>Dates and Times Made Easy with lubridate</em>. Journal of Statistical Software, 40(3), 1-25. <!-- > --> <!-- > McCullagh, P., & Nelder, J. A. (1989). *Generalized Linear Models* (2nd ed.). Chapman & Hall. --> <!-- > --> <!-- > Hastie, T., & Tibshirani, R. (1990). *Generalized Additive Models*. Chapman & Hall. --> <!-- > --> <!-- > Wood, S. N. (2017). *Generalized Additive Models: An Introduction with R* (2nd ed.). CRC Press. --></p>
</blockquote>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>