---
title: A standard multinomial GLMM with random correlated intercepts
author: Henrique Laureano (.github.io)
date: "*Last modification on* `r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r loading}
source('functions.R')
## install.packages('pacman')
pacman::p_load(Matrix, mvtnorm, mc2d, furrr, TMB, tictoc)
future::plan(multicore);TMB::openmp(11)

J <- 3e4
Z <- Matrix::bdiag(replicate(J, rep(1, 2), simplify=FALSE))
U <- matrix(0, nrow=J, ncol=2)
```

## easy data

```{r easy_data}
beta.easy <- c(1, 0.75) ## what makes it easy is the beta's choice
Sigma.0 <- matrix(c(1.0, 0.25, 0.25, 0.5), nrow=2, ncol=2)
## ch0l(Sigma.0) ## checking it positive-definiteness
set.seed(1237)
y.0 <- datasimu(
    J=J, beta=beta.easy, Sigma=Sigma.0
)
prop.table(colSums(y.0))
```

## model 0

> even with an "easy" dataset, i.e. with a good occurrence frequency in
> all multinomial classes, the model doesn't converge well - in this
> first moment I need to be able to get the "random" components in
> "sdreport()". Initial guesses at zero don't work well, so let's start
> with a GLM. If it is difficult now imagine later...


```{r m0,cache=TRUE,error=TRUE}
dll <- 'GLMM';TMB::compile(paste0(dll, '.cpp'))

checkDLL(dll)
obj0 <- TMB::MakeADFun(data=list(Y=y.0, Z=Z),
                       parameters=list(
                           beta1=0,
                           beta2=0,
                           logs2=c(log(0.1), log(0.1)),
                           rhoZ=atanh( 0.05/(sqrt(0.1)*sqrt(0.1)) ),
                           U=U),
                       DLL=dll,
                       random='U', hessia=TRUE, silent=TRUE)
tictoc::tic()
opt0 <- nlminb(obj0$par,
               obj0$fn,
               obj0$gr)
tictoc::toc()
```

```{r m0_sdr,cache=TRUE,error=TRUE}
tictoc::tic()
sdr0 <- sdreport(obj0)
tictoc::toc()
```

```{r m0_results,cache=TRUE,error=TRUE}
opt0
summary(sdr0, select='fixed')
summary(sdr0, select='report')
obj0$report()
nrow(summary(sdr0, select='random'))
cbind(
    1:20,
    summary(sdr0, select='random')[1:20, ], 
    summary(sdr0, select='random')[30001:30020, ]
)
```

```{r v2m0,cache=TRUE,error=TRUE}
v2dll <- 'v2GLMM';TMB::compile(paste0(v2dll, '.cpp'))

checkDLL(v2dll)
v2obj0 <- TMB::MakeADFun(data=list(Y=y.0, Z=Z),
                         parameters=list(
                             beta1=0,
                             beta2=0,
                             logs2=c(log(0.1), log(0.1)),
                             rhoZ=atanh( 0.05/(sqrt(0.1)*sqrt(0.1)) ),
                             U=U),
                         DLL=v2dll,
                         random='U', hessia=TRUE, silent=TRUE)
tictoc::tic()
v2opt0 <- nlminb(v2obj0$par,
                 v2obj0$fn,
                 v2obj0$gr)
tictoc::toc()
```

```{r v2m0_sdr,cache=TRUE,error=TRUE}
tictoc::tic()
v2sdr0 <- sdreport(v2obj0)
tictoc::toc()
```

```{r v2m0_results,cache=TRUE,error=TRUE}
v2opt0
summary(v2sdr0, select='fixed')
summary(v2sdr0, select='report')
v2obj0$report()
nrow(summary(v2sdr0, select='random'))
cbind(
    1:20,
    summary(v2sdr0, select='random')[1:20, ], 
    summary(v2sdr0, select='random')[30001:30020, ]
)
```
