---
title: A standard multinomial GLMM with random common intercept
author: Henrique Laureano (.github.io)
date: "*Last modification on* `r Sys.time()`"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: show
---

```{r loading}
source('functions.R')

## install.packages('pacman')
pacman::p_load(Matrix, mvtnorm, mc2d, ## rmultinomial()
               furrr, ## future + purrr
               TMB, tictoc, tidyverse ## ggplot2() + dplyr()
               )

future::plan(multicore);TMB::openmp(11)
```

```{r data}
J <- 250
cs <- 10
beta.mcie <- c(beta1=0.85, beta2=1.25)
sd <- sqrt(0.25)

set.seed(0858)
y <- datasimu.l1(J=J, cs=cs, beta=beta.mcie, sd=sd)
prop.table(colSums(y))

uniDLL <- 'uniGLMM';invisible(TMB::compile(paste0(uniDLL, '.cpp')))
checkDLL(uniDLL)

Z <- modelZ(J=J, cs=cs)
u <- numeric(J)

obj <- TMB::MakeADFun(data=list(Y=y, Z=Z),
                      parameters=list(beta1=beta.mcie['beta1'],
                                      beta2=beta.mcie['beta2'],
                                      logsd=log(sd),
                                      u=u),
                      DLL=uniDLL, ## ----------------------------------
                      random='u', hessia=TRUE, silent=TRUE)
opt <- with(obj,
            nlminb(par, fn, gr))

bind_cols(
    bind_rows(
        opt$par, c(beta.mcie, logsd=log(sd))
    ),
    label=c('model', 'data')
)
sdr <- sdreport(obj)
summary(sdr, select='fixed')
summary(sdr, select='report')
summary(summary(sdr, select='random'))

prof.beta1 <- TMB::tmbprofile(obj, name='beta1', trace=FALSE)

prof.beta2 <- TMB::tmbprofile(obj, name='beta2', trace=FALSE)
prof.logsd <- TMB::tmbprofile(obj, name='logsd', trace=FALSE)
```

```{r compApp,error=TRUE}
v2dll <- 'v2GLMM';invisible(TMB::compile(paste0(v2dll, '.cpp')))
v3dll <- 'v3GLMM';invisible(TMB::compile(paste0(v3dll, '.cpp')))

checkDLL(v2dll)
v2obj <- TMB::MakeADFun(data=list(Y=y.mcie10, Z=Z10),
                        parameters=list(beta1=beta.mcie['beta1'],
                                        beta2=beta.mcie['beta2'],
                                        logs2=log(diag(Sigma.mcie)),
                                        rhoZ =atanh(-0.25),
                                        U    =U),
                        DLL=v2dll, ## ----------------------------------
                        random='U', hessia=TRUE, silent=TRUE)
checkDLL(v3dll)
v3obj <- TMB::MakeADFun(data=list(Y=y.mcie10, Z=Z10),
                        parameters=list(beta1=beta.mcie['beta1'],
                                        beta2=beta.mcie['beta2'],
                                        logs2=log(diag(Sigma.mcie)),
                                        rhoZ =atanh(-0.25),
                                        U    =U),
                        DLL=v3dll, ## ----------------------------------
                        random='U', hessia=TRUE, silent=TRUE)
v2obj$fn(v2obj$par)
v3obj$fn(v3obj$par)

v2opt <- with(v2obj, nlminb(par, fn, gr))
v3opt <- with(v3obj, nlminb(par, fn, gr))

v2opt$par
v3opt$par
```

The v3 model is the one were we sum the MVNORM() object. The code above
show us that the correct written is with the minus sign inside the nll
-=.
