---
title: "multiGLMM: a multinomial GLMM 4 clustered competing risks data"
author: "[Henrique Ap. Laureano](http://www.leg.ufpr.br/~henrique)"
date: "*Last modification on* `r Sys.time()`"
include-before:
  - '\(\newcommand{\bm}[1]{\boldsymbol{\mathbf{#1}}}\)'
output:
  html_document:
    toc: true
    toc_float: true
    css: font_size.css
    code_folding: show
---

```{r, echo=FALSE}
library(knitr)
htmltools::img(src = image_uri("logo_leg.jpg"),
               alt = 'logo',
               style = 'position:absolute; top:0; right:0;
                        padding:10px; width:175px;')
options(width = 100)
opts_chunk$set(fig.path = "imultiglmm/",
               cache = TRUE,
               cache.path = "cmultiglmm/",
               ## warning = FALSE,
               comment = NA,
               prompt = FALSE)
```

```{r packages}
pacman::p_load(tidyverse, ## pipes, select()
               TMB, ## template model builder
               Matrix, ## bdiag()
               tmbstan, ## MCMC samp. from TMB model object using Stan
               patchwork)
## why not library()?
## with p_load(), if the package isn't installed,
## install_packages() is automatically loaded
```

## simulating some data

```
times: equally spaced grid from 30 to 80 years old
```

```{r datasimu}
datasimu <- function(J, from = 30, to =  79.5, by = 0.5, delta = 80,
                     beta = c(-2, -1.5), gamma = c(1.2, 1), w = c(3, 5),
                     S = matrix(c(1.0, 0.4, 0.5, 0.4,
                                  0.4, 1.0, 0.4, 0.3,
                                  0.5, 0.4, 1.0, 0.4,
                                  0.4, 0.3, 0.4, 1.0), 4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    risk1 <- exp(beta[1] + B[ , 1])
    risk2 <- exp(beta[2] + B[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - B[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - B[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
```

```{r usingdatasimu}
J <- 1000
set.seed(201220)
df <- datasimu(J = J)
df %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
```

```{r tmb1, warning=FALSE}
## compile("multiGLMM.cpp")
dyn.load(dynlib("multiGLMM"))
openmp(n = 10)
tmbdata <- list(Y = as.matrix(df %>% select(y1:y3)),
                Z = bdiag(replicate(J, rep(1, 2), simplify = FALSE)),
                T = df$t,
                delta = 80)
## ---------------------------------------------------------------------
tmbpars <- list(beta1 = -2,
                beta2 = -1.5,
                gama1 = 1.2,
                gama2 = 1,
                w1 = 3,
                w2 = 5,
                R = matrix(0, nrow = J, ncol = 4),
                sigma = rep(1, 4),
                theta = rep(0.1, 6))
## ---------------------------------------------------------------------
objstan <- MakeADFun(data = tmbdata,
                     parameters = tmbpars,
                     DLL = "multiGLMM",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
objstan$fn()
## ---------------------------------------------------------------------
tictoc::tic()
optstan <- nlminb(objstan$par, objstan$fn, objstan$gr)
tictoc::toc()
```

```{r tmbstan1}
## FOR SOME WEIRD REASON I CAN NOT PARALLELIZE THE MODEL SAMPLING
## cores <- parallel::detectCores()
## options(mc.cores = cores)
## rstan_options(auto_write = TRUE)
## ---------------------------------------------------------------------
fitstan <- tmbstan(objstan,
                   chains = 2,
                   iter = 4000,
                   lower = c(rep(-Inf, 6), rep(1e-4, 4), rep(-Inf, 6)),
                   upper = rep(Inf, 16),
                   control = list(max_treedepth = 15)
                   )
```

```{r}
plot(fitstan, pars = names(objstan$par))
## ---------------------------------------------------------------------
traceplot(fitstan, pars = names(objstan$par))
```
