---
title: "multiGLMM: a multinomial GLMM 4 clustered competing risks data"
author: "[Henrique Ap. Laureano](http://www.leg.ufpr.br/~henrique)"
date: "*Last modification on* `r Sys.time()`"
include-before:
  - '\(\newcommand{\bm}[1]{\boldsymbol{\mathbf{#1}}}\)'
output:
  html_document:
    toc: true
    toc_float: true
    css: font_size.css
    code_folding: show
---

```{r, echo=FALSE}
library(knitr)
htmltools::img(src = image_uri("logo_leg.jpg"),
               alt = 'logo',
               style = 'position:absolute; top:0; right:0;
                        padding:10px; width:175px;')
options(width = 100)
opts_chunk$set(fig.path = "iprocess/",
               cache = TRUE,
               cache.path = "cprocess/",
               ## warning = FALSE,
               comment = NA,
               prompt = FALSE)
```

```{r packages}
pacman::p_load(tidyverse, ## pipes, select()
               TMB, ## template model builder
               Matrix, ## bdiag()
               tmbstan, ## MCMC samp. from TMB model object using Stan
               patchwork)
## why not library()?
## with p_load(), if the package isn't installed,
## install_packages() is automatically loaded
```

## starting from the bottom

## just fixed effects

```
times: equally spaced grid from 30 to 80 years old
```

```{r datasimuF}
datasimuF <- function(J, from = 30, to =  79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    risk1 <- exp(beta[1])
    risk2 <- exp(beta[2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
tmbparsF <- list(beta1 = -2,
                 beta2 = -1.5,
                 gama1 = 1.2,
                 gama2 = 1,
                 w1 = 3,
                 w2 = 5)
```

```{r fixedmodels}
## compile("SCHEIKEfixed.cpp")
dyn.load(dynlib("SCHEIKEfixed"))
openmp(n = 10)
## ---------------------------------------------------------------------
dfF <- datasimuF(J = 1e3)
dfF %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdataF <- list(Y = as.matrix(dfF %>% select(y1:y3)),
                 T = dfF$t,
                 delta = 80)
objF <- MakeADFun(data = tmbdataF,
                  parameters = tmbparsF,
                  DLL = "SCHEIKEfixed",
                  hessian = TRUE, silent = TRUE)
objF$fn()
tictoc::tic()
optF <- nlminb(objF$par, objF$fn, objF$gr)
tictoc::toc()
sdrF <- sdreport(objF)
## ---------------------------------------------------------------------
dfF2 <- datasimuF(J = 5e3)
dfF2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdataF2 <- list(Y = as.matrix(dfF2 %>% select(y1:y3)),
                  T = dfF2$t,
                  delta = 80)
objF2 <- MakeADFun(data = tmbdataF2,
                   parameters = tmbparsF,
                   DLL = "SCHEIKEfixed",
                   hessian = TRUE, silent = TRUE)
objF2$fn()
tictoc::tic()
optF2 <- nlminb(objF2$par, objF2$fn, objF2$gr)
tictoc::toc()
sdrF2 <- sdreport(objF2)
## ---------------------------------------------------------------------
dfF3 <- datasimuF(J = 1e4)
dfF3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdataF3 <- list(Y = as.matrix(dfF3 %>% select(y1:y3)),
                  T = dfF3$t,
                  delta = 80)
objF3 <- MakeADFun(data = tmbdataF3,
                   parameters = tmbparsF,
                   DLL = "SCHEIKEfixed",
                   hessian = TRUE, silent = TRUE)
objF3$fn()
tictoc::tic()
optF3 <- nlminb(objF3$par, objF3$fn, objF3$gr)
tictoc::toc()
sdrF3 <- sdreport(objF3)
## ---------------------------------------------------------------------
dfF4 <- datasimuF(J = 25e3)
dfF4 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdataF4 <- list(Y = as.matrix(dfF4 %>% select(y1:y3)),
                  T = dfF4$t,
                  delta = 80)
objF4 <- MakeADFun(data = tmbdataF4,
                   parameters = tmbparsF,
                   DLL = "SCHEIKEfixed",
                   hessian = TRUE, silent = TRUE)
objF4$fn()
tictoc::tic()
optF4 <- nlminb(objF4$par, objF4$fn, objF4$gr)
tictoc::toc()
sdrF4 <- sdreport(objF4)
## ---------------------------------------------------------------------
dfF5 <- datasimuF(J = 50e3)
dfF5 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdataF5 <- list(Y = as.matrix(dfF5 %>% select(y1:y3)),
                  T = dfF5$t,
                  delta = 80)
objF5 <- MakeADFun(data = tmbdataF5,
                   parameters = tmbparsF,
                   DLL = "SCHEIKEfixed",
                   hessian = TRUE, silent = TRUE)
objF5$fn()
tictoc::tic()
optF5 <- nlminb(objF5$par, objF5$fn, objF5$gr)
tictoc::toc()
sdrF5 <- sdreport(objF5)
```

```{r fixedsummaries}
## 1e3 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5), summary(sdrF))
## 5e3 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5), summary(sdrF2))
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5), summary(sdrF3))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5), summary(sdrF4))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5), summary(sdrF5))
```

```{r fixedprofiles}
b1F <- tmbprofile(objF5, name = "beta1", trace = FALSE)
b2F <- tmbprofile(objF5, name = "beta2", trace = FALSE)
g1F <- tmbprofile(objF5, name = "gama1", trace = FALSE)
g2F <- tmbprofile(objF5, name = "gama2", trace = FALSE)
w1F <- tmbprofile(objF5, name = "w1", trace = FALSE)
w2F <- tmbprofile(objF5, name = "w2", trace = FALSE)
## ---------------------------------------------------------------------
par(mfrow = c(2, 3), mar =  c(4, 4, 2, 2))
plot(b1F) ; abline(v = -2, lty = 2)
plot(b2F) ; abline(v = -1.5, lty = 2)
plot(g1F) ; abline(v = 1.2, lty = 2)
plot(g2F) ; abline(v = 1, lty = 2)
plot(w1F) ; abline(v = 3, lty = 2)
plot(w2F) ; abline(v = 5, lty = 2)
```

```
remember: this is just one fit. the right thing to do here should be a
simulation study to get the histogram estimates
```

## adding latent structure

### 1

```{r datasimu1}
datasimu1 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(0.5, 0.0,
                                                0.0, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(110137)
df1.1 <- datasimu1(J = 1e4)
df1.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata1.1 <- list(
    Y = as.matrix(df1.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df1.1$t,
    delta = 80)
tmbpars1.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = log(0.5))
## ---------------------------------------------------------------------
set.seed(110208)
df1.2 <- datasimu1(J = 25e3)
df1.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata1.2 <- list(
    Y = as.matrix(df1.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df1.2$t,
    delta = 80)
tmbpars1.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = log(0.5))
## ---------------------------------------------------------------------
set.seed(110246)
df1.3 <- datasimu1(J = 50e3)
df1.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata1.3 <- list(
    Y = as.matrix(df1.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df1.3$t,
    delta = 80)
tmbpars1.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = log(0.5))
```

```{r models_1, error=TRUE, warning=FALSE, dependson="datasimu1"}
## compile("multiGLMM_1.cpp")
dyn.load(dynlib("multiGLMM_1"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_1.1 <- MakeADFun(data = tmbdata1.1,
                   parameters = tmbpars1.1,
                   DLL = "multiGLMM_1",
                   random = "R",
                   hessian = TRUE, silent = TRUE)
obj_1.1$fn()
tictoc::tic()
opt_1.1 <- nlminb(obj_1.1$par, obj_1.1$fn, obj_1.1$gr)
tictoc::toc()
sdr_1.1 <- sdreport(obj_1.1)
## ---------------------------------------------------------------------
obj_1.2 <- MakeADFun(data = tmbdata1.2,
                   parameters = tmbpars1.2,
                   DLL = "multiGLMM_1",
                   random = "R",
                   hessian = TRUE, silent = TRUE)
obj_1.2$fn()
tictoc::tic()
opt_1.2 <- nlminb(obj_1.2$par, obj_1.2$fn, obj_1.2$gr)
tictoc::toc()
sdr_1.2 <- sdreport(obj_1.2)
##----------------------------------------------------------------------
obj_1.3 <- MakeADFun(data = tmbdata1.3,
                     parameters = tmbpars1.3,
                     DLL = "multiGLMM_1",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_1.3$fn()
tictoc::tic()
opt_1.3 <- nlminb(obj_1.3$par, obj_1.3$fn, obj_1.3$gr)
tictoc::toc()
sdr_1.3 <- sdreport(obj_1.3)
```

```{r summaries_1, error=TRUE, dependson="datasimu1"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5)), summary(sdr_1.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5)), summary(sdr_1.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5)), summary(sdr_1.3, "fixed"))
```

### 2

```{r datasimu2}
datasimu2 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(1.0, 0.0,
                                                0.0, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(151340)
df2.1 <- datasimu2(J = 1e4)
df2.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata2.1 <- list(
    Y = as.matrix(df2.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df2.1$t,
    delta = 80)
tmbpars2.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = c(log(1), log(0.5)))
## ---------------------------------------------------------------------
set.seed(151449)
df2.2 <- datasimu2(J = 25e3)
df2.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata2.2 <- list(
    Y = as.matrix(df2.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df2.2$t,
    delta = 80)
tmbpars2.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)))
## ---------------------------------------------------------------------
set.seed(151532)
df2.3 <- datasimu2(J = 50e3)
df2.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata2.3 <- list(
    Y = as.matrix(df2.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df2.3$t,
    delta = 80)
tmbpars2.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)))
```

```{r models_2, error=TRUE, warning=FALSE, dependson="datasimu2"}
## compile("multiGLMM_2.cpp")
dyn.load(dynlib("multiGLMM_2"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_2.1 <- MakeADFun(data = tmbdata2.1,
                     parameters = tmbpars2.1,
                     DLL = "multiGLMM_2",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_2.1$fn()
tictoc::tic()
opt_2.1 <- nlminb(obj_2.1$par, obj_2.1$fn, obj_2.1$gr)
tictoc::toc()
sdr_2.1 <- sdreport(obj_2.1)
## ---------------------------------------------------------------------
obj_2.2 <- MakeADFun(data = tmbdata2.2,
                     parameters = tmbpars2.2,
                     DLL = "multiGLMM_2",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_2.2$fn()
tictoc::tic()
opt_2.2 <- nlminb(obj_2.2$par, obj_2.2$fn, obj_2.2$gr)
tictoc::toc()
sdr_2.2 <- sdreport(obj_2.2)
##----------------------------------------------------------------------
obj_2.3 <- MakeADFun(data = tmbdata2.3,
                     parameters = tmbpars2.3,
                     DLL = "multiGLMM_2",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_2.3$fn()
tictoc::tic()
opt_2.3 <- nlminb(obj_2.3$par, obj_2.3$fn, obj_2.3$gr)
tictoc::toc()
sdr_2.3 <- sdreport(obj_2.3)
```

```{r summaries_2, error=TRUE, dependson="datasimu2"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_2.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_2.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_2.3, "fixed"))
```

### 3

```{r datasimu3}
datasimu3 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(0.5, 0.25,
                                                0.25, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(173612)
df3.1 <- datasimu3(J = 1e4)
df3.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata3.1 <- list(
    Y = as.matrix(df3.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df3.1$t,
    delta = 80)
tmbpars3.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = log(0.5),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(173725)
df3.2 <- datasimu3(J = 25e3)
df3.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata3.2 <- list(
    Y = as.matrix(df3.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df3.2$t,
    delta = 80)
tmbpars3.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = log(0.5),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(173812)
df3.3 <- datasimu3(J = 50e3)
df3.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata3.3 <- list(
    Y = as.matrix(df3.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df3.3$t,
    delta = 80)
tmbpars3.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = log(0.5),
                   rhoZ = atanh(0.25))
```

```{r models_3, error=TRUE, warning=FALSE, dependson="datasimu3"}
## compile("multiGLMM_3.cpp")
dyn.load(dynlib("multiGLMM_3"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_3.1 <- MakeADFun(data = tmbdata3.1,
                     parameters = tmbpars3.1,
                     DLL = "multiGLMM_3",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_3.1$fn()
tictoc::tic()
opt_3.1 <- nlminb(obj_3.1$par, obj_3.1$fn, obj_3.1$gr)
tictoc::toc()
sdr_3.1 <- sdreport(obj_3.1)
## ---------------------------------------------------------------------
obj_3.2 <- MakeADFun(data = tmbdata3.2,
                     parameters = tmbpars3.2,
                     DLL = "multiGLMM_3",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_3.2$fn()
tictoc::tic()
opt_3.2 <- nlminb(obj_3.2$par, obj_3.2$fn, obj_3.2$gr)
tictoc::toc()
sdr_3.2 <- sdreport(obj_3.2)
##----------------------------------------------------------------------
obj_3.3 <- MakeADFun(data = tmbdata3.3,
                     parameters = tmbpars3.3,
                     DLL = "multiGLMM_3",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_3.3$fn()
tictoc::tic()
opt_3.3 <- nlminb(obj_3.3$par, obj_3.3$fn, obj_3.3$gr)
tictoc::toc()
sdr_3.3 <- sdreport(obj_3.3)
```

```{r summaries_3, error=TRUE, dependson="datasimu3"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      summary(sdr_3.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      summary(sdr_3.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      summary(sdr_3.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      opt_3.1$par, ## 1e4 pairs
      opt_3.2$par, ## 25e3
      opt_3.3$par) ## 50e3
```

### 4

```{r datasimu4}
datasimu4 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(1.0, 0.25,
                                                0.25, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(083512)
df4.1 <- datasimu4(J = 1e4)
df4.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata4.1 <- list(
    Y = as.matrix(df4.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df4.1$t,
    delta = 80)
tmbpars4.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = c(log(1), log(0.5)),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(083602)
df4.2 <- datasimu4(J = 25e3)
df4.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata4.2 <- list(
    Y = as.matrix(df4.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df4.2$t,
    delta = 80)
tmbpars4.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(083639)
df4.3 <- datasimu4(J = 50e3)
df4.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata4.3 <- list(
    Y = as.matrix(df4.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df4.3$t,
    delta = 80)
tmbpars4.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)),
                   rhoZ = atanh(0.25))
```

```{r models_4, error=TRUE, warning=FALSE, dependson="datasimu4"}
## compile("multiGLMM_4.cpp")
dyn.load(dynlib("multiGLMM_4"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_4.1 <- MakeADFun(data = tmbdata4.1,
                     parameters = tmbpars4.1,
                     DLL = "multiGLMM_4",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_4.1$fn()
tictoc::tic()
opt_4.1 <- nlminb(obj_4.1$par, obj_4.1$fn, obj_4.1$gr)
tictoc::toc()
sdr_4.1 <- sdreport(obj_4.1)
## ---------------------------------------------------------------------
obj_4.2 <- MakeADFun(data = tmbdata4.2,
                     parameters = tmbpars4.2,
                     DLL = "multiGLMM_4",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_4.2$fn()
tictoc::tic()
opt_4.2 <- nlminb(obj_4.2$par, obj_4.2$fn, obj_4.2$gr)
tictoc::toc()
sdr_4.2 <- sdreport(obj_4.2)
##----------------------------------------------------------------------
obj_4.3 <- MakeADFun(data = tmbdata4.3,
                     parameters = tmbpars4.3,
                     DLL = "multiGLMM_4",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_4.3$fn()
tictoc::tic()
opt_4.3 <- nlminb(obj_4.3$par, obj_4.3$fn, obj_4.3$gr)
tictoc::toc()
sdr_4.3 <- sdreport(obj_4.3)
```

```{r summaries_4, error=TRUE, dependson="datasimu4"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      summary(sdr_4.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      summary(sdr_4.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      summary(sdr_4.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      opt_4.1$par, ## 1e4 pairs
      opt_4.2$par, ## 25e3
      opt_4.3$par) ## 50e3
```

### 5

```{r datasimu5}
datasimu5 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(0.5, 0.0,
                                                0.0, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1])
    risk2 <- exp(beta[2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(132643)
df5.1 <- datasimu5(J = 1e4)
df5.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata5.1 <- list(
    Y = as.matrix(df5.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df5.1$t,
    delta = 80)
tmbpars5.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = log(0.5))
## ---------------------------------------------------------------------
set.seed(132741)
df5.2 <- datasimu5(J = 25e3)
df5.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata5.2 <- list(
    Y = as.matrix(df5.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df5.2$t,
    delta = 80)
tmbpars5.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = log(0.5))
## ---------------------------------------------------------------------
set.seed(132810)
df5.3 <- datasimu5(J = 50e3)
df5.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata5.3 <- list(
    Y = as.matrix(df5.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df5.3$t,
    delta = 80)
tmbpars5.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = log(0.5))
```

```{r models_5, error=TRUE, warning=FALSE, dependson="datasimu5"}
## compile("multiGLMM_5.cpp")
dyn.load(dynlib("multiGLMM_5"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_5.1 <- MakeADFun(data = tmbdata5.1,
                     parameters = tmbpars5.1,
                     DLL = "multiGLMM_5",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_5.1$fn()
tictoc::tic()
opt_5.1 <- nlminb(obj_5.1$par, obj_5.1$fn, obj_5.1$gr)
tictoc::toc()
sdr_5.1 <- sdreport(obj_5.1)
## ---------------------------------------------------------------------
obj_5.2 <- MakeADFun(data = tmbdata5.2,
                     parameters = tmbpars5.2,
                     DLL = "multiGLMM_5",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_5.2$fn()
tictoc::tic()
opt_5.2 <- nlminb(obj_5.2$par, obj_5.2$fn, obj_5.2$gr)
tictoc::toc()
sdr_5.2 <- sdreport(obj_5.2)
##----------------------------------------------------------------------
obj_5.3 <- MakeADFun(data = tmbdata5.3,
                     parameters = tmbpars5.3,
                     DLL = "multiGLMM_5",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_5.3$fn()
tictoc::tic()
opt_5.3 <- nlminb(obj_5.3$par, obj_5.3$fn, obj_5.3$gr)
tictoc::toc()
sdr_5.3 <- sdreport(obj_5.3)
```

```{r summaries_5, error=TRUE, dependson="datasimu5"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5)), summary(sdr_5.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5)), summary(sdr_5.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5)), summary(sdr_5.3, "fixed"))
```

### 6

```{r datasimu6}
datasimu6 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(1.0, 0.0,
                                                0.0, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1])
    risk2 <- exp(beta[2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(150447)
df6.1 <- datasimu6(J = 1e4)
df6.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata6.1 <- list(
    Y = as.matrix(df6.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df6.1$t,
    delta = 80)
tmbpars6.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = c(log(1), log(0.5)))
## ---------------------------------------------------------------------
set.seed(150527)
df6.2 <- datasimu6(J = 25e3)
df6.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata6.2 <- list(
    Y = as.matrix(df6.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df6.2$t,
    delta = 80)
tmbpars6.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)))
## ---------------------------------------------------------------------
set.seed(150611)
df6.3 <- datasimu6(J = 50e3)
df6.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata6.3 <- list(
    Y = as.matrix(df6.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df6.3$t,
    delta = 80)
tmbpars6.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)))
```

```{r models_6, error=TRUE, warning=FALSE, dependson="datasimu6"}
## compile("multiGLMM_6.cpp")
dyn.load(dynlib("multiGLMM_6"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_6.1 <- MakeADFun(data = tmbdata6.1,
                     parameters = tmbpars6.1,
                     DLL = "multiGLMM_6",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_6.1$fn()
tictoc::tic()
opt_6.1 <- nlminb(obj_6.1$par, obj_6.1$fn, obj_6.1$gr)
tictoc::toc()
sdr_6.1 <- sdreport(obj_6.1)
## ---------------------------------------------------------------------
obj_6.2 <- MakeADFun(data = tmbdata6.2,
                     parameters = tmbpars6.2,
                     DLL = "multiGLMM_6",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_6.2$fn()
tictoc::tic()
opt_6.2 <- nlminb(obj_6.2$par, obj_6.2$fn, obj_6.2$gr)
tictoc::toc()
sdr_6.2 <- sdreport(obj_6.2)
##----------------------------------------------------------------------
obj_6.3 <- MakeADFun(data = tmbdata6.3,
                     parameters = tmbpars6.3,
                     DLL = "multiGLMM_6",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_6.3$fn()
tictoc::tic()
opt_6.3 <- nlminb(obj_6.3$par, obj_6.3$fn, obj_6.3$gr)
tictoc::toc()
sdr_6.3 <- sdreport(obj_6.3)
```

```{r summaries_6, error=TRUE, dependson="datasimu6"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_6.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_6.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_6.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      opt_6.1$par, ## 1e4
      opt_6.2$par) ## 25e3
```

### 7

```{r datasimu7}
datasimu7 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(0.5, 0.25,
                                                0.25, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1])
    risk2 <- exp(beta[2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(163308)
df7.1 <- datasimu7(J = 1e4)
df7.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata7.1 <- list(
    Y = as.matrix(df7.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df7.1$t,
    delta = 80)
tmbpars7.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = log(0.5),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(163411)
df7.2 <- datasimu7(J = 25e3)
df7.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata7.2 <- list(
    Y = as.matrix(df7.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df7.2$t,
    delta = 80)
tmbpars7.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = log(0.5),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(163454)
df7.3 <- datasimu7(J = 50e3)
df7.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata7.3 <- list(
    Y = as.matrix(df7.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df7.3$t,
    delta = 80)
tmbpars7.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = log(0.5),
                   rhoZ = atanh(0.25))
```

```{r models_7, error=TRUE, warning=FALSE, dependson="datasimu7"}
## compile("multiGLMM_7.cpp")
dyn.load(dynlib("multiGLMM_7"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_7.1 <- MakeADFun(data = tmbdata7.1,
                     parameters = tmbpars7.1,
                     DLL = "multiGLMM_7",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_7.1$fn()
tictoc::tic()
opt_7.1 <- nlminb(obj_7.1$par, obj_7.1$fn, obj_7.1$gr)
tictoc::toc()
sdr_7.1 <- sdreport(obj_7.1)
## ---------------------------------------------------------------------
obj_7.2 <- MakeADFun(data = tmbdata7.2,
                     parameters = tmbpars7.2,
                     DLL = "multiGLMM_7",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_7.2$fn()
tictoc::tic()
opt_7.2 <- nlminb(obj_7.2$par, obj_7.2$fn, obj_7.2$gr)
tictoc::toc()
sdr_7.2 <- sdreport(obj_7.2)
##----------------------------------------------------------------------
obj_7.3 <- MakeADFun(data = tmbdata7.3,
                     parameters = tmbpars7.3,
                     DLL = "multiGLMM_7",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_7.3$fn()
tictoc::tic()
opt_7.3 <- nlminb(obj_7.3$par, obj_7.3$fn, obj_7.3$gr)
tictoc::toc()
sdr_7.3 <- sdreport(obj_7.3)
```

```{r summaries_7, error=TRUE, dependson="datasimu7"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      summary(sdr_7.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      summary(sdr_7.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      summary(sdr_7.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(0.5), atanh(0.25)),
      opt_7.1$par, ## 1e4 pairs
      opt_7.2$par, ## 25e3
      opt_7.3$par) ## 50e3
```

### 8

```{r datasimu8}
datasimu8 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(1.0, 0.25,
                                                0.25, 0.5), 2, 2))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1])
    risk2 <- exp(beta[2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 1])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 2])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(174316)
df8.1 <- datasimu8(J = 1e4)
df8.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata8.1 <- list(
    Y = as.matrix(df8.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df8.1$t,
    delta = 80)
tmbpars8.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 2),
                   logs2 = c(log(1), log(0.5)),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(174355)
df8.2 <- datasimu8(J = 25e3)
df8.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata8.2 <- list(
    Y = as.matrix(df8.2 %>% select(y1:y3)),
    Z = bdiag(replicate(25e3, rep(1, 2), simplify = FALSE)),
    T = df8.2$t,
    delta = 80)
tmbpars8.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 25e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)),
                   rhoZ = atanh(0.25))
## ---------------------------------------------------------------------
set.seed(174433)
df8.3 <- datasimu8(J = 50e3)
df8.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata8.3 <- list(
    Y = as.matrix(df8.3 %>% select(y1:y3)),
    Z = bdiag(replicate(50e3, rep(1, 2), simplify = FALSE)),
    T = df8.3$t,
    delta = 80)
tmbpars8.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 50e3, ncol = 2),
                   logs2 = c(log(1), log(0.5)),
                   rhoZ = atanh(0.25))
```

```{r models_8, error=TRUE, warning=FALSE, dependson="datasimu8"}
## compile("multiGLMM_8.cpp")
dyn.load(dynlib("multiGLMM_8"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_8.1 <- MakeADFun(data = tmbdata8.1,
                     parameters = tmbpars8.1,
                     DLL = "multiGLMM_8",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_8.1$fn()
tictoc::tic()
opt_8.1 <- nlminb(obj_8.1$par, obj_8.1$fn, obj_8.1$gr)
tictoc::toc()
sdr_8.1 <- sdreport(obj_8.1)
## ---------------------------------------------------------------------
obj_8.2 <- MakeADFun(data = tmbdata8.2,
                     parameters = tmbpars8.2,
                     DLL = "multiGLMM_8",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_8.2$fn()
tictoc::tic()
opt_8.2 <- nlminb(obj_8.2$par, obj_8.2$fn, obj_8.2$gr)
tictoc::toc()
sdr_8.2 <- sdreport(obj_8.2)
##----------------------------------------------------------------------
obj_8.3 <- MakeADFun(data = tmbdata8.3,
                     parameters = tmbpars8.3,
                     DLL = "multiGLMM_8",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_8.3$fn()
tictoc::tic()
opt_8.3 <- nlminb(obj_8.3$par, obj_8.3$fn, obj_8.3$gr)
tictoc::toc()
sdr_8.3 <- sdreport(obj_8.3)
```

```{r summaries_8, error=TRUE, dependson="datasimu8"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      summary(sdr_8.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      summary(sdr_8.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      summary(sdr_8.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.25)),
      opt_8.1$par, ## 1e4 pairs
      opt_8.2$par, ## 25e3
      opt_8.3$par) ## 50e3
```

### 9

```{r datasimu9}
datasimu9 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                      beta = c(-2, -1.5), gamma = c(1.2, 1),
                      w = c(3, 5), S = matrix(c(1.0, 0.0, 0.0, 0.0,
                                                0.0, 1.0, 0.0, 0.0,
                                                0.0, 0.0, 0.5, 0.0,
                                                0.0, 0.0, 0.0, 0.5),
                                              4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension

B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(111706)
df9.1 <- datasimu9(J = 1e4)
df9.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata9.1 <- list(
    Y = as.matrix(df9.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df9.1$t,
    delta = 80)
tmbpars9.1 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 1e4, ncol = 4),
                   logs2 = c(log(1), log(0.5)))
## ---------------------------------------------------------------------
set.seed(111752)
df9.2 <- datasimu9(J = 2e4)
df9.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata9.2 <- list(
    Y = as.matrix(df9.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df9.2$t,
    delta = 80)
tmbpars9.2 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 2e4, ncol = 4),
                   logs2 = c(log(1), log(0.5)))
## ---------------------------------------------------------------------
set.seed(111824)
df9.3 <- datasimu9(J = 4e4)
df9.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata9.3 <- list(
    Y = as.matrix(df9.3 %>% select(y1:y3)),
    Z = bdiag(replicate(4e4, rep(1, 2), simplify = FALSE)),
    T = df9.3$t,
    delta = 80)
tmbpars9.3 <- list(beta1 = -2,
                   beta2 = -1.5,
                   gama1 = 1.2,
                   gama2 = 1,
                   w1 = 3,
                   w2 = 5,
                   R = matrix(0, nrow = 4e4, ncol = 4),
                   logs2 = c(log(1), log(0.5)))
```

```{r models_9, error=TRUE, warning=FALSE, dependson="datasimu9"}
## compile("multiGLMM_9.cpp")
dyn.load(dynlib("multiGLMM_9"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_9.1 <- MakeADFun(data = tmbdata9.1,
                     parameters = tmbpars9.1,
                     DLL = "multiGLMM_9",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_9.1$fn()
tictoc::tic()
opt_9.1 <- nlminb(obj_9.1$par, obj_9.1$fn, obj_9.1$gr)
tictoc::toc()
sdr_9.1 <- sdreport(obj_9.1)
## ---------------------------------------------------------------------
obj_9.2 <- MakeADFun(data = tmbdata9.2,
                     parameters = tmbpars9.2,
                     DLL = "multiGLMM_9",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_9.2$fn()
tictoc::tic()
opt_9.2 <- nlminb(obj_9.2$par, obj_9.2$fn, obj_9.2$gr)
tictoc::toc()
sdr_9.2 <- sdreport(obj_9.2)
##----------------------------------------------------------------------
obj_9.3 <- MakeADFun(data = tmbdata9.3,
                     parameters = tmbpars9.3,
                     DLL = "multiGLMM_9",
                     random = "R",
                     hessian = TRUE, silent = TRUE)
obj_9.3$fn()
tictoc::tic()
opt_9.3 <- nlminb(obj_9.3$par, obj_9.3$fn, obj_9.3$gr)
tictoc::toc()
sdr_9.3 <- sdreport(obj_9.3)
```

```{r summaries_9, error=TRUE, dependson="datasimu9"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_9.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_9.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5)),
      summary(sdr_9.3, "fixed"))
```

### 10

```{r datasimu10}
datasimu10 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                       beta = c(-2, -1.5), gamma = c(1.2, 1),
                       w = c(3, 5), S = matrix(c(1.0, 0.0, 0.0, 0.0,
                                                 0.0, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 0.5, 0.0,
                                                 0.0, 0.0, 0.0, 0.5),
                                               4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(132428)
df10.1 <- datasimu10(J = 1e4)
df10.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata10.1 <- list(
    Y = as.matrix(df10.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df10.1$t,
    delta = 80)
tmbpars10.1 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 1e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)))
## ---------------------------------------------------------------------
set.seed(132536)
df10.2 <- datasimu10(J = 2e4)
df10.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata10.2 <- list(
    Y = as.matrix(df10.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df10.2$t,
    delta = 80)
tmbpars10.2 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 2e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)))
## ---------------------------------------------------------------------
set.seed(132720)
df10.3 <- datasimu10(J = 4e4)
df10.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata10.3 <- list(
    Y = as.matrix(df10.3 %>% select(y1:y3)),
    Z = bdiag(replicate(4e4, rep(1, 2), simplify = FALSE)),
    T = df10.3$t,
    delta = 80)
tmbpars10.3 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 4e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)))
```

```{r models_10, error=TRUE, warning=FALSE, dependson="datasimu10"}
## compile("multiGLMM_10.cpp")
dyn.load(dynlib("multiGLMM_10"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_10.1 <- MakeADFun(data = tmbdata10.1,
                      parameters = tmbpars10.1,
                      DLL = "multiGLMM_10",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_10.1$fn()
tictoc::tic()
opt_10.1 <- nlminb(obj_10.1$par, obj_10.1$fn, obj_10.1$gr)
tictoc::toc()
sdr_10.1 <- sdreport(obj_10.1)
## ---------------------------------------------------------------------
obj_10.2 <- MakeADFun(data = tmbdata10.2,
                      parameters = tmbpars10.2,
                      DLL = "multiGLMM_10",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_10.2$fn()
tictoc::tic()
opt_10.2 <- nlminb(obj_10.2$par, obj_10.2$fn, obj_10.2$gr)
tictoc::toc()
sdr_10.2 <- sdreport(obj_10.2)
##----------------------------------------------------------------------
obj_10.3 <- MakeADFun(data = tmbdata10.3,
                      parameters = tmbpars10.3,
                      DLL = "multiGLMM_10",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_10.3$fn()
tictoc::tic()
opt_10.3 <- nlminb(obj_10.3$par, obj_10.3$fn, obj_10.3$gr)
tictoc::toc()
sdr_10.3 <- sdreport(obj_10.3)
```

```{r summaries_10, error=TRUE, dependson="datasimu10"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(1), log(0.5), log(0.5)),
      summary(sdr_10.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(1), log(0.5), log(0.5)),
      summary(sdr_10.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(1), log(0.5), log(0.5)),
      summary(sdr_10.3, "fixed"))
```

### 11

```{r datasimu11}
datasimu11 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                       beta = c(-2, -1.5), gamma = c(1.2, 1),
                       w = c(3, 5), S = matrix(c(1.0, 0.5, 0.0, 0.0,
                                                 0.5, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 0.5, 0.0,
                                                 0.0, 0.0, 0.0, 0.5),
                                               4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(164922)
df11.1 <- datasimu11(J = 1e4)
df11.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata11.1 <- list(
    Y = as.matrix(df11.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df11.1$t,
    delta = 80)
tmbpars11.1 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 1e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = atanh(0.5))
## ---------------------------------------------------------------------
set.seed(165023)
df11.2 <- datasimu11(J = 2e4)
df11.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata11.2 <- list(
    Y = as.matrix(df11.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df11.2$t,
    delta = 80)
tmbpars11.2 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 2e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = atanh(0.5))
## ---------------------------------------------------------------------
set.seed(165101)
df11.3 <- datasimu11(J = 3e4)
df11.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata11.3 <- list(
    Y = as.matrix(df11.3 %>% select(y1:y3)),
    Z = bdiag(replicate(3e4, rep(1, 2), simplify = FALSE)),
    T = df11.3$t,
    delta = 80)
tmbpars11.3 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 3e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = atanh(0.5))
```

```{r models_11, error=TRUE, warning=FALSE, dependson="datasimu11"}
## compile("multiGLMM_11.cpp")
dyn.load(dynlib("multiGLMM_11"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_11.1 <- MakeADFun(data = tmbdata11.1,
                      parameters = tmbpars11.1,
                      DLL = "multiGLMM_11",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_11.1$fn()
tictoc::tic()
opt_11.1 <- nlminb(obj_11.1$par, obj_11.1$fn, obj_11.1$gr)
tictoc::toc()
sdr_11.1 <- sdreport(obj_11.1)
## ---------------------------------------------------------------------
obj_11.2 <- MakeADFun(data = tmbdata11.2,
                      parameters = tmbpars11.2,
                      DLL = "multiGLMM_11",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_11.2$fn()
tictoc::tic()
opt_11.2 <- nlminb(obj_11.2$par, obj_11.2$fn, obj_11.2$gr)
tictoc::toc()
sdr_11.2 <- sdreport(obj_11.2)
##----------------------------------------------------------------------
obj_11.3 <- MakeADFun(data = tmbdata11.3,
                      parameters = tmbpars11.3,
                      DLL = "multiGLMM_11",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_11.3$fn()
tictoc::tic()
opt_11.3 <- nlminb(obj_11.3$par, obj_11.3$fn, obj_11.3$gr)
tictoc::toc()
sdr_11.3 <- sdreport(obj_11.3)
```

```{r summaries_11, error=TRUE, dependson="datasimu11"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.5)),
      summary(sdr_11.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.5)),
      summary(sdr_11.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.5)),
      summary(sdr_11.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.5)),
      opt_11.1$par, ## 1e4 pairs
      opt_11.2$par, ## 25e3
      opt_11.3$par) ## 50e3
```

### 12

```{r datasimu12}
datasimu12 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                       beta = c(-2, -1.5), gamma = c(1.2, 1),
                       w = c(3, 5), S = matrix(c(1.0, 0.5, 0.0, 0.0,
                                                 0.5, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 0.5, 0.0,
                                                 0.0, 0.0, 0.0, 0.5),
                                               4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(090722)
df12.1 <- datasimu12(J = 1e4)
df12.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata12.1 <- list(
    Y = as.matrix(df12.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df12.1$t,
    delta = 80)
tmbpars12.1 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 1e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)),
                    rhoZ = atanh(0.5))
## ---------------------------------------------------------------------
set.seed(090806)
df12.2 <- datasimu12(J = 2e4)
df12.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata12.2 <- list(
    Y = as.matrix(df12.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df12.2$t,
    delta = 80)
tmbpars12.2 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 2e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)),
                    rhoZ = atanh(0.5))
## ---------------------------------------------------------------------
set.seed(090843)
df12.3 <- datasimu12(J = 3e4)
df12.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata12.3 <- list(
    Y = as.matrix(df12.3 %>% select(y1:y3)),
    Z = bdiag(replicate(3e4, rep(1, 2), simplify = FALSE)),
    T = df12.3$t,
    delta = 80)
tmbpars12.3 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 3e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)),
                    rhoZ = atanh(0.5))
```

```{r models_12, error=TRUE, warning=FALSE, dependson="datasimu12"}
## compile("multiGLMM_12.cpp")
dyn.load(dynlib("multiGLMM_12"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_12.1 <- MakeADFun(data = tmbdata12.1,
                      parameters = tmbpars12.1,
                      DLL = "multiGLMM_12",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_12.1$fn()
tictoc::tic()
opt_12.1 <- nlminb(obj_12.1$par, obj_12.1$fn, obj_12.1$gr)
tictoc::toc()
sdr_12.1 <- sdreport(obj_12.1)
## ---------------------------------------------------------------------
obj_12.2 <- MakeADFun(data = tmbdata12.2,
                      parameters = tmbpars12.2,
                      DLL = "multiGLMM_12",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_12.2$fn()
tictoc::tic()
opt_12.2 <- nlminb(obj_12.2$par, obj_12.2$fn, obj_12.2$gr)
tictoc::toc()
sdr_12.2 <- sdreport(obj_12.2)
##----------------------------------------------------------------------
obj_12.3 <- MakeADFun(data = tmbdata12.3,
                      parameters = tmbpars12.3,
                      DLL = "multiGLMM_12",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_12.3$fn()
tictoc::tic()
opt_12.3 <- nlminb(obj_12.3$par, obj_12.3$fn, obj_12.3$gr)
tictoc::toc()
sdr_12.3 <- sdreport(obj_12.3)
```

```{r summaries_12, error=TRUE, dependson="datasimu12"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.5)),
      summary(sdr_12.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.5)),
      summary(sdr_12.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.5)),
      summary(sdr_12.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.5)),
      opt_12.1$par, ## 1e4 pairs
      opt_12.2$par, ## 25e3
      opt_12.3$par) ## 50e3
```

### 13

```{r datasimu13}
datasimu13 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                       beta = c(-2, -1.5), gamma = c(1.2, 1),
                       w = c(3, 5), S = matrix(c(1.0, 0.0, 0.0, 0.0,
                                                 0.0, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 0.5, 0.2,
                                                 0.0, 0.0, 0.2, 0.5),
                                               4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(105757)
df13.1 <- datasimu13(J = 1e4)
df13.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata13.1 <- list(
    Y = as.matrix(df13.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df13.1$t,
    delta = 80)
tmbpars13.1 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 1e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = atanh(0.2))
## ---------------------------------------------------------------------
set.seed(110249)
df13.2 <- datasimu13(J = 2e4)
df13.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata13.2 <- list(
    Y = as.matrix(df13.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df13.2$t,
    delta = 80)
tmbpars13.2 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 2e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = atanh(0.2))
## ---------------------------------------------------------------------
set.seed(110340)
df13.3 <- datasimu13(J = 3e4)
df13.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata13.3 <- list(
    Y = as.matrix(df13.3 %>% select(y1:y3)),
    Z = bdiag(replicate(3e4, rep(1, 2), simplify = FALSE)),
    T = df13.3$t,
    delta = 80)
tmbpars13.3 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 3e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = atanh(0.2))
```

```{r models_13, error=TRUE, warning=FALSE, dependson="datasimu13"}
## compile("multiGLMM_13.cpp")
dyn.load(dynlib("multiGLMM_13"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_13.1 <- MakeADFun(data = tmbdata13.1,
                      parameters = tmbpars13.1,
                      DLL = "multiGLMM_13",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_13.1$fn()
tictoc::tic()
opt_13.1 <- nlminb(obj_13.1$par, obj_13.1$fn, obj_13.1$gr)
tictoc::toc()
sdr_13.1 <- sdreport(obj_13.1)
## ---------------------------------------------------------------------
obj_13.2 <- MakeADFun(data = tmbdata13.2,
                      parameters = tmbpars13.2,
                      DLL = "multiGLMM_13",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_13.2$fn()
tictoc::tic()
opt_13.2 <- nlminb(obj_13.2$par, obj_13.2$fn, obj_13.2$gr)
tictoc::toc()
sdr_13.2 <- sdreport(obj_13.2)
##----------------------------------------------------------------------
obj_13.3 <- MakeADFun(data = tmbdata13.3,
                      parameters = tmbpars13.3,
                      DLL = "multiGLMM_13",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_13.3$fn()
tictoc::tic()
opt_13.3 <- nlminb(obj_13.3$par, obj_13.3$fn, obj_13.3$gr)
tictoc::toc()
sdr_13.3 <- sdreport(obj_13.3)
```

```{r summaries_13, error=TRUE, dependson="datasimu13"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.2)),
      summary(sdr_13.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.2)),
      summary(sdr_13.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.2)),
      summary(sdr_13.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5, log(1), log(0.5), atanh(0.2)),
      opt_13.1$par, ## 1e4 pairs
      opt_13.2$par, ## 25e3
      opt_13.3$par) ## 50e3
```

### 14

```{r datasimu14}
datasimu14 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                       beta = c(-2, -1.5), gamma = c(1.2, 1),
                       w = c(3, 5), S = matrix(c(1.0, 0.0, 0.0, 0.0,
                                                 0.0, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 0.5, 0.2,
                                                 0.0, 0.0, 0.2, 0.5),
                                               4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(131606)
df14.1 <- datasimu14(J = 1e4)
df14.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata14.1 <- list(
    Y = as.matrix(df14.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df14.1$t,
    delta = 80)
tmbpars14.1 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 1e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)),
                    rhoZ = atanh(0.2))
## ---------------------------------------------------------------------
set.seed(131642)
df14.2 <- datasimu14(J = 2e4)
df14.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata14.2 <- list(
    Y = as.matrix(df14.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df14.2$t,
    delta = 80)
tmbpars14.2 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 2e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)),
                    rhoZ = atanh(0.2))
## ---------------------------------------------------------------------
set.seed(131713)
df14.3 <- datasimu14(J = 3e4)
df14.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata14.3 <- list(
    Y = as.matrix(df14.3 %>% select(y1:y3)),
    Z = bdiag(replicate(3e4, rep(1, 2), simplify = FALSE)),
    T = df14.3$t,
    delta = 80)
tmbpars14.3 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 3e4, ncol = 4),
                    logs2 = c(log(1), log(1), log(0.5), log(0.5)),
                    rhoZ = atanh(0.2))
```

```{r models_14, error=TRUE, warning=FALSE, dependson="datasimu14"}
## compile("multiGLMM_14.cpp")
dyn.load(dynlib("multiGLMM_14"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_14.1 <- MakeADFun(data = tmbdata14.1,
                      parameters = tmbpars14.1,
                      DLL = "multiGLMM_14",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_14.1$fn()
tictoc::tic()
opt_14.1 <- nlminb(obj_14.1$par, obj_14.1$fn, obj_14.1$gr)
tictoc::toc()
sdr_14.1 <- sdreport(obj_14.1)
## ---------------------------------------------------------------------
obj_14.2 <- MakeADFun(data = tmbdata14.2,
                      parameters = tmbpars14.2,
                      DLL = "multiGLMM_14",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_14.2$fn()
tictoc::tic()
opt_14.2 <- nlminb(obj_14.2$par, obj_14.2$fn, obj_14.2$gr)
tictoc::toc()
sdr_14.2 <- sdreport(obj_14.2)
##----------------------------------------------------------------------
obj_14.3 <- MakeADFun(data = tmbdata14.3,
                      parameters = tmbpars14.3,
                      DLL = "multiGLMM_14",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_14.3$fn()
tictoc::tic()
opt_14.3 <- nlminb(obj_14.3$par, obj_14.3$fn, obj_14.3$gr)
tictoc::toc()
sdr_14.3 <- sdreport(obj_14.3)
```

```{r summaries_14, error=TRUE, dependson="datasimu14"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.2)),
      summary(sdr_14.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.2)),
      summary(sdr_14.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.2)),
      summary(sdr_14.3, "fixed"))
```

```{r}
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(1), log(0.5), log(0.5), atanh(0.2)),
      opt_14.1$par, ## 1e4 pairs
      opt_14.2$par, ## 25e3
      opt_14.3$par) ## 50e3
```

### 15

```{r datasimu15}
datasimu15 <- function(J, from = 30, to = 79.5, by = 0.5, delta = 80,
                       beta = c(-2, -1.5), gamma = c(1.2, 1),
                       w = c(3, 5), S = matrix(c(1.0, 0.4, 0.0, 0.0,
                                                 0.4, 1.0, 0.0, 0.0,
                                                 0.0, 0.0, 0.5, 0.2,
                                                 0.0, 0.0, 0.2, 0.5),
                                               4, 4))
{
    out <- data.frame("i" = rep(seq(2), times = J),
                      "j" = factor(rep(seq(J), each = 2)),
                      "p1" = NA, "p2" = NA, "p3" = NA,
                      "y1" = NA, "y2" = NA, "y3" = NA,
                      "t" = rep(seq(from = from, to = to, by = by),
                                length.out = 2 * J))
    K <- dim(S)[1]/2 + 1
    ladim <- 2 * (K - 1) ## latent effects dimension
    B <- mvtnorm::rmvnorm(J, mean = rep(0, ladim), sigma = S)
    Z <- bdiag(replicate(J, rep(1, 2), simplify = FALSE))
    R <- Z %*% B
    risk1 <- exp(beta[1] + R[ , 1])
    risk2 <- exp(beta[2] + R[ , 2])
    level <- 1 + risk1 + risk2
    out$p1 <- risk1/level *
        w[1] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[1] * atanh(2 * out$t/delta - 1) - gamma[1] - R[ , 3])
    out$p2 <- risk2/level *
        w[2] * delta/(2 * out$t * (delta - out$t)) *
        dnorm(w[2] * atanh(2 * out$t/delta - 1) - gamma[2] - R[ , 4])
    out$p3 <- with(out, 1 - p1 - p2)
    out[ , c("y1", "y2", "y3")] <-
        mc2d::rmultinomial(2 * J, 1,
                           prob = with(out, cbind(p1, p2, p3)))
    return(out)
}
## ---------------------------------------------------------------------
set.seed(130038)
df15.1 <- datasimu15(J = 1e4)
df15.1 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata15.1 <- list(
    Y = as.matrix(df15.1 %>% select(y1:y3)),
    Z = bdiag(replicate(1e4, rep(1, 2), simplify = FALSE)),
    T = df15.1$t,
    delta = 80)
tmbpars15.1 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 1e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = c(atanh(0.4), atanh(0.2)))
## ---------------------------------------------------------------------
set.seed(130127)
df15.2 <- datasimu15(J = 2e4)
df15.2 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata15.2 <- list(
    Y = as.matrix(df15.2 %>% select(y1:y3)),
    Z = bdiag(replicate(2e4, rep(1, 2), simplify = FALSE)),
    T = df15.2$t,
    delta = 80)
tmbpars15.2 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 2e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = c(atanh(0.4), atanh(0.2)))
## ---------------------------------------------------------------------
set.seed(130215)
df15.3 <- datasimu15(J = 3e4)
df15.3 %>% dplyr::select(y1:y3) %>% colSums() %>% prop.table()
tmbdata15.3 <- list(
    Y = as.matrix(df15.3 %>% select(y1:y3)),
    Z = bdiag(replicate(3e4, rep(1, 2), simplify = FALSE)),
    T = df15.3$t,
    delta = 80)
tmbpars15.3 <- list(beta1 = -2,
                    beta2 = -1.5,
                    gama1 = 1.2,
                    gama2 = 1,
                    w1 = 3,
                    w2 = 5,
                    R = matrix(0, nrow = 3e4, ncol = 4),
                    logs2 = c(log(1), log(0.5)),
                    rhoZ = c(atanh(0.4), atanh(0.2)))
```

```{r models_15, error=TRUE, warning=FALSE, dependson="datasimu15"}
## compile("multiGLMM_15.cpp")
dyn.load(dynlib("multiGLMM_15"))
openmp(n = 10)
## ---------------------------------------------------------------------
obj_15.1 <- MakeADFun(data = tmbdata15.1,
                      parameters = tmbpars15.1,
                      DLL = "multiGLMM_15",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_15.1$fn()
tictoc::tic()
opt_15.1 <- nlminb(obj_15.1$par, obj_15.1$fn, obj_15.1$gr)
tictoc::toc()
sdr_15.1 <- sdreport(obj_15.1)
## ---------------------------------------------------------------------
obj_15.2 <- MakeADFun(data = tmbdata15.2,
                      parameters = tmbpars15.2,
                      DLL = "multiGLMM_15",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_15.2$fn()
tictoc::tic()
opt_15.2 <- nlminb(obj_15.2$par, obj_15.2$fn, obj_15.2$gr)
tictoc::toc()
sdr_15.2 <- sdreport(obj_15.2)
##----------------------------------------------------------------------
obj_15.3 <- MakeADFun(data = tmbdata15.3,
                      parameters = tmbpars15.3,
                      DLL = "multiGLMM_15",
                      random = "R",
                      hessian = TRUE, silent = TRUE)
obj_15.3$fn()
tictoc::tic()
opt_15.3 <- nlminb(obj_15.3$par, obj_15.3$fn, obj_15.3$gr)
tictoc::toc()
sdr_15.3 <- sdreport(obj_15.3)
```

```{r summaries_15, error=TRUE, dependson="datasimu15"}
## 1e4 -----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(0.5), atanh(0.4), atanh(0.2)),
      summary(sdr_15.1, "fixed"))
## 25e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(0.5), atanh(0.4), atanh(0.2)),
      summary(sdr_15.2, "fixed"))
## 50e3 ----------------------------------------------------------------
cbind(c(-2, -1.5, 1.2, 1, 3, 5,
        log(1), log(0.5), atanh(0.4), atanh(0.2)),
      summary(sdr_15.3, "fixed"))
```
